# 04a. Геофичи вокруг ЖК (OSM)

Считаем геопризнаки окружения каждого ЖК по координатам (`lat`/`lng`) через
OpenStreetMap (OSMnx 2.x). Фичи считаются **на уровне `project_id`** (один
репрезентативный центроид на проект, ~750 точек), а не на каждую из 4.6M строк —
это на три порядка дешевле, а гео-окружение проекта от среза к срезу не меняется.

Слои OSM кэшируются в `data/interim/osm_cache/*.gpkg`, поэтому повторный запуск
не дёргает Overpass. Результат → `data/processed/geo_features.parquet` (индекс
`project_id`); мерджится в модельный датасет в `04_features` по `project_id`.

In [1]:
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display
pd.set_option("display.max_columns", 80)

_cwd = Path.cwd().resolve()
REPO_ROOT = _cwd if (_cwd / "data").is_dir() else _cwd.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import src.geo_features as geo
from src.config import EDA_LEFT_PARQUET, OSM_CACHE_DIR, GEO_FEATURES_PARQUET

df = pd.read_parquet(EDA_LEFT_PARQUET, columns=["project_id", "project_name", "lat", "lng"])
print(f"{len(df):,} строк, {df['project_id'].nunique()} уникальных project_id")

4,631,451 строк, 758 уникальных project_id

## 1. Точки проектов

Один центроид на `project_id` (median lat/lng). Координаты вне правдоподобных
границ Москвы/МО и нули (`0.0`) отбрасываются.

In [3]:
points = geo.project_points(df)
print(f"Проектов с валидными координатами: {len(points)}")
print(f"Отброшено проектов (нет/битые координаты): "
      f"{df['project_id'].nunique() - len(points)}")
display(points[["project_id", "project_name", "lat", "lng"]].head())

Проектов с валидными координатами: 752
Отброшено проектов (нет/битые координаты): 6

   project_id       project_name       lat       lng
0         551       Wellton Park  55.77341  37.47303
1         676         Union Park  55.78119  37.46896
2         683       Внуково Парк  55.59549  37.20044
3         688        Москва А101  55.56923   37.4905
4         696  Первый Московский  55.60198  37.36408

## 2. Скачивание слоёв OSM

Качаем потайлово (область режется на сетку); кэш по тайлам позволяет прерывать и продолжать — готовый слой берётся из кэша.

In [4]:
# накопитель слоёв; каждый слой ниже — отдельная ячейка (можно перезапускать по одному)
layers = {}
print("слои для скачивания:", list(geo.OSM_TAGS))

слои для скачивания: ['metro', 'schools', 'green', 'water', 'industrial', 'cemetery', 'power_lines', 'major_roads', 'railway']

**Точечные слои (тайл 10 км) — лёгкие.**

In [5]:
layers["metro"] = geo.fetch_layer(points, OSM_CACHE_DIR, "metro")

[metro] сетка ~10 км: 164 тайлов
  [metro] скачиваю 164 тайлов из OSM…
  [metro] тайл 1/164 | +5 (Σ5) |    0c | прошло  0.0м · ост.~ 0.1м
  [metro] тайл 2/164 | +2 (Σ7) |    0c | прошло  0.0м · ост.~ 0.1м
  [metro] тайл 3/164 | +0 (Σ7) |    0c | прошло  0.0м · ост.~ 0.1м
  [metro] тайл 4/164 | +4 (Σ11) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 5/164 | +10 (Σ21) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 6/164 | +6 (Σ27) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 7/164 | +7 (Σ34) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 8/164 | +16 (Σ50) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 9/164 | +6 (Σ56) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 10/164 | +70 (Σ126) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 11/164 | +13 (Σ139) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 12/164 | +27 (Σ166) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 13/164 | +9 (Σ175) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 14/164 | +56 (Σ231) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 15/164 | +189 (Σ420) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 16/164 | +68 (Σ488) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 17/164 | +31 (Σ519) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 18/164 | +23 (Σ542) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 19/164 | +47 (Σ589) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 20/164 | +22 (Σ611) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 21/164 | +84 (Σ695) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 22/164 | +9 (Σ704) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 23/164 | +30 (Σ734) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 24/164 | +61 (Σ795) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 25/164 | +37 (Σ832) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 26/164 | +48 (Σ880) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 27/164 | +20 (Σ900) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 28/164 | +89 (Σ989) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 29/164 | +64 (Σ1,053) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 30/164 | +34 (Σ1,087) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 31/164 | +30 (Σ1,117) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 32/164 | +29 (Σ1,146) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 33/164 | +75 (Σ1,221) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 34/164 | +41 (Σ1,262) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 35/164 | +24 (Σ1,286) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 36/164 | +0 (Σ1,286) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 37/164 | +0 (Σ1,286) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 38/164 | +0 (Σ1,286) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 39/164 | +48 (Σ1,334) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 40/164 | +0 (Σ1,334) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 41/164 | +131 (Σ1,465) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 42/164 | +119 (Σ1,584) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 43/164 | +267 (Σ1,851) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 44/164 | +108 (Σ1,959) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 45/164 | +109 (Σ2,068) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 46/164 | +79 (Σ2,147) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 47/164 | +339 (Σ2,486) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 48/164 | +30 (Σ2,516) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 49/164 | +76 (Σ2,592) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 50/164 | +3 (Σ2,595) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 51/164 | +73 (Σ2,668) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 52/164 | +6 (Σ2,674) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 53/164 | +22 (Σ2,696) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 54/164 | +54 (Σ2,750) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 55/164 | +100 (Σ2,850) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 56/164 | +315 (Σ3,165) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 57/164 | +687 (Σ3,852) |    0c | прошло  0.0м · ост.~ 0.0м
  [metro] тайл 58/164 | +703 (Σ4,555) |    3c | прошло  0.1м · ост.~ 0.1м
  [metro] тайл 59/164 | +911 (Σ5,466) |   12c | прошло  0.3м · ост.~ 0.5м
  [metro] тайл 60/164 | +393 (Σ5,859) |   26c | прошло  0.7м · ост.~ 1.2м
  [metro] тайл 61/164 | +106 (Σ5,965) |    8c | прошло  0.8м · ост.~ 1.4м
  [metro] тайл 62/164 | +20 (Σ5,985) |   14c | прошло  1.1м · ост.~ 1.7м
  [metro] тайл 63/164 | +10 (Σ5,995) |  216c | прошло  4.7м · ост.~ 7.5м
  [metro] тайл 64/164 | +15 (Σ6,010) |    2c | прошло  4.7м · ост.~ 7.3м
  [metro] тайл 65/164 | +13 (Σ6,023) |    2c | прошло  4.7м · ост.~ 7.2м
  [metro] тайл 66/164 | +9 (Σ6,032) |    2c | прошло  4.7м · ост.~ 7.0м
  [metro] тайл 67/164 | +2 (Σ6,034) |    2c | прошло  4.8м · ост.~ 6.9м
  [metro] тайл 68/164 | +14 (Σ6,048) |    6c | прошло  4.9м · ост.~ 6.9м
  [metro] тайл 69/164 | +152 (Σ6,200) |  212c | прошло  8.4м · ост.~11.6м
  [metro] тайл 70/164 | +347 (Σ6,547) |   24c | прошло  8.8м · ост.~11.8м
  [metro] тайл 71/164 | +568 (Σ7,115) |  217c | прошло 12.4м · ост.~16.3м
  [metro] тайл 72/164 | +1477 (Σ8,592) |    3c | прошло 12.5м · ост.~15.9м
  [metro] тайл 73/164 | +1864 (Σ10,456) |   16c | прошло 12.7м · ост.~15.9м
  [metro] тайл 74/164 | +1626 (Σ12,082) |    4c | прошло 12.8м · ост.~15.6м
  [metro] тайл 75/164 | +805 (Σ12,887) |   99c | прошло 14.5м · ост.~17.2м
  [metro] тайл 76/164 | +117 (Σ13,004) |    3c | прошло 14.5м · ост.~16.8м
  [metro] тайл 77/164 | +28 (Σ13,032) |    2c | прошло 14.5м · ост.~16.4м
  [metro] тайл 78/164 | +19 (Σ13,051) |    2c | прошло 14.6м · ост.~16.1м
  [metro] тайл 79/164 | +48 (Σ13,099) |   16c | прошло 14.8м · ост.~16.0м
  [metro] тайл 80/164 | +76 (Σ13,175) |    2c | прошло 14.9м · ост.~15.6м
  [metro] тайл 81/164 | +39 (Σ13,214) |    2c | прошло 14.9м · ост.~15.3м
  [metro] тайл 82/164 | +0 (Σ13,214) |    1c | прошло 14.9м · ост.~14.9м
  [metro] тайл 83/164 | +20 (Σ13,234) |    2c | прошло 14.9м · ост.~14.6м
  [metro] тайл 84/164 | +66 (Σ13,300) |    2c | прошло 15.0м · ост.~14.3м
  [metro] тайл 85/164 | +117 (Σ13,417) |    2c | прошло 15.0м · ост.~13.9м
  [metro] тайл 86/164 | +285 (Σ13,702) |    2c | прошло 15.0м · ост.~13.6м
  [metro] тайл 87/164 | +1270 (Σ14,972) |    2c | прошло 15.1м · ост.~13.3м
  [metro] тайл 88/164 | +1854 (Σ16,826) |    4c | прошло 15.1м · ост.~13.1м
  [metro] тайл 89/164 | +1188 (Σ18,014) |    4c | прошло 15.2м · ост.~12.8м
  [metro] тайл 90/164 | +570 (Σ18,584) |    2c | прошло 15.2м · ост.~12.5м
  [metro] тайл 91/164 | +67 (Σ18,651) |    2c | прошло 15.3м · ост.~12.3м
  [metro] тайл 92/164 | +3 (Σ18,654) |    2c | прошло 15.3м · ост.~12.0м
  [metro] тайл 93/164 | +23 (Σ18,677) |    2c | прошло 15.3м · ост.~11.7м
  [metro] тайл 94/164 | +16 (Σ18,693) |    2c | прошло 15.4м · ост.~11.4м
  [metro] тайл 95/164 | +52 (Σ18,745) |    2c | прошло 15.4м · ост.~11.2м
  [metro] тайл 96/164 | +73 (Σ18,818) |    2c | прошло 15.4м · ост.~10.9м
  [metro] тайл 97/164 | +37 (Σ18,855) |    2c | прошло 15.4м · ост.~10.7м
  [metro] тайл 98/164 | +65 (Σ18,920) |    2c | прошло 15.5м · ост.~10.4м
  [metro] тайл 99/164 | +283 (Σ19,203) |    2c | прошло 15.5м · ост.~10.2м
  [metro] тайл 100/164 | +918 (Σ20,121) |    2c | прошло 15.5м · ост.~10.0м
  [metro] тайл 101/164 | +320 (Σ20,441) |    2c | прошло 15.6м · ост.~ 9.7м
  [metro] тайл 102/164 | +180 (Σ20,621) |    2c | прошло 15.6м · ост.~ 9.5м
  [metro] тайл 103/164 | +144 (Σ20,765) |    2c | прошло 15.6м · ост.~ 9.3м
  [metro] тайл 104/164 | +15 (Σ20,780) |    2c | прошло 15.7м · ост.~ 9.0м
  [metro] тайл 105/164 | +2 (Σ20,782) |    2c | прошло 15.7м · ост.~ 8.8м
  [metro] тайл 106/164 | +6 (Σ20,788) |    2c | прошло 15.7м · ост.~ 8.6м
  [metro] тайл 107/164 | +49 (Σ20,837) |    2c | прошло 15.8м · ост.~ 8.4м
  [metro] тайл 108/164 | +80 (Σ20,917) |    2c | прошло 15.8м · ост.~ 8.2м
  [metro] тайл 109/164 | +0 (Σ20,917) |    1c | прошло 15.8м · ост.~ 8.0м
  [metro] тайл 110/164 | +12 (Σ20,929) |    2c | прошло 15.9м · ост.~ 7.8м
  [metro] тайл 111/164 | +47 (Σ20,976) |    2c | прошло 15.9м · ост.~ 7.6м
  [metro] тайл 112/164 | +106 (Σ21,082) |    2c | прошло 15.9м · ост.~ 7.4м
  [metro] тайл 113/164 | +130 (Σ21,212) |    3c | прошло 16.0м · ост.~ 7.2м
  [metro] тайл 114/164 | +192 (Σ21,404) |    2c | прошло 16.0м · ост.~ 7.0м
  [metro] тайл 115/164 | +28 (Σ21,432) |    3c | прошло 16.0м · ост.~ 6.8м
  [metro] тайл 116/164 | +18 (Σ21,450) |  104c | прошло 17.8м · ост.~ 7.4м
  [metro] тайл 117/164 | +13 (Σ21,463) |   16c | прошло 18.0м · ост.~ 7.2м
  [metro] тайл 118/164 | +16 (Σ21,479) |   23c | прошло 18.4м · ост.~ 7.2м
  [metro] тайл 119/164 | +6 (Σ21,485) |  132c | прошло 20.6м · ост.~ 7.8м
  [metro] тайл 120/164 | +125 (Σ21,610) |  112c | прошло 22.5м · ост.~ 8.3м
  [metro] тайл 121/164 | +27 (Σ21,637) |    4c | прошло 22.6м · ост.~ 8.0м
  [metro] тайл 122/164 | +56 (Σ21,693) |    2c | прошло 22.6м · ост.~ 7.8м
  [metro] тайл 123/164 | +6 (Σ21,699) |    2c | прошло 22.6м · ост.~ 7.5м
  [metro] тайл 124/164 | +9 (Σ21,708) |    2c | прошло 22.7м · ост.~ 7.3м
  [metro] тайл 125/164 | +67 (Σ21,775) |    2c | прошло 22.7м · ост.~ 7.1м
  [metro] тайл 126/164 | +73 (Σ21,848) |    2c | прошло 22.7м · ост.~ 6.9м
  [metro] тайл 127/164 | +0 (Σ21,848) |    1c | прошло 22.8м · ост.~ 6.6м
  [metro] тайл 128/164 | +20 (Σ21,868) |    2c | прошло 22.8м · ост.~ 6.4м
  [metro] тайл 129/164 | +0 (Σ21,868) |    2c | прошло 22.8м · ост.~ 6.2м
  [metro] тайл 130/164 | +12 (Σ21,880) |    2c | прошло 22.8м · ост.~ 6.0м
  [metro] тайл 131/164 | +35 (Σ21,915) |    2c | прошло 22.9м · ост.~ 5.8м
  [metro] тайл 132/164 | +9 (Σ21,924) |   94c | прошло 24.5м · ост.~ 5.9м
  [metro] тайл 133/164 | +14 (Σ21,938) |    3c | прошло 24.5м · ост.~ 5.7м
  [metro] тайл 134/164 | +15 (Σ21,953) |    2c | прошло 24.5м · ост.~ 5.5м
  [metro] тайл 135/164 | +17 (Σ21,970) |    2c | прошло 24.6м · ост.~ 5.3м
  [metro] тайл 136/164 | +14 (Σ21,984) |    8c | прошло 24.7м · ост.~ 5.1м
  [metro] тайл 137/164 | +3 (Σ21,987) |    2c | прошло 24.7м · ост.~ 4.9м
  [metro] тайл 138/164 | +9 (Σ21,996) |   90c | прошло 26.2м · ост.~ 4.9м
  [metro] тайл 139/164 | +0 (Σ21,996) |    1c | прошло 26.2м · ост.~ 4.7м
  [metro] тайл 140/164 | +15 (Σ22,011) |    2c | прошло 26.3м · ост.~ 4.5м
  [metro] тайл 141/164 | +21 (Σ22,032) |    2c | прошло 26.3м · ост.~ 4.3м
  [metro] тайл 142/164 | +0 (Σ22,032) |   15c | прошло 26.5м · ост.~ 4.1м
  [metro] тайл 143/164 | +72 (Σ22,104) |    2c | прошло 26.6м · ост.~ 3.9м
  [metro] тайл 144/164 | +79 (Σ22,183) |    2c | прошло 26.6м · ост.~ 3.7м
  [metro] тайл 145/164 | +16 (Σ22,199) |    2c | прошло 26.6м · ост.~ 3.5м
  [metro] тайл 146/164 | +22 (Σ22,221) |    2c | прошло 26.6м · ост.~ 3.3м
  [metro] тайл 147/164 | +0 (Σ22,221) |    1c | прошло 26.7м · ост.~ 3.1м
  [metro] тайл 148/164 | +60 (Σ22,281) |    2c | прошло 26.7м · ост.~ 2.9м
  [metro] тайл 149/164 | +168 (Σ22,449) |    2c | прошло 26.7м · ост.~ 2.7м
  [metro] тайл 150/164 | +9 (Σ22,458) |    2c | прошло 26.7м · ост.~ 2.5м
  [metro] тайл 151/164 | +4 (Σ22,462) |    2c | прошло 26.8м · ост.~ 2.3м
  [metro] тайл 152/164 | +6 (Σ22,468) |    2c | прошло 26.8м · ост.~ 2.1м
  [metro] тайл 153/164 | +20 (Σ22,488) |    2c | прошло 26.8м · ост.~ 1.9м
  [metro] тайл 154/164 | +25 (Σ22,513) |    2c | прошло 26.9м · ост.~ 1.7м
  [metro] тайл 155/164 | +0 (Σ22,513) |    1c | прошло 26.9м · ост.~ 1.6м
  [metro] тайл 156/164 | +13 (Σ22,526) |    2c | прошло 26.9м · ост.~ 1.4м
  [metro] тайл 157/164 | +6 (Σ22,532) |    2c | прошло 26.9м · ост.~ 1.2м
  [metro] тайл 158/164 | +0 (Σ22,532) |    1c | прошло 26.9м · ост.~ 1.0м
  [metro] тайл 159/164 | +0 (Σ22,532) |    1c | прошло 27.0м · ост.~ 0.8м
  [metro] тайл 160/164 | +3 (Σ22,535) |    2c | прошло 27.0м · ост.~ 0.7м
  [metro] тайл 161/164 | +25 (Σ22,560) |    2c | прошло 27.0м · ост.~ 0.5м
  [metro] тайл 162/164 | +0 (Σ22,560) |    0c | прошло 27.0м · ост.~ 0.3м
  [metro] тайл 163/164 | +5 (Σ22,565) |    2c | прошло 27.1м · ост.~ 0.2м
  [metro] тайл 164/164 | +0 (Σ22,565) |    0c | прошло 27.1м · ост.~ 0.0м
  [metro] ГОТОВО: 22,555 объектов

In [12]:
layers["schools"] = geo.fetch_layer(points, OSM_CACHE_DIR, "schools")

[schools] сетка ~10 км: 164 тайлов
  [schools] скачиваю 164 тайлов из OSM…
  [schools] тайл 1/164 | +6 (Σ6) |    0c | прошло  0.0м · ост.~ 0.1м
  [schools] тайл 2/164 | +16 (Σ22) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 3/164 | +0 (Σ22) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 4/164 | +1 (Σ23) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 5/164 | +10 (Σ33) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 6/164 | +1 (Σ34) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 7/164 | +1 (Σ35) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 8/164 | +5 (Σ40) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 9/164 | +6 (Σ46) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 10/164 | +6 (Σ52) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 11/164 | +29 (Σ81) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 12/164 | +7 (Σ88) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 13/164 | +6 (Σ94) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 14/164 | +4 (Σ98) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 15/164 | +53 (Σ151) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 16/164 | +10 (Σ161) |    0c | прошло  0.0м · ост.~ 0.0м
  [schools] тайл 17/164 | +7 (Σ168) |    2c | прошло  0.0м · ост.~ 0.3м
  [schools] тайл 18/164 | +17 (Σ185) |    2c | прошло  0.1м · ост.~ 0.5м
  [schools] тайл 19/164 | +21 (Σ206) |    2c | прошло  0.1м · ост.~ 0.6м
  [schools] тайл 20/164 | +4 (Σ210) |    2c | прошло  0.1м · ост.~ 0.9м
  [schools] тайл 21/164 | +30 (Σ240) |    2c | прошло  0.2м · ост.~ 1.0м
  [schools] тайл 22/164 | +1 (Σ241) |    2c | прошло  0.2м · ост.~ 1.1м
  [schools] тайл 23/164 | +5 (Σ246) |    3c | прошло  0.2м · ост.~ 1.4м
  [schools] тайл 24/164 | +16 (Σ262) |    2c | прошло  0.3м · ост.~ 1.5м
  [schools] тайл 25/164 | +3 (Σ265) |    2c | прошло  0.3м · ост.~ 1.6м
  [schools] тайл 26/164 | +5 (Σ270) |    2c | прошло  0.3м · ост.~ 1.7м
  [schools] тайл 27/164 | +3 (Σ273) |    6c | прошло  0.4м · ост.~ 2.1м
  [schools] тайл 28/164 | +25 (Σ298) |    2c | прошло  0.4м · ост.~ 2.1м
  [schools] тайл 29/164 | +32 (Σ330) |    2c | прошло  0.5м · ост.~ 2.2м
  [schools] тайл 30/164 | +11 (Σ341) |    2c | прошло  0.5м · ост.~ 2.2м
  [schools] тайл 31/164 | +47 (Σ388) |    2c | прошло  0.5м · ост.~ 2.3м
  [schools] тайл 32/164 | +16 (Σ404) |    2c | прошло  0.6м · ост.~ 2.3м
  [schools] тайл 33/164 | +10 (Σ414) |    2c | прошло  0.6м · ост.~ 2.3м
  [schools] тайл 34/164 | +13 (Σ427) |    2c | прошло  0.6м · ост.~ 2.3м
  [schools] тайл 35/164 | +22 (Σ449) |    2c | прошло  0.6м · ост.~ 2.4м
  [schools] тайл 36/164 | +1 (Σ450) |    2c | прошло  0.7м · ост.~ 2.4м
  [schools] тайл 37/164 | +0 (Σ450) |    0c | прошло  0.7м · ост.~ 2.3м
  [schools] тайл 38/164 | +0 (Σ450) |    0c | прошло  0.7м · ост.~ 2.3м
  [schools] тайл 39/164 | +8 (Σ458) |    2c | прошло  0.7м · ост.~ 2.3м
  [schools] тайл 40/164 | +3 (Σ461) |    2c | прошло  0.7м · ост.~ 2.3м
  [schools] тайл 41/164 | +25 (Σ486) |    2c | прошло  0.8м · ост.~ 2.3м
  [schools] тайл 42/164 | +17 (Σ503) |    2c | прошло  0.8м · ост.~ 2.3м
  [schools] тайл 43/164 | +107 (Σ610) |    2c | прошло  0.8м · ост.~ 2.3м
  [schools] тайл 44/164 | +33 (Σ643) |    2c | прошло  0.8м · ост.~ 2.3м
  [schools] тайл 45/164 | +68 (Σ711) |    2c | прошло  0.9м · ост.~ 2.3м
  [schools] тайл 46/164 | +26 (Σ737) |    2c | прошло  0.9м · ост.~ 2.3м
  [schools] тайл 47/164 | +158 (Σ895) |    2c | прошло  0.9м · ост.~ 2.3м
  [schools] тайл 48/164 | +2 (Σ897) |    2c | прошло  1.0м · ост.~ 2.3м
  [schools] тайл 49/164 | +48 (Σ945) |    2c | прошло  1.0м · ост.~ 2.3м
  [schools] тайл 50/164 | +2 (Σ947) |    2c | прошло  1.0м · ост.~ 2.3м
  [schools] тайл 51/164 | +60 (Σ1,007) |    2c | прошло  1.0м · ост.~ 2.3м
  [schools] тайл 52/164 | +6 (Σ1,013) |    1c | прошло  1.1м · ост.~ 2.3м
  [schools] тайл 53/164 | +6 (Σ1,019) |    2c | прошло  1.1м · ост.~ 2.3м
  [schools] тайл 54/164 | +11 (Σ1,030) |    2c | прошло  1.1м · ост.~ 2.3м
  [schools] тайл 55/164 | +25 (Σ1,055) |    2c | прошло  1.1м · ост.~ 2.3м
  [schools] тайл 56/164 | +57 (Σ1,112) |    2c | прошло  1.2м · ост.~ 2.3м
  [schools] тайл 57/164 | +210 (Σ1,322) |    2c | прошло  1.2м · ост.~ 2.3м
  [schools] тайл 58/164 | +243 (Σ1,565) |    2c | прошло  1.2м · ост.~ 2.3м
  [schools] тайл 59/164 | +366 (Σ1,931) |    4c | прошло  1.3м · ост.~ 2.3м
  [schools] тайл 60/164 | +168 (Σ2,099) |    2c | прошло  1.3м · ост.~ 2.3м
  [schools] тайл 61/164 | +20 (Σ2,119) |    2c | прошло  1.4м · ост.~ 2.3м
  [schools] тайл 62/164 | +3 (Σ2,122) |    2c | прошло  1.4м · ост.~ 2.3м
  [schools] тайл 63/164 | +0 (Σ2,122) |    1c | прошло  1.4м · ост.~ 2.3м
  [schools] тайл 64/164 | +2 (Σ2,124) |    2c | прошло  1.4м · ост.~ 2.3м
  [schools] тайл 65/164 | +7 (Σ2,131) |    1c | прошло  1.5м · ост.~ 2.2м
  [schools] тайл 66/164 | +12 (Σ2,143) |    2c | прошло  1.5м · ост.~ 2.2м
  [schools] тайл 67/164 | +1 (Σ2,144) |    2c | прошло  1.5м · ост.~ 2.2м
  [schools] тайл 68/164 | +20 (Σ2,164) |    2c | прошло  1.6м · ост.~ 2.2м
  [schools] тайл 69/164 | +60 (Σ2,224) |    2c | прошло  1.6м · ост.~ 2.2м
  [schools] тайл 70/164 | +132 (Σ2,356) |    2c | прошло  1.6м · ост.~ 2.2м
  [schools] тайл 71/164 | +242 (Σ2,598) |    2c | прошло  1.6м · ост.~ 2.2м
  [schools] тайл 72/164 | +648 (Σ3,246) |    2c | прошло  1.7м · ост.~ 2.1м
  [schools] тайл 73/164 | +629 (Σ3,875) |    3c | прошло  1.7м · ост.~ 2.2м
  [schools] тайл 74/164 | +633 (Σ4,508) |    3c | прошло  1.8м · ост.~ 2.2м
  [schools] тайл 75/164 | +349 (Σ4,857) |    2c | прошло  1.8м · ост.~ 2.2м
  [schools] тайл 76/164 | +36 (Σ4,893) |    2c | прошло  1.8м · ост.~ 2.1м
  [schools] тайл 77/164 | +13 (Σ4,906) |    2c | прошло  1.9м · ост.~ 2.1м
  [schools] тайл 78/164 | +7 (Σ4,913) |    2c | прошло  1.9м · ост.~ 2.1м
  [schools] тайл 79/164 | +12 (Σ4,925) |    1c | прошло  1.9м · ост.~ 2.1м
  [schools] тайл 80/164 | +42 (Σ4,967) |    2c | прошло  1.9м · ост.~ 2.0м
  [schools] тайл 81/164 | +5 (Σ4,972) |    2c | прошло  2.0м · ост.~ 2.0м
  [schools] тайл 82/164 | +0 (Σ4,972) |    0c | прошло  2.0м · ост.~ 2.0м
  [schools] тайл 83/164 | +0 (Σ4,972) |    0c | прошло  2.0м · ост.~ 1.9м
  [schools] тайл 84/164 | +11 (Σ4,983) |    2c | прошло  2.0м · ост.~ 1.9м
  [schools] тайл 85/164 | +55 (Σ5,038) |    2c | прошло  2.1м · ост.~ 1.9м
  [schools] тайл 86/164 | +148 (Σ5,186) |    2c | прошло  2.1м · ост.~ 1.9м
  [schools] тайл 87/164 | +561 (Σ5,747) |    2c | прошло  2.1м · ост.~ 1.9м
  [schools] тайл 88/164 | +630 (Σ6,377) |    3c | прошло  2.2м · ост.~ 1.9м
  [schools] тайл 89/164 | +421 (Σ6,798) |    3c | прошло  2.2м · ост.~ 1.9м
  [schools] тайл 90/164 | +254 (Σ7,052) |    2c | прошло  2.3м · ост.~ 1.9м
  [schools] тайл 91/164 | +16 (Σ7,068) |    2c | прошло  2.3м · ост.~ 1.8м
  [schools] тайл 92/164 | +2 (Σ7,070) |    2c | прошло  2.3м · ост.~ 1.8м
  [schools] тайл 93/164 | +1 (Σ7,071) |    2c | прошло  2.4м · ост.~ 1.8м
  [schools] тайл 94/164 | +4 (Σ7,075) |    2c | прошло  2.4м · ост.~ 1.8м
  [schools] тайл 95/164 | +17 (Σ7,092) |    2c | прошло  2.4м · ост.~ 1.7м
  [schools] тайл 96/164 | +8 (Σ7,100) |    2c | прошло  2.4м · ост.~ 1.7м
  [schools] тайл 97/164 | +9 (Σ7,109) |    2c | прошло  2.5м · ост.~ 1.7м
  [schools] тайл 98/164 | +47 (Σ7,156) |    2c | прошло  2.5м · ост.~ 1.7м
  [schools] тайл 99/164 | +184 (Σ7,340) |    2c | прошло  2.5м · ост.~ 1.7м
  [schools] тайл 100/164 | +391 (Σ7,731) |    2c | прошло  2.5м · ост.~ 1.6м
  [schools] тайл 101/164 | +210 (Σ7,941) |    2c | прошло  2.6м · ост.~ 1.6м
  [schools] тайл 102/164 | +126 (Σ8,067) |    2c | прошло  2.6м · ост.~ 1.6м
  [schools] тайл 103/164 | +99 (Σ8,166) |    5c | прошло  2.7м · ост.~ 1.6м
  [schools] тайл 104/164 | +23 (Σ8,189) |    2c | прошло  2.7м · ост.~ 1.6м
  [schools] тайл 105/164 | +4 (Σ8,193) |    1c | прошло  2.7м · ост.~ 1.5м
  [schools] тайл 106/164 | +2 (Σ8,195) |    2c | прошло  2.8м · ост.~ 1.5м
  [schools] тайл 107/164 | +13 (Σ8,208) |    1c | прошло  2.8м · ост.~ 1.5м
  [schools] тайл 108/164 | +39 (Σ8,247) |    1c | прошло  2.8м · ост.~ 1.5м
  [schools] тайл 109/164 | +0 (Σ8,247) |    1c | прошло  2.8м · ост.~ 1.4м
  [schools] тайл 110/164 | +27 (Σ8,274) |    2c | прошло  2.9м · ост.~ 1.4м
  [schools] тайл 111/164 | +95 (Σ8,369) |    2c | прошло  2.9м · ост.~ 1.4м
  [schools] тайл 112/164 | +119 (Σ8,488) |    2c | прошло  2.9м · ост.~ 1.4м
  [schools] тайл 113/164 | +81 (Σ8,569) |    2c | прошло  2.9м · ост.~ 1.3м
  [schools] тайл 114/164 | +109 (Σ8,678) |    2c | прошло  3.0м · ост.~ 1.3м
  [schools] тайл 115/164 | +13 (Σ8,691) |    2c | прошло  3.0м · ост.~ 1.3м
  [schools] тайл 116/164 | +2 (Σ8,693) |    2c | прошло  3.0м · ост.~ 1.3м
  [schools] тайл 117/164 | +3 (Σ8,696) |    2c | прошло  3.1м · ост.~ 1.2м
  [schools] тайл 118/164 | +13 (Σ8,709) |    2c | прошло  3.1м · ост.~ 1.2м
  [schools] тайл 119/164 | +0 (Σ8,709) |    1c | прошло  3.1м · ост.~ 1.2м
  [schools] тайл 120/164 | +32 (Σ8,741) |    2c | прошло  3.1м · ост.~ 1.1м
  [schools] тайл 121/164 | +4 (Σ8,745) |    2c | прошло  3.1м · ост.~ 1.1м
  [schools] тайл 122/164 | +95 (Σ8,840) |    2c | прошло  3.2м · ост.~ 1.1м
  [schools] тайл 123/164 | +10 (Σ8,850) |    2c | прошло  3.2м · ост.~ 1.1м
  [schools] тайл 124/164 | +18 (Σ8,868) |    2c | прошло  3.2м · ост.~ 1.0м
  [schools] тайл 125/164 | +38 (Σ8,906) |    2c | прошло  3.3м · ост.~ 1.0м
  [schools] тайл 126/164 | +18 (Σ8,924) |    2c | прошло  3.3м · ост.~ 1.0м
  [schools] тайл 127/164 | +5 (Σ8,929) |    2c | прошло  3.3м · ост.~ 1.0м
  [schools] тайл 128/164 | +19 (Σ8,948) |    2c | прошло  3.3м · ост.~ 0.9м
  [schools] тайл 129/164 | +1 (Σ8,949) |    1c | прошло  3.4м · ост.~ 0.9м
  [schools] тайл 130/164 | +46 (Σ8,995) |    1c | прошло  3.4м · ост.~ 0.9м
  [schools] тайл 131/164 | +26 (Σ9,021) |    3c | прошло  3.4м · ост.~ 0.9м
  [schools] тайл 132/164 | +24 (Σ9,045) |    2c | прошло  3.5м · ост.~ 0.8м
  [schools] тайл 133/164 | +3 (Σ9,048) |    2c | прошло  3.5м · ост.~ 0.8м
  [schools] тайл 134/164 | +5 (Σ9,053) |    2c | прошло  3.5м · ост.~ 0.8м
  [schools] тайл 135/164 | +9 (Σ9,062) |    2c | прошло  3.5м · ост.~ 0.8м
  [schools] тайл 136/164 | +17 (Σ9,079) |    2c | прошло  3.6м · ост.~ 0.7м
  [schools] тайл 137/164 | +1 (Σ9,080) |    2c | прошло  3.6м · ост.~ 0.7м
  [schools] тайл 138/164 | +1 (Σ9,081) |    2c | прошло  3.6м · ост.~ 0.7м
  [schools] тайл 139/164 | +0 (Σ9,081) |    1c | прошло  3.6м · ост.~ 0.7м
  [schools] тайл 140/164 | +31 (Σ9,112) |    2c | прошло  3.7м · ост.~ 0.6м
  [schools] тайл 141/164 | +81 (Σ9,193) |    2c | прошло  3.7м · ост.~ 0.6м
  [schools] тайл 142/164 | +21 (Σ9,214) |    2c | прошло  3.7м · ост.~ 0.6м
  [schools] тайл 143/164 | +16 (Σ9,230) |    2c | прошло  3.8м · ост.~ 0.6м
  [schools] тайл 144/164 | +10 (Σ9,240) |    2c | прошло  3.8м · ост.~ 0.5м
  [schools] тайл 145/164 | +32 (Σ9,272) |    2c | прошло  3.8м · ост.~ 0.5м
  [schools] тайл 146/164 | +8 (Σ9,280) |    2c | прошло  3.8м · ост.~ 0.5м
  [schools] тайл 147/164 | +0 (Σ9,280) |    1c | прошло  3.8м · ост.~ 0.4м
  [schools] тайл 148/164 | +13 (Σ9,293) |    2c | прошло  3.9м · ост.~ 0.4м
  [schools] тайл 149/164 | +51 (Σ9,344) |    2c | прошло  3.9м · ост.~ 0.4м
  [schools] тайл 150/164 | +9 (Σ9,353) |    2c | прошло  3.9м · ост.~ 0.4м
  [schools] тайл 151/164 | +6 (Σ9,359) |    1c | прошло  4.0м · ост.~ 0.3м
  [schools] тайл 152/164 | +17 (Σ9,376) |    2c | прошло  4.0м · ост.~ 0.3м
  [schools] тайл 153/164 | +2 (Σ9,378) |    2c | прошло  4.0м · ост.~ 0.3м
  [schools] тайл 154/164 | +1 (Σ9,379) |    2c | прошло  4.0м · ост.~ 0.3м
  [schools] тайл 155/164 | +0 (Σ9,379) |    1c | прошло  4.0м · ост.~ 0.2м
  [schools] тайл 156/164 | +53 (Σ9,432) |    2c | прошло  4.1м · ост.~ 0.2м
  [schools] тайл 157/164 | +3 (Σ9,435) |    1c | прошло  4.1м · ост.~ 0.2м
  [schools] тайл 158/164 | +4 (Σ9,439) |    2c | прошло  4.1м · ост.~ 0.2м
  [schools] тайл 159/164 | +4 (Σ9,443) |    2c | прошло  4.1м · ост.~ 0.1м
  [schools] тайл 160/164 | +11 (Σ9,454) |    2c | прошло  4.2м · ост.~ 0.1м
  [schools] тайл 161/164 | +20 (Σ9,474) |    2c | прошло  4.2м · ост.~ 0.1м
  [schools] тайл 162/164 | +0 (Σ9,474) |    1c | прошло  4.2м · ост.~ 0.1м
  [schools] тайл 163/164 | +3 (Σ9,477) |    1c | прошло  4.2м · ост.~ 0.0м
  [schools] тайл 164/164 | +2 (Σ9,479) |    1c | прошло  4.3м · ост.~ 0.0м
  [schools] ГОТОВО: 9,266 объектов

**Тяжёлые площадные/линейные слои (тайл 5 км) — дольше.**

In [13]:
layers["green"] = geo.fetch_layer(points, OSM_CACHE_DIR, "green")

[green] сетка ~5 км: 482 тайлов
  [green] скачиваю 482 тайлов из OSM…
  [green] тайл 1/482 | +131 (Σ131) |    2c | прошло  0.0м · ост.~19.0м
  [green] тайл 2/482 | +124 (Σ255) |    2c | прошло  0.1м · ост.~19.0м
  [green] тайл 3/482 | +110 (Σ365) |    3c | прошло  0.1м · ост.~19.7м
  [green] тайл 4/482 | +108 (Σ473) |    3c | прошло  0.2м · ост.~20.3м
  [green] тайл 5/482 | +117 (Σ590) |    2c | прошло  0.2м · ост.~19.6м
  [green] тайл 6/482 | +54 (Σ644) |    2c | прошло  0.2м · ост.~19.3м
  [green] тайл 7/482 | +71 (Σ715) |    2c | прошло  0.3м · ост.~19.1м
  [green] тайл 8/482 | +156 (Σ871) |    3c | прошло  0.3м · ост.~19.2м
  [green] тайл 9/482 | +169 (Σ1,040) |    2c | прошло  0.4м · ост.~19.2м
  [green] тайл 10/482 | +106 (Σ1,146) |    2c | прошло  0.4м · ост.~19.1м
  [green] тайл 11/482 | +111 (Σ1,257) |    2c | прошло  0.4м · ост.~18.9м
  [green] тайл 12/482 | +257 (Σ1,514) |    3c | прошло  0.5м · ост.~19.0м
  [green] тайл 13/482 | +116 (Σ1,630) |    2c | прошло  0.5м · ост.~19.0м
  [green] тайл 14/482 | +114 (Σ1,744) |    2c | прошло  0.6м · ост.~18.8м
  [green] тайл 15/482 | +150 (Σ1,894) |    2c | прошло  0.6м · ост.~18.8м
  [green] тайл 16/482 | +137 (Σ2,031) |    2c | прошло  0.6м · ост.~18.8м
  [green] тайл 17/482 | +42 (Σ2,073) |    2c | прошло  0.7м · ост.~18.7м
  [green] тайл 18/482 | +83 (Σ2,156) |    2c | прошло  0.7м · ост.~18.6м
  [green] тайл 19/482 | +502 (Σ2,658) |    2c | прошло  0.8м · ост.~18.6м
  [green] тайл 20/482 | +84 (Σ2,742) |    2c | прошло  0.8м · ост.~18.5м
  [green] тайл 21/482 | +42 (Σ2,784) |    2c | прошло  0.8м · ост.~18.4м
  [green] тайл 22/482 | +98 (Σ2,882) |    2c | прошло  0.9м · ост.~18.4м
  [green] тайл 23/482 | +572 (Σ3,454) |    3c | прошло  0.9м · ост.~18.4м
  [green] тайл 24/482 | +23 (Σ3,477) |    2c | прошло  1.0м · ост.~18.4м
  [green] тайл 25/482 | +59 (Σ3,536) |    2c | прошло  1.0м · ост.~18.3м
  [green] тайл 26/482 | +110 (Σ3,646) |    2c | прошло  1.0м · ост.~18.3м
  [green] тайл 27/482 | +139 (Σ3,785) |    2c | прошло  1.1м · ост.~18.2м
  [green] тайл 28/482 | +21 (Σ3,806) |    2c | прошло  1.1м · ост.~18.2м
  [green] тайл 29/482 | +49 (Σ3,855) |    2c | прошло  1.2м · ост.~18.1м
  [green] тайл 30/482 | +279 (Σ4,134) |    2c | прошло  1.2м · ост.~18.0м
  [green] тайл 31/482 | +96 (Σ4,230) |    3c | прошло  1.2м · ост.~18.0м
  [green] тайл 32/482 | +128 (Σ4,358) |    3c | прошло  1.3м · ост.~18.0м
  [green] тайл 33/482 | +87 (Σ4,445) |    2c | прошло  1.3м · ост.~18.0м
  [green] тайл 34/482 | +144 (Σ4,589) |    2c | прошло  1.4м · ост.~18.0м
  [green] тайл 35/482 | +61 (Σ4,650) |    2c | прошло  1.4м · ост.~17.9м
  [green] тайл 36/482 | +24 (Σ4,674) |    2c | прошло  1.4м · ост.~17.8м
  [green] тайл 37/482 | +100 (Σ4,774) |    2c | прошло  1.5м · ост.~17.8м
  [green] тайл 38/482 | +174 (Σ4,948) |    3c | прошло  1.5м · ост.~17.8м
  [green] тайл 39/482 | +77 (Σ5,025) |    3c | прошло  1.6м · ост.~17.8м
  [green] тайл 40/482 | +147 (Σ5,172) |    4c | прошло  1.6м · ост.~18.1м
  [green] тайл 41/482 | +554 (Σ5,726) |    3c | прошло  1.7м · ост.~18.2м
  [green] тайл 42/482 | +78 (Σ5,804) |    7c | прошло  1.8м · ост.~18.8м
  [green] тайл 43/482 | +125 (Σ5,929) |   17c | прошло  2.1м · ост.~21.2м
  [green] тайл 44/482 | +59 (Σ5,988) |    3c | прошло  2.1м · ост.~21.2м
  [green] тайл 45/482 | +121 (Σ6,109) |    4c | прошло  2.2м · ост.~21.3м
  [green] тайл 46/482 | +80 (Σ6,189) |    6c | прошло  2.3м · ост.~21.8м
  [green] тайл 47/482 | +37 (Σ6,226) |   32c | прошло  2.8м · ост.~26.2м
  [green] тайл 48/482 | +911 (Σ7,137) |    7c | прошло  3.0м · ост.~26.7м
  [green] тайл 49/482 | +78 (Σ7,215) |    3c | прошло  3.0м · ост.~26.6м
  [green] тайл 50/482 | +96 (Σ7,311) |   89c | прошло  4.5м · ост.~38.8м
  [green] тайл 51/482 | +61 (Σ7,372) |    2c | прошло  4.5м · ост.~38.3м
  [green] тайл 52/482 | +40 (Σ7,412) |    2c | прошло  4.6м · ост.~37.8м
  [green] тайл 53/482 | +48 (Σ7,460) |    2c | прошло  4.6м · ост.~37.3м
  [green] тайл 54/482 | +115 (Σ7,575) |    3c | прошло  4.7м · ост.~36.9м
  [green] тайл 55/482 | +172 (Σ7,747) |    2c | прошло  4.7м · ост.~36.4м
  [green] тайл 56/482 | +94 (Σ7,841) |    3c | прошло  4.7м · ост.~36.0м
  [green] тайл 57/482 | +70 (Σ7,911) |    2c | прошло  4.8м · ост.~35.6м
  [green] тайл 58/482 | +94 (Σ8,005) |    2c | прошло  4.8м · ост.~35.2м
  [green] тайл 59/482 | +128 (Σ8,133) |    2c | прошло  4.9м · ост.~34.8м
  [green] тайл 60/482 | +146 (Σ8,279) |    2c | прошло  4.9м · ост.~34.4м
  [green] тайл 61/482 | +42 (Σ8,321) |    2c | прошло  4.9м · ост.~34.1м
  [green] тайл 62/482 | +37 (Σ8,358) |    2c | прошло  5.0м · ост.~33.7м
  [green] тайл 63/482 | +129 (Σ8,487) |    3c | прошло  5.0м · ост.~33.4м
  [green] тайл 64/482 | +56 (Σ8,543) |    2c | прошло  5.1м · ост.~33.1м
  [green] тайл 65/482 | +151 (Σ8,694) |    3c | прошло  5.1м · ост.~32.8м
  [green] тайл 66/482 | +79 (Σ8,773) |    2c | прошло  5.1м · ост.~32.4м
  [green] тайл 67/482 | +142 (Σ8,915) |    3c | прошло  5.2м · ост.~32.1м
  [green] тайл 68/482 | +43 (Σ8,958) |    2c | прошло  5.2м · ост.~31.8м
  [green] тайл 69/482 | +171 (Σ9,129) |    3c | прошло  5.3м · ост.~31.6м
  [green] тайл 70/482 | +239 (Σ9,368) |    3c | прошло  5.3м · ост.~31.3м
  [green] тайл 71/482 | +150 (Σ9,518) |    3c | прошло  5.4м · ост.~31.1м
  [green] тайл 72/482 | +111 (Σ9,629) |    3c | прошло  5.4м · ост.~30.8м
  [green] тайл 73/482 | +99 (Σ9,728) |    2c | прошло  5.5м · ост.~30.6м
  [green] тайл 74/482 | +89 (Σ9,817) |    2c | прошло  5.5м · ост.~30.3м
  [green] тайл 75/482 | +108 (Σ9,925) |    3c | прошло  5.5м · ост.~30.1м
  [green] тайл 76/482 | +113 (Σ10,038) |    2c | прошло  5.6м · ост.~29.8м
  [green] тайл 77/482 | +165 (Σ10,203) |    2c | прошло  5.6м · ост.~29.6м
  [green] тайл 78/482 | +65 (Σ10,268) |    2c | прошло  5.7м · ост.~29.3м
  [green] тайл 79/482 | +58 (Σ10,326) |    2c | прошло  5.7м · ост.~29.1м
  [green] тайл 80/482 | +174 (Σ10,500) |    2c | прошло  5.7м · ост.~28.8м
  [green] тайл 81/482 | +346 (Σ10,846) |    3c | прошло  5.8м · ост.~28.7м
  [green] тайл 82/482 | +485 (Σ11,331) |    3c | прошло  5.8м · ост.~28.4м
  [green] тайл 83/482 | +138 (Σ11,469) |    3c | прошло  5.9м · ост.~28.2м
  [green] тайл 84/482 | +172 (Σ11,641) |    3c | прошло  5.9м · ост.~28.1м
  [green] тайл 85/482 | +204 (Σ11,845) |    3c | прошло  6.0м · ост.~27.9м
  [green] тайл 86/482 | +245 (Σ12,090) |    5c | прошло  6.1м · ост.~27.9м
  [green] тайл 87/482 | +652 (Σ12,742) |    3c | прошло  6.1м · ост.~27.7м
  [green] тайл 88/482 | +218 (Σ12,960) |    3c | прошло  6.2м · ост.~27.5м
  [green] тайл 89/482 | +104 (Σ13,064) |   89c | прошло  7.6м · ост.~33.7м
  [green] тайл 90/482 | +205 (Σ13,269) |   15c | прошло  7.9м · ост.~34.4м
  [green] тайл 91/482 | +82 (Σ13,351) |   18c | прошло  8.2м · ост.~35.2м
  [green] тайл 92/482 | +141 (Σ13,492) |    2c | прошло  8.2м · ост.~34.9м
  [green] тайл 93/482 | +94 (Σ13,586) |    2c | прошло  8.3м · ост.~34.6м
  [green] тайл 94/482 | +93 (Σ13,679) |    3c | прошло  8.3м · ост.~34.3м
  [green] тайл 95/482 | +13 (Σ13,692) |    2c | прошло  8.4м · ост.~34.0м
  [green] тайл 96/482 | +41 (Σ13,733) |    2c | прошло  8.4м · ост.~33.8м
  [green] тайл 97/482 | +30 (Σ13,763) |    2c | прошло  8.4м · ост.~33.5м
  [green] тайл 98/482 | +9 (Σ13,772) |    2c | прошло  8.5м · ост.~33.2м
  [green] тайл 99/482 | +32 (Σ13,804) |    3c | прошло  8.5м · ост.~32.9м
  [green] тайл 100/482 | +79 (Σ13,883) |    2c | прошло  8.6м · ост.~32.7м
  [green] тайл 101/482 | +133 (Σ14,016) |    3c | прошло  8.6м · ост.~32.4м
  [green] тайл 102/482 | +449 (Σ14,465) |    3c | прошло  8.6м · ост.~32.2м
  [green] тайл 103/482 | +309 (Σ14,774) |    3c | прошло  8.7м · ост.~32.0м
  [green] тайл 104/482 | +252 (Σ15,026) |    4c | прошло  8.8м · ост.~31.9м
  [green] тайл 105/482 | +197 (Σ15,223) |    3c | прошло  8.8м · ост.~31.6м
  [green] тайл 106/482 | +174 (Σ15,397) |   35c | прошло  9.4м · ост.~33.3м
  [green] тайл 107/482 | +501 (Σ15,898) |    3c | прошло  9.4м · ост.~33.1м
  [green] тайл 108/482 | +192 (Σ16,090) |    4c | прошло  9.5м · ост.~32.9м
  [green] тайл 109/482 | +186 (Σ16,276) |    3c | прошло  9.6м · ост.~32.7м
  [green] тайл 110/482 | +742 (Σ17,018) |    3c | прошло  9.6м · ост.~32.5м
  [green] тайл 111/482 | +408 (Σ17,426) |   26c | прошло 10.0м · ост.~33.6м
  [green] тайл 112/482 | +129 (Σ17,555) |    3c | прошло 10.1м · ост.~33.3м
  [green] тайл 113/482 | +127 (Σ17,682) |    2c | прошло 10.1м · ост.~33.1м
  [green] тайл 114/482 | +40 (Σ17,722) |    3c | прошло 10.2м · ост.~32.9м
  [green] тайл 115/482 | +176 (Σ17,898) |    3c | прошло 10.2м · ост.~32.6м
  [green] тайл 116/482 | +23 (Σ17,921) |    3c | прошло 10.3м · ост.~32.4м
  [green] тайл 117/482 | +103 (Σ18,024) |    2c | прошло 10.3м · ост.~32.1м
  [green] тайл 118/482 | +86 (Σ18,110) |    2c | прошло 10.3м · ост.~31.9м
  [green] тайл 119/482 | +91 (Σ18,201) |    2c | прошло 10.4м · ост.~31.7м
  [green] тайл 120/482 | +92 (Σ18,293) |    2c | прошло 10.4м · ост.~31.4м
  [green] тайл 121/482 | +196 (Σ18,489) |    5c | прошло 10.5м · ост.~31.3м
  [green] тайл 122/482 | +54 (Σ18,543) |    2c | прошло 10.5м · ост.~31.1м
  [green] тайл 123/482 | +96 (Σ18,639) |    3c | прошло 10.6м · ост.~30.9м
  [green] тайл 124/482 | +426 (Σ19,065) |    3c | прошло 10.6м · ост.~30.7м
  [green] тайл 125/482 | +330 (Σ19,395) |    2c | прошло 10.7м · ост.~30.5м
  [green] тайл 126/482 | +64 (Σ19,459) |    3c | прошло 10.7м · ост.~30.3м
  [green] тайл 127/482 | +153 (Σ19,612) |    3c | прошло 10.8м · ост.~30.1м
  [green] тайл 128/482 | +309 (Σ19,921) |    3c | прошло 10.8м · ост.~29.9м
  [green] тайл 129/482 | +367 (Σ20,288) |    3c | прошло 10.9м · ост.~29.7м
  [green] тайл 130/482 | +220 (Σ20,508) |    5c | прошло 10.9м · ост.~29.6м
  [green] тайл 131/482 | +190 (Σ20,698) |    3c | прошло 11.0м · ост.~29.4м
  [green] тайл 132/482 | +282 (Σ20,980) |    3c | прошло 11.0м · ост.~29.3м
  [green] тайл 133/482 | +155 (Σ21,135) |    3c | прошло 11.1м · ост.~29.1м
  [green] тайл 134/482 | +50 (Σ21,185) |    2c | прошло 11.1м · ост.~28.9м
  [green] тайл 135/482 | +130 (Σ21,315) |    3c | прошло 11.2м · ост.~28.7м
  [green] тайл 136/482 | +56 (Σ21,371) |    2c | прошло 11.2м · ост.~28.5м
  [green] тайл 137/482 | +97 (Σ21,468) |    3c | прошло 11.3м · ост.~28.3м
  [green] тайл 138/482 | +118 (Σ21,586) |    2c | прошло 11.3м · ост.~28.1м
  [green] тайл 139/482 | +145 (Σ21,731) |    2c | прошло 11.3м · ост.~28.0м
  [green] тайл 140/482 | +186 (Σ21,917) |    2c | прошло 11.4м · ост.~27.8м
  [green] тайл 141/482 | +109 (Σ22,026) |    2c | прошло 11.4м · ост.~27.6м
  [green] тайл 142/482 | +51 (Σ22,077) |    3c | прошло 11.5м · ост.~27.4м
  [green] тайл 143/482 | +112 (Σ22,189) |    3c | прошло 11.5м · ост.~27.3м
  [green] тайл 144/482 | +113 (Σ22,302) |    2c | прошло 11.5м · ост.~27.1м
  [green] тайл 145/482 | +79 (Σ22,381) |    3c | прошло 11.6м · ост.~26.9м
  [green] тайл 146/482 | +448 (Σ22,829) |    3c | прошло 11.6м · ост.~26.8м
  [green] тайл 147/482 | +544 (Σ23,373) |    3c | прошло 11.7м · ост.~26.6м
  [green] тайл 148/482 | +945 (Σ24,318) |    4c | прошло 11.7м · ост.~26.5м
  [green] тайл 149/482 | +323 (Σ24,641) |    3c | прошло 11.8м · ост.~26.4м
  [green] тайл 150/482 | +637 (Σ25,278) |    4c | прошло 11.9м · ост.~26.2м
  [green] тайл 151/482 | +1187 (Σ26,465) |    3c | прошло 11.9м · ост.~26.1м
  [green] тайл 152/482 | +314 (Σ26,779) |    4c | прошло 12.0м · ост.~26.0м
  [green] тайл 153/482 | +339 (Σ27,118) |    3c | прошло 12.0м · ост.~25.9м
  [green] тайл 154/482 | +223 (Σ27,341) |    3c | прошло 12.1м · ост.~25.7м
  [green] тайл 155/482 | +37 (Σ27,378) |    3c | прошло 12.1м · ост.~25.6м
  [green] тайл 156/482 | +123 (Σ27,501) |    2c | прошло 12.2м · ост.~25.4м
  [green] тайл 157/482 | +128 (Σ27,629) |    3c | прошло 12.2м · ост.~25.2м
  [green] тайл 158/482 | +70 (Σ27,699) |    2c | прошло 12.2м · ост.~25.1м
  [green] тайл 159/482 | +161 (Σ27,860) |    3c | прошло 12.3м · ост.~24.9м
  [green] тайл 160/482 | +57 (Σ27,917) |    3c | прошло 12.3м · ост.~24.8м
  [green] тайл 161/482 | +27 (Σ27,944) |    2c | прошло 12.4м · ост.~24.6м
  [green] тайл 162/482 | +62 (Σ28,006) |    2c | прошло 12.4м · ост.~24.5м
  [green] тайл 163/482 | +66 (Σ28,072) |    2c | прошло 12.4м · ост.~24.3м
  [green] тайл 164/482 | +83 (Σ28,155) |    2c | прошло 12.5м · ост.~24.2м
  [green] тайл 165/482 | +103 (Σ28,258) |    3c | прошло 12.5м · ост.~24.1м
  [green] тайл 166/482 | +114 (Σ28,372) |    3c | прошло 12.6м · ост.~23.9м
  [green] тайл 167/482 | +332 (Σ28,704) |    3c | прошло 12.6м · ост.~23.8м
  [green] тайл 168/482 | +217 (Σ28,921) |    3c | прошло 12.7м · ост.~23.7м
  [green] тайл 169/482 | +1101 (Σ30,022) |    3c | прошло 12.7м · ост.~23.6м
  [green] тайл 170/482 | +837 (Σ30,859) |    4c | прошло 12.8м · ост.~23.5м
  [green] тайл 171/482 | +614 (Σ31,473) |    4c | прошло 12.9м · ост.~23.4м
  [green] тайл 172/482 | +980 (Σ32,453) |    5c | прошло 12.9м · ост.~23.3м
  [green] тайл 173/482 | +1351 (Σ33,804) |    4c | прошло 13.0м · ост.~23.2м
  [green] тайл 174/482 | +644 (Σ34,448) |    4c | прошло 13.1м · ост.~23.1м
  [green] тайл 175/482 | +285 (Σ34,733) |    3c | прошло 13.1м · ост.~23.0м
  [green] тайл 176/482 | +221 (Σ34,954) |    3c | прошло 13.2м · ост.~22.9м
  [green] тайл 177/482 | +118 (Σ35,072) |    3c | прошло 13.2м · ост.~22.8м
  [green] тайл 178/482 | +82 (Σ35,154) |    3c | прошло 13.3м · ост.~22.6м
  [green] тайл 179/482 | +101 (Σ35,255) |    2c | прошло 13.3м · ост.~22.5м
  [green] тайл 180/482 | +74 (Σ35,329) |    2c | прошло 13.3м · ост.~22.4м
  [green] тайл 181/482 | +68 (Σ35,397) |    3c | прошло 13.4м · ост.~22.3м
  [green] тайл 182/482 | +49 (Σ35,446) |    2c | прошло 13.4м · ост.~22.1м
  [green] тайл 183/482 | +47 (Σ35,493) |    2c | прошло 13.5м · ост.~22.0м
  [green] тайл 184/482 | +55 (Σ35,548) |   17c | прошло 13.7м · ост.~22.3м
  [green] тайл 185/482 | +76 (Σ35,624) |    2c | прошло 13.8м · ост.~22.1м
  [green] тайл 186/482 | +86 (Σ35,710) |    2c | прошло 13.8м · ост.~22.0м
  [green] тайл 187/482 | +53 (Σ35,763) |    2c | прошло 13.9м · ост.~21.9м
  [green] тайл 188/482 | +138 (Σ35,901) |   10c | прошло 14.0м · ост.~21.9м
  [green] тайл 189/482 | +162 (Σ36,063) |    3c | прошло 14.1м · ост.~21.8м
  [green] тайл 190/482 | +198 (Σ36,261) |    2c | прошло 14.1м · ост.~21.7м
  [green] тайл 191/482 | +114 (Σ36,375) |    3c | прошло 14.2м · ост.~21.6м
  [green] тайл 192/482 | +189 (Σ36,564) |    3c | прошло 14.2м · ост.~21.5м
  [green] тайл 193/482 | +528 (Σ37,092) |    4c | прошло 14.3м · ост.~21.4м
  [green] тайл 194/482 | +662 (Σ37,754) |    4c | прошло 14.3м · ост.~21.3м
  [green] тайл 195/482 | +805 (Σ38,559) |    3c | прошло 14.4м · ост.~21.2м
  [green] тайл 196/482 | +2217 (Σ40,776) |    5c | прошло 14.5м · ост.~21.1м
  [green] тайл 197/482 | +1278 (Σ42,054) |    4c | прошло 14.5м · ост.~21.0м
  [green] тайл 198/482 | +2676 (Σ44,730) |    7c | прошло 14.7м · ост.~21.0м
  [green] тайл 199/482 | +554 (Σ45,284) |    4c | прошло 14.7м · ост.~20.9м
  [green] тайл 200/482 | +618 (Σ45,902) |    5c | прошло 14.8м · ост.~20.9м
  [green] тайл 201/482 | +673 (Σ46,575) |    3c | прошло 14.8м · ост.~20.8м
  [green] тайл 202/482 | +243 (Σ46,818) |    3c | прошло 14.9м · ост.~20.6м
  [green] тайл 203/482 | +156 (Σ46,974) |    3c | прошло 14.9м · ост.~20.5м
  [green] тайл 204/482 | +152 (Σ47,126) |    3c | прошло 15.0м · ост.~20.4м
  [green] тайл 205/482 | +86 (Σ47,212) |    3c | прошло 15.0м · ост.~20.3м
  [green] тайл 206/482 | +148 (Σ47,360) |    2c | прошло 15.1м · ост.~20.2м
  [green] тайл 207/482 | +143 (Σ47,503) |    2c | прошло 15.1м · ост.~20.1м
  [green] тайл 208/482 | +184 (Σ47,687) |    2c | прошло 15.1м · ост.~20.0м
  [green] тайл 209/482 | +268 (Σ47,955) |    3c | прошло 15.2м · ост.~19.8м
  [green] тайл 210/482 | +103 (Σ48,058) |    2c | прошло 15.2м · ост.~19.7м
  [green] тайл 211/482 | +98 (Σ48,156) |    2c | прошло 15.3м · ост.~19.6м
  [green] тайл 212/482 | +206 (Σ48,362) |    2c | прошло 15.3м · ост.~19.5м
  [green] тайл 213/482 | +61 (Σ48,423) |    2c | прошло 15.3м · ост.~19.4м
  [green] тайл 214/482 | +10 (Σ48,433) |    2c | прошло 15.4м · ост.~19.3м
  [green] тайл 215/482 | +34 (Σ48,467) |    2c | прошло 15.4м · ост.~19.1м
  [green] тайл 216/482 | +96 (Σ48,563) |    2c | прошло 15.5м · ост.~19.0м
  [green] тайл 217/482 | +82 (Σ48,645) |    2c | прошло 15.5м · ост.~18.9м
  [green] тайл 218/482 | +107 (Σ48,752) |    4c | прошло 15.6м · ост.~18.9м
  [green] тайл 219/482 | +126 (Σ48,878) |  116c | прошло 17.5м · ост.~21.0м
  [green] тайл 220/482 | +185 (Σ49,063) |   81c | прошло 18.8м · ост.~22.4м
  [green] тайл 221/482 | +345 (Σ49,408) |   10c | прошло 19.0м · ост.~22.4м
  [green] тайл 222/482 | +385 (Σ49,793) |    3c | прошло 19.0м · ост.~22.3м
  [green] тайл 223/482 | +635 (Σ50,428) |   22c | прошло 19.4м · ост.~22.6м
  [green] тайл 224/482 | +1632 (Σ52,060) |    4c | прошло 19.5м · ост.~22.5м
  [green] тайл 225/482 | +3329 (Σ55,389) |    5c | прошло 19.6м · ост.~22.4м
  [green] тайл 226/482 | +2152 (Σ57,541) |    5c | прошло 19.7м · ост.~22.3м
  [green] тайл 227/482 | +3203 (Σ60,744) |    5c | прошло 19.7м · ост.~22.2м
  [green] тайл 228/482 | +457 (Σ61,201) |    4c | прошло 19.8м · ост.~22.1м
  [green] тайл 229/482 | +283 (Σ61,484) |    3c | прошло 19.8м · ост.~21.9м
  [green] тайл 230/482 | +62 (Σ61,546) |    3c | прошло 19.9м · ост.~21.8м
  [green] тайл 231/482 | +88 (Σ61,634) |    3c | прошло 19.9м · ост.~21.7м
  [green] тайл 232/482 | +250 (Σ61,884) |    3c | прошло 20.0м · ост.~21.5м
  [green] тайл 233/482 | +62 (Σ61,946) |    2c | прошло 20.0м · ост.~21.4м
  [green] тайл 234/482 | +27 (Σ61,973) |    3c | прошло 20.1м · ост.~21.3м
  [green] тайл 235/482 | +84 (Σ62,057) |    3c | прошло 20.1м · ост.~21.1м
  [green] тайл 236/482 | +100 (Σ62,157) |    2c | прошло 20.1м · ост.~21.0м
  [green] тайл 237/482 | +96 (Σ62,253) |    2c | прошло 20.2м · ост.~20.9м
  [green] тайл 238/482 | +130 (Σ62,383) |    2c | прошло 20.2м · ост.~20.7м
  [green] тайл 239/482 | +59 (Σ62,442) |    2c | прошло 20.3м · ост.~20.6м
  [green] тайл 240/482 | +79 (Σ62,521) |    2c | прошло 20.3м · ост.~20.5м
  [green] тайл 241/482 | +89 (Σ62,610) |    2c | прошло 20.3м · ост.~20.3м
  [green] тайл 242/482 | +7 (Σ62,617) |    2c | прошло 20.4м · ост.~20.2м
  [green] тайл 243/482 | +22 (Σ62,639) |    2c | прошло 20.4м · ост.~20.1м
  [green] тайл 244/482 | +50 (Σ62,689) |    2c | прошло 20.4м · ост.~19.9м
  [green] тайл 245/482 | +27 (Σ62,716) |    2c | прошло 20.5м · ост.~19.8м
  [green] тайл 246/482 | +31 (Σ62,747) |    2c | прошло 20.5м · ост.~19.7м
  [green] тайл 247/482 | +65 (Σ62,812) |    3c | прошло 20.6м · ост.~19.6м
  [green] тайл 248/482 | +129 (Σ62,941) |    3c | прошло 20.6м · ост.~19.5м
  [green] тайл 249/482 | +814 (Σ63,755) |    4c | прошло 20.7м · ост.~19.4м
  [green] тайл 250/482 | +1342 (Σ65,097) |    4c | прошло 20.7м · ост.~19.2м
  [green] тайл 251/482 | +714 (Σ65,811) |    3c | прошло 20.8м · ост.~19.1м
  [green] тайл 252/482 | +540 (Σ66,351) |    6c | прошло 20.9м · ост.~19.1м
  [green] тайл 253/482 | +1436 (Σ67,787) |    5c | прошло 21.0м · ост.~19.0м
  [green] тайл 254/482 | +1841 (Σ69,628) |    6c | прошло 21.1м · ост.~18.9м
  [green] тайл 255/482 | +1754 (Σ71,382) |    5c | прошло 21.2м · ост.~18.8м
  [green] тайл 256/482 | +656 (Σ72,038) |    4c | прошло 21.2м · ост.~18.7м
  [green] тайл 257/482 | +72 (Σ72,110) |    3c | прошло 21.3м · ост.~18.6м
  [green] тайл 258/482 | +80 (Σ72,190) |    3c | прошло 21.3м · ост.~18.5м
  [green] тайл 259/482 | +58 (Σ72,248) |    3c | прошло 21.4м · ост.~18.4м
  [green] тайл 260/482 | +52 (Σ72,300) |    2c | прошло 21.4м · ост.~18.3м
  [green] тайл 261/482 | +18 (Σ72,318) |    2c | прошло 21.4м · ост.~18.2м
  [green] тайл 262/482 | +91 (Σ72,409) |    2c | прошло 21.5м · ост.~18.0м
  [green] тайл 263/482 | +15 (Σ72,424) |    2c | прошло 21.5м · ост.~17.9м
  [green] тайл 264/482 | +119 (Σ72,543) |    2c | прошло 21.6м · ост.~17.8м
  [green] тайл 265/482 | +109 (Σ72,652) |    2c | прошло 21.6м · ост.~17.7м
  [green] тайл 266/482 | +88 (Σ72,740) |    3c | прошло 21.7м · ост.~17.6м

In [14]:
layers["water"] = geo.fetch_layer(points, OSM_CACHE_DIR, "water")

[water] сетка ~5 км: 482 тайлов
  [water] скачиваю 482 тайлов из OSM…
  [water] тайл 1/482 | +95 (Σ95) |    2c | прошло  0.0м · ост.~15.5м
  [water] тайл 2/482 | +65 (Σ160) |    2c | прошло  0.1м · ост.~14.8м
  [water] тайл 3/482 | +78 (Σ238) |    2c | прошло  0.1м · ост.~14.9м
  [water] тайл 4/482 | +78 (Σ316) |    2c | прошло  0.1м · ост.~15.1м
  [water] тайл 5/482 | +41 (Σ357) |    2c | прошло  0.2м · ост.~14.8м
  [water] тайл 6/482 | +36 (Σ393) |    2c | прошло  0.2м · ост.~14.6м
  [water] тайл 7/482 | +35 (Σ428) |    2c | прошло  0.2м · ост.~14.4м
  [water] тайл 8/482 | +60 (Σ488) |    2c | прошло  0.2м · ост.~14.3м
  [water] тайл 9/482 | +70 (Σ558) |    2c | прошло  0.3м · ост.~14.7м
  [water] тайл 10/482 | +47 (Σ605) |    2c | прошло  0.3м · ост.~14.9м
  [water] тайл 11/482 | +46 (Σ651) |    2c | прошло  0.3м · ост.~14.7м
  [water] тайл 12/482 | +58 (Σ709) |    2c | прошло  0.4м · ост.~14.8м
  [water] тайл 13/482 | +38 (Σ747) |    2c | прошло  0.4м · ост.~14.6м
  [water] тайл 14/482 | +80 (Σ827) |    2c | прошло  0.4м · ост.~14.7м
  [water] тайл 15/482 | +30 (Σ857) |    2c | прошло  0.5м · ост.~14.8м
  [water] тайл 16/482 | +41 (Σ898) |    2c | прошло  0.5м · ост.~14.8м
  [water] тайл 17/482 | +40 (Σ938) |    2c | прошло  0.5м · ост.~14.7м
  [water] тайл 18/482 | +36 (Σ974) |    2c | прошло  0.6м · ост.~14.6м
  [water] тайл 19/482 | +90 (Σ1,064) |    2c | прошло  0.6м · ост.~14.6м
  [water] тайл 20/482 | +79 (Σ1,143) |    2c | прошло  0.6м · ост.~14.5м
  [water] тайл 21/482 | +43 (Σ1,186) |    2c | прошло  0.7м · ост.~14.4м
  [water] тайл 22/482 | +45 (Σ1,231) |    2c | прошло  0.7м · ост.~14.4м
  [water] тайл 23/482 | +92 (Σ1,323) |    2c | прошло  0.7м · ост.~14.3м
  [water] тайл 24/482 | +28 (Σ1,351) |    2c | прошло  0.7м · ост.~14.2м
  [water] тайл 25/482 | +53 (Σ1,404) |    2c | прошло  0.8м · ост.~14.2м
  [water] тайл 26/482 | +104 (Σ1,508) |    2c | прошло  0.8м · ост.~14.1м
  [water] тайл 27/482 | +108 (Σ1,616) |    2c | прошло  0.8м · ост.~14.1м
  [water] тайл 28/482 | +6 (Σ1,622) |    2c | прошло  0.9м · ост.~14.1м
  [water] тайл 29/482 | +29 (Σ1,651) |    2c | прошло  0.9м · ост.~14.1м
  [water] тайл 30/482 | +84 (Σ1,735) |    2c | прошло  0.9м · ост.~14.0м
  [water] тайл 31/482 | +44 (Σ1,779) |    2c | прошло  1.0м · ост.~14.0м
  [water] тайл 32/482 | +47 (Σ1,826) |    2c | прошло  1.0м · ост.~14.0м
  [water] тайл 33/482 | +70 (Σ1,896) |    2c | прошло  1.0м · ост.~14.0м
  [water] тайл 34/482 | +114 (Σ2,010) |    2c | прошло  1.1м · ост.~14.0м
  [water] тайл 35/482 | +43 (Σ2,053) |    2c | прошло  1.1м · ост.~14.0м
  [water] тайл 36/482 | +34 (Σ2,087) |    2c | прошло  1.1м · ост.~13.9м
  [water] тайл 37/482 | +62 (Σ2,149) |    2c | прошло  1.2м · ост.~13.9м
  [water] тайл 38/482 | +56 (Σ2,205) |    2c | прошло  1.2м · ост.~14.0м
  [water] тайл 39/482 | +32 (Σ2,237) |    2c | прошло  1.2м · ост.~13.9м
  [water] тайл 40/482 | +66 (Σ2,303) |    2c | прошло  1.3м · ост.~13.9м
  [water] тайл 41/482 | +69 (Σ2,372) |    2c | прошло  1.3м · ост.~13.9м
  [water] тайл 42/482 | +36 (Σ2,408) |    2c | прошло  1.3м · ост.~13.9м
  [water] тайл 43/482 | +37 (Σ2,445) |    2c | прошло  1.4м · ост.~13.8м
  [water] тайл 44/482 | +32 (Σ2,477) |    2c | прошло  1.4м · ост.~13.7м
  [water] тайл 45/482 | +57 (Σ2,534) |    2c | прошло  1.4м · ост.~13.7м
  [water] тайл 46/482 | +92 (Σ2,626) |    2c | прошло  1.4м · ост.~13.7м
  [water] тайл 47/482 | +85 (Σ2,711) |    2c | прошло  1.5м · ост.~13.7м
  [water] тайл 48/482 | +74 (Σ2,785) |    2c | прошло  1.5м · ост.~13.7м
  [water] тайл 49/482 | +43 (Σ2,828) |    2c | прошло  1.5м · ост.~13.6м
  [water] тайл 50/482 | +68 (Σ2,896) |    2c | прошло  1.6м · ост.~13.6м
  [water] тайл 51/482 | +61 (Σ2,957) |    2c | прошло  1.6м · ост.~13.5м
  [water] тайл 52/482 | +37 (Σ2,994) |    2c | прошло  1.6м · ост.~13.5м
  [water] тайл 53/482 | +40 (Σ3,034) |    2c | прошло  1.7м · ост.~13.5м
  [water] тайл 54/482 | +69 (Σ3,103) |    2c | прошло  1.7м · ост.~13.5м
  [water] тайл 55/482 | +105 (Σ3,208) |    2c | прошло  1.7м · ост.~13.4м
  [water] тайл 56/482 | +53 (Σ3,261) |    2c | прошло  1.8м · ост.~13.4м
  [water] тайл 57/482 | +61 (Σ3,322) |    2c | прошло  1.8м · ост.~13.4м
  [water] тайл 58/482 | +56 (Σ3,378) |    2c | прошло  1.8м · ост.~13.3м
  [water] тайл 59/482 | +116 (Σ3,494) |    2c | прошло  1.9м · ост.~13.4м
  [water] тайл 60/482 | +118 (Σ3,612) |    2c | прошло  1.9м · ост.~13.3м
  [water] тайл 61/482 | +92 (Σ3,704) |    2c | прошло  1.9м · ост.~13.3м
  [water] тайл 62/482 | +38 (Σ3,742) |    2c | прошло  2.0м · ост.~13.3м
  [water] тайл 63/482 | +203 (Σ3,945) |    2c | прошло  2.0м · ост.~13.2м
  [water] тайл 64/482 | +38 (Σ3,983) |    2c | прошло  2.0м · ост.~13.2м
  [water] тайл 65/482 | +61 (Σ4,044) |    2c | прошло  2.0м · ост.~13.2м
  [water] тайл 66/482 | +30 (Σ4,074) |    2c | прошло  2.1м · ост.~13.1м
  [water] тайл 67/482 | +37 (Σ4,111) |    2c | прошло  2.1м · ост.~13.1м
  [water] тайл 68/482 | +44 (Σ4,155) |    2c | прошло  2.1м · ост.~13.1м
  [water] тайл 69/482 | +154 (Σ4,309) |    2c | прошло  2.2м · ост.~13.1м
  [water] тайл 70/482 | +104 (Σ4,413) |    2c | прошло  2.2м · ост.~13.0м
  [water] тайл 71/482 | +87 (Σ4,500) |    2c | прошло  2.2м · ост.~13.0м
  [water] тайл 72/482 | +68 (Σ4,568) |    2c | прошло  2.3м · ост.~13.0м
  [water] тайл 73/482 | +16 (Σ4,584) |    2c | прошло  2.3м · ост.~12.9м
  [water] тайл 74/482 | +21 (Σ4,605) |    2c | прошло  2.3м · ост.~12.9м
  [water] тайл 75/482 | +97 (Σ4,702) |    2c | прошло  2.4м · ост.~12.9м
  [water] тайл 76/482 | +99 (Σ4,801) |    2c | прошло  2.4м · ост.~12.8м
  [water] тайл 77/482 | +67 (Σ4,868) |    2c | прошло  2.4м · ост.~12.8м
  [water] тайл 78/482 | +112 (Σ4,980) |    2c | прошло  2.5м · ост.~12.8м
  [water] тайл 79/482 | +51 (Σ5,031) |    2c | прошло  2.5м · ост.~12.7м
  [water] тайл 80/482 | +276 (Σ5,307) |    2c | прошло  2.5м · ост.~12.7м
  [water] тайл 81/482 | +171 (Σ5,478) |    2c | прошло  2.6м · ост.~12.7м
  [water] тайл 82/482 | +95 (Σ5,573) |    2c | прошло  2.6м · ост.~12.6м
  [water] тайл 83/482 | +115 (Σ5,688) |    2c | прошло  2.6м · ост.~12.6м
  [water] тайл 84/482 | +87 (Σ5,775) |    2c | прошло  2.7м · ост.~12.6м
  [water] тайл 85/482 | +65 (Σ5,840) |    2c | прошло  2.7м · ост.~12.6м
  [water] тайл 86/482 | +82 (Σ5,922) |    2c | прошло  2.7м · ост.~12.6м
  [water] тайл 87/482 | +90 (Σ6,012) |    2c | прошло  2.8м · ост.~12.6м
  [water] тайл 88/482 | +137 (Σ6,149) |    2c | прошло  2.8м · ост.~12.5м
  [water] тайл 89/482 | +48 (Σ6,197) |    2c | прошло  2.8м · ост.~12.5м
  [water] тайл 90/482 | +59 (Σ6,256) |    2c | прошло  2.9м · ост.~12.4м
  [water] тайл 91/482 | +44 (Σ6,300) |    2c | прошло  2.9м · ост.~12.4м
  [water] тайл 92/482 | +60 (Σ6,360) |    2c | прошло  2.9м · ост.~12.4м
  [water] тайл 93/482 | +90 (Σ6,450) |    2c | прошло  3.0м · ост.~12.4м
  [water] тайл 94/482 | +33 (Σ6,483) |    2c | прошло  3.0м · ост.~12.3м
  [water] тайл 95/482 | +43 (Σ6,526) |    2c | прошло  3.0м · ост.~12.3м
  [water] тайл 96/482 | +16 (Σ6,542) |    2c | прошло  3.1м · ост.~12.3м
  [water] тайл 97/482 | +13 (Σ6,555) |    2c | прошло  3.1м · ост.~12.3м
  [water] тайл 98/482 | +19 (Σ6,574) |    2c | прошло  3.1м · ост.~12.3м
  [water] тайл 99/482 | +62 (Σ6,636) |    2c | прошло  3.2м · ост.~12.2м
  [water] тайл 100/482 | +134 (Σ6,770) |    2c | прошло  3.2м · ост.~12.2м
  [water] тайл 101/482 | +167 (Σ6,937) |    2c | прошло  3.2м · ост.~12.2м
  [water] тайл 102/482 | +126 (Σ7,063) |    2c | прошло  3.3м · ост.~12.1м
  [water] тайл 103/482 | +146 (Σ7,209) |    2c | прошло  3.3м · ост.~12.1м
  [water] тайл 104/482 | +103 (Σ7,312) |    2c | прошло  3.3м · ост.~12.1м
  [water] тайл 105/482 | +50 (Σ7,362) |    2c | прошло  3.4м · ост.~12.1м
  [water] тайл 106/482 | +74 (Σ7,436) |    2c | прошло  3.4м · ост.~12.0м
  [water] тайл 107/482 | +103 (Σ7,539) |    2c | прошло  3.4м · ост.~12.0м
  [water] тайл 108/482 | +74 (Σ7,613) |    2c | прошло  3.5м · ост.~12.0м
  [water] тайл 109/482 | +83 (Σ7,696) |    2c | прошло  3.5м · ост.~12.0м
  [water] тайл 110/482 | +112 (Σ7,808) |    2c | прошло  3.5м · ост.~11.9м
  [water] тайл 111/482 | +59 (Σ7,867) |    2c | прошло  3.6м · ост.~11.9м
  [water] тайл 112/482 | +100 (Σ7,967) |    2c | прошло  3.6м · ост.~11.9м
  [water] тайл 113/482 | +89 (Σ8,056) |    2c | прошло  3.6м · ост.~11.8м
  [water] тайл 114/482 | +103 (Σ8,159) |    2c | прошло  3.7м · ост.~11.8м
  [water] тайл 115/482 | +146 (Σ8,305) |    2c | прошло  3.7м · ост.~11.8м
  [water] тайл 116/482 | +68 (Σ8,373) |    2c | прошло  3.7м · ост.~11.7м
  [water] тайл 117/482 | +100 (Σ8,473) |    2c | прошло  3.8м · ост.~11.7м
  [water] тайл 118/482 | +26 (Σ8,499) |    2c | прошло  3.8м · ост.~11.7м
  [water] тайл 119/482 | +39 (Σ8,538) |    2c | прошло  3.8м · ост.~11.6м
  [water] тайл 120/482 | +59 (Σ8,597) |    2c | прошло  3.8м · ост.~11.6м
  [water] тайл 121/482 | +88 (Σ8,685) |    2c | прошло  3.9м · ост.~11.5м
  [water] тайл 122/482 | +82 (Σ8,767) |    2c | прошло  3.9м · ост.~11.5м
  [water] тайл 123/482 | +73 (Σ8,840) |    2c | прошло  3.9м · ост.~11.5м
  [water] тайл 124/482 | +77 (Σ8,917) |    2c | прошло  4.0м · ост.~11.4м
  [water] тайл 125/482 | +110 (Σ9,027) |    2c | прошло  4.0м · ост.~11.4м
  [water] тайл 126/482 | +114 (Σ9,141) |    2c | прошло  4.0м · ост.~11.4м
  [water] тайл 127/482 | +59 (Σ9,200) |    2c | прошло  4.1м · ост.~11.3м
  [water] тайл 128/482 | +103 (Σ9,303) |    2c | прошло  4.1м · ост.~11.3м
  [water] тайл 129/482 | +103 (Σ9,406) |    2c | прошло  4.1м · ост.~11.3м
  [water] тайл 130/482 | +134 (Σ9,540) |    2c | прошло  4.2м · ост.~11.2м
  [water] тайл 131/482 | +86 (Σ9,626) |    2c | прошло  4.2м · ост.~11.2м
  [water] тайл 132/482 | +68 (Σ9,694) |    2c | прошло  4.2м · ост.~11.2м
  [water] тайл 133/482 | +68 (Σ9,762) |    2c | прошло  4.2м · ост.~11.1м
  [water] тайл 134/482 | +32 (Σ9,794) |    2c | прошло  4.3м · ост.~11.1м
  [water] тайл 135/482 | +60 (Σ9,854) |    2c | прошло  4.3м · ост.~11.1м
  [water] тайл 136/482 | +152 (Σ10,006) |    2c | прошло  4.3м · ост.~11.0м
  [water] тайл 137/482 | +172 (Σ10,178) |    2c | прошло  4.4м · ост.~11.0м
  [water] тайл 138/482 | +198 (Σ10,376) |    2c | прошло  4.4м · ост.~11.0м
  [water] тайл 139/482 | +118 (Σ10,494) |    2c | прошло  4.4м · ост.~11.0м
  [water] тайл 140/482 | +63 (Σ10,557) |    2c | прошло  4.5м · ост.~10.9м
  [water] тайл 141/482 | +38 (Σ10,595) |    2c | прошло  4.5м · ост.~10.9м
  [water] тайл 142/482 | +47 (Σ10,642) |    2c | прошло  4.5м · ост.~10.9м
  [water] тайл 143/482 | +51 (Σ10,693) |    2c | прошло  4.6м · ост.~10.8м
  [water] тайл 144/482 | +40 (Σ10,733) |    2c | прошло  4.6м · ост.~10.8м
  [water] тайл 145/482 | +111 (Σ10,844) |    2c | прошло  4.6м · ост.~10.8м
  [water] тайл 146/482 | +66 (Σ10,910) |    2c | прошло  4.7м · ост.~10.7м
  [water] тайл 147/482 | +140 (Σ11,050) |    2c | прошло  4.7м · ост.~10.7м
  [water] тайл 148/482 | +131 (Σ11,181) |    2c | прошло  4.7м · ост.~10.7м
  [water] тайл 149/482 | +99 (Σ11,280) |    2c | прошло  4.8м · ост.~10.7м
  [water] тайл 150/482 | +135 (Σ11,415) |    2c | прошло  4.8м · ост.~10.7м
  [water] тайл 151/482 | +173 (Σ11,588) |    3c | прошло  4.9м · ост.~10.6м
  [water] тайл 152/482 | +96 (Σ11,684) |    2c | прошло  4.9м · ост.~10.6м
  [water] тайл 153/482 | +174 (Σ11,858) |    2c | прошло  4.9м · ост.~10.6м
  [water] тайл 154/482 | +113 (Σ11,971) |    2c | прошло  5.0м · ост.~10.6м
  [water] тайл 155/482 | +31 (Σ12,002) |    2c | прошло  5.0м · ост.~10.5м
  [water] тайл 156/482 | +45 (Σ12,047) |    2c | прошло  5.0м · ост.~10.5м
  [water] тайл 157/482 | +71 (Σ12,118) |    2c | прошло  5.1м · ост.~10.5м
  [water] тайл 158/482 | +77 (Σ12,195) |    2c | прошло  5.1м · ост.~10.4м
  [water] тайл 159/482 | +45 (Σ12,240) |    2c | прошло  5.1м · ост.~10.4м
  [water] тайл 160/482 | +27 (Σ12,267) |    2c | прошло  5.1м · ост.~10.4м
  [water] тайл 161/482 | +46 (Σ12,313) |    2c | прошло  5.2м · ост.~10.3м
  [water] тайл 162/482 | +58 (Σ12,371) |    2c | прошло  5.2м · ост.~10.3м
  [water] тайл 163/482 | +51 (Σ12,422) |    2c | прошло  5.2м · ост.~10.3м
  [water] тайл 164/482 | +39 (Σ12,461) |    2c | прошло  5.3м · ост.~10.2м
  [water] тайл 165/482 | +65 (Σ12,526) |    2c | прошло  5.3м · ост.~10.2м
  [water] тайл 166/482 | +59 (Σ12,585) |    2c | прошло  5.3м · ост.~10.2м
  [water] тайл 167/482 | +128 (Σ12,713) |    2c | прошло  5.4м · ост.~10.2м
  [water] тайл 168/482 | +144 (Σ12,857) |    2c | прошло  5.4м · ост.~10.1м
  [water] тайл 169/482 | +135 (Σ12,992) |    2c | прошло  5.5м · ост.~10.1м
  [water] тайл 170/482 | +62 (Σ13,054) |    2c | прошло  5.5м · ост.~10.1м
  [water] тайл 171/482 | +102 (Σ13,156) |    2c | прошло  5.5м · ост.~10.1м
  [water] тайл 172/482 | +66 (Σ13,222) |    3c | прошло  5.6м · ост.~10.1м
  [water] тайл 173/482 | +83 (Σ13,305) |    3c | прошло  5.6м · ост.~10.1м
  [water] тайл 174/482 | +75 (Σ13,380) |    2c | прошло  5.7м · ост.~10.0м
  [water] тайл 175/482 | +109 (Σ13,489) |    2c | прошло  5.7м · ост.~10.0м
  [water] тайл 176/482 | +57 (Σ13,546) |    2c | прошло  5.7м · ост.~10.0м
  [water] тайл 177/482 | +50 (Σ13,596) |    2c | прошло  5.8м · ост.~ 9.9м
  [water] тайл 178/482 | +62 (Σ13,658) |    2c | прошло  5.8м · ост.~ 9.9м
  [water] тайл 179/482 | +62 (Σ13,720) |    2c | прошло  5.8м · ост.~ 9.9м
  [water] тайл 180/482 | +31 (Σ13,751) |    2c | прошло  5.9м · ост.~ 9.8м
  [water] тайл 181/482 | +26 (Σ13,777) |    2c | прошло  5.9м · ост.~ 9.8м
  [water] тайл 182/482 | +45 (Σ13,822) |    2c | прошло  5.9м · ост.~ 9.8м
  [water] тайл 183/482 | +33 (Σ13,855) |    2c | прошло  5.9м · ост.~ 9.7м
  [water] тайл 184/482 | +260 (Σ14,115) |    2c | прошло  6.0м · ост.~ 9.7м
  [water] тайл 185/482 | +70 (Σ14,185) |    2c | прошло  6.0м · ост.~ 9.6м
  [water] тайл 186/482 | +119 (Σ14,304) |    2c | прошло  6.0м · ост.~ 9.6м
  [water] тайл 187/482 | +59 (Σ14,363) |    2c | прошло  6.1м · ост.~ 9.6м
  [water] тайл 188/482 | +68 (Σ14,431) |    2c | прошло  6.1м · ост.~ 9.5м
  [water] тайл 189/482 | +130 (Σ14,561) |    2c | прошло  6.1м · ост.~ 9.5м
  [water] тайл 190/482 | +61 (Σ14,622) |    2c | прошло  6.2м · ост.~ 9.5м
  [water] тайл 191/482 | +93 (Σ14,715) |    2c | прошло  6.2м · ост.~ 9.4м
  [water] тайл 192/482 | +110 (Σ14,825) |    2c | прошло  6.2м · ост.~ 9.4м
  [water] тайл 193/482 | +226 (Σ15,051) |    2c | прошло  6.3м · ост.~ 9.4м
  [water] тайл 194/482 | +220 (Σ15,271) |    2c | прошло  6.3м · ост.~ 9.4м
  [water] тайл 195/482 | +85 (Σ15,356) |    2c | прошло  6.3м · ост.~ 9.3м
  [water] тайл 196/482 | +87 (Σ15,443) |    3c | прошло  6.4м · ост.~ 9.3м
  [water] тайл 197/482 | +65 (Σ15,508) |    3c | прошло  6.4м · ост.~ 9.3м
  [water] тайл 198/482 | +86 (Σ15,594) |    3c | прошло  6.5м · ост.~ 9.3м
  [water] тайл 199/482 | +103 (Σ15,697) |    2c | прошло  6.5м · ост.~ 9.3м
  [water] тайл 200/482 | +142 (Σ15,839) |    2c | прошло  6.6м · ост.~ 9.3м
  [water] тайл 201/482 | +85 (Σ15,924) |    2c | прошло  6.6м · ост.~ 9.2м
  [water] тайл 202/482 | +147 (Σ16,071) |    2c | прошло  6.6м · ост.~ 9.2м
  [water] тайл 203/482 | +84 (Σ16,155) |    2c | прошло  6.7м · ост.~ 9.2м
  [water] тайл 204/482 | +92 (Σ16,247) |    2c | прошло  6.7м · ост.~ 9.1м
  [water] тайл 205/482 | +38 (Σ16,285) |    2c | прошло  6.7м · ост.~ 9.1м
  [water] тайл 206/482 | +107 (Σ16,392) |    2c | прошло  6.8м · ост.~ 9.1м
  [water] тайл 207/482 | +100 (Σ16,492) |    2c | прошло  6.8м · ост.~ 9.0м
  [water] тайл 208/482 | +88 (Σ16,580) |    2c | прошло  6.8м · ост.~ 9.0м
  [water] тайл 209/482 | +102 (Σ16,682) |    2c | прошло  6.9м · ост.~ 8.9м
  [water] тайл 210/482 | +133 (Σ16,815) |    2c | прошло  6.9м · ост.~ 8.9м
  [water] тайл 211/482 | +124 (Σ16,939) |    3c | прошло  6.9м · ост.~ 8.9м
  [water] тайл 212/482 | +85 (Σ17,024) |    2c | прошло  7.0м · ост.~ 8.9м
  [water] тайл 213/482 | +19 (Σ17,043) |    2c | прошло  7.0м · ост.~ 8.8м
  [water] тайл 214/482 | +8 (Σ17,051) |    2c | прошло  7.0м · ост.~ 8.8м
  [water] тайл 215/482 | +36 (Σ17,087) |    2c | прошло  7.0м · ост.~ 8.8м
  [water] тайл 216/482 | +43 (Σ17,130) |    2c | прошло  7.1м · ост.~ 8.7м
  [water] тайл 217/482 | +55 (Σ17,185) |    2c | прошло  7.1м · ост.~ 8.7м
  [water] тайл 218/482 | +52 (Σ17,237) |    2c | прошло  7.1м · ост.~ 8.6м
  [water] тайл 219/482 | +81 (Σ17,318) |    2c | прошло  7.2м · ост.~ 8.6м
  [water] тайл 220/482 | +124 (Σ17,442) |    2c | прошло  7.2м · ост.~ 8.6м
  [water] тайл 221/482 | +133 (Σ17,575) |    2c | прошло  7.2м · ост.~ 8.5м
  [water] тайл 222/482 | +130 (Σ17,705) |    2c | прошло  7.3м · ост.~ 8.5м
  [water] тайл 223/482 | +91 (Σ17,796) |    2c | прошло  7.3м · ост.~ 8.5м
  [water] тайл 224/482 | +73 (Σ17,869) |    3c | прошло  7.4м · ост.~ 8.5м
  [water] тайл 225/482 | +98 (Σ17,967) |    3c | прошло  7.4м · ост.~ 8.5м
  [water] тайл 226/482 | +71 (Σ18,038) |    3c | прошло  7.5м · ост.~ 8.4м
  [water] тайл 227/482 | +238 (Σ18,276) |    2c | прошло  7.5м · ост.~ 8.4м
  [water] тайл 228/482 | +79 (Σ18,355) |    2c | прошло  7.5м · ост.~ 8.4м
  [water] тайл 229/482 | +59 (Σ18,414) |    2c | прошло  7.6м · ост.~ 8.4м
  [water] тайл 230/482 | +55 (Σ18,469) |    2c | прошло  7.6м · ост.~ 8.3м
  [water] тайл 231/482 | +31 (Σ18,500) |    2c | прошло  7.6м · ост.~ 8.3м
  [water] тайл 232/482 | +54 (Σ18,554) |    2c | прошло  7.7м · ост.~ 8.3м
  [water] тайл 233/482 | +43 (Σ18,597) |    2c | прошло  7.7м · ост.~ 8.2м
  [water] тайл 234/482 | +60 (Σ18,657) |    2c | прошло  7.7м · ост.~ 8.2м
  [water] тайл 235/482 | +52 (Σ18,709) |    2c | прошло  7.8м · ост.~ 8.1м
  [water] тайл 236/482 | +75 (Σ18,784) |    2c | прошло  7.8м · ост.~ 8.1м
  [water] тайл 237/482 | +98 (Σ18,882) |    3c | прошло  7.8м · ост.~ 8.1м
  [water] тайл 238/482 | +115 (Σ18,997) |    2c | прошло  7.9м · ост.~ 8.1м
  [water] тайл 239/482 | +139 (Σ19,136) |    2c | прошло  7.9м · ост.~ 8.0м
  [water] тайл 240/482 | +55 (Σ19,191) |    2c | прошло  7.9м · ост.~ 8.0м
  [water] тайл 241/482 | +37 (Σ19,228) |    2c | прошло  7.9м · ост.~ 7.9м
  [water] тайл 242/482 | +28 (Σ19,256) |    2c | прошло  8.0м · ост.~ 7.9м
  [water] тайл 243/482 | +31 (Σ19,287) |    2c | прошло  8.0м · ост.~ 7.9м
  [water] тайл 244/482 | +22 (Σ19,309) |    2c | прошло  8.0м · ост.~ 7.8м
  [water] тайл 245/482 | +17 (Σ19,326) |    2c | прошло  8.1м · ост.~ 7.8м
  [water] тайл 246/482 | +30 (Σ19,356) |    2c | прошло  8.1м · ост.~ 7.8м
  [water] тайл 247/482 | +73 (Σ19,429) |    2c | прошло  8.1м · ост.~ 7.7м
  [water] тайл 248/482 | +114 (Σ19,543) |    2c | прошло  8.2м · ост.~ 7.7м
  [water] тайл 249/482 | +182 (Σ19,725) |    2c | прошло  8.2м · ост.~ 7.7м
  [water] тайл 250/482 | +291 (Σ20,016) |    3c | прошло  8.2м · ост.~ 7.6м
  [water] тайл 251/482 | +245 (Σ20,261) |    2c | прошло  8.3м · ост.~ 7.6м
  [water] тайл 252/482 | +32 (Σ20,293) |    4c | прошло  8.3м · ост.~ 7.6м
  [water] тайл 253/482 | +65 (Σ20,358) |    3c | прошло  8.4м · ост.~ 7.6м
  [water] тайл 254/482 | +190 (Σ20,548) |    3c | прошло  8.4м · ост.~ 7.6м
  [water] тайл 255/482 | +209 (Σ20,757) |    2c | прошло  8.5м · ост.~ 7.6м
  [water] тайл 256/482 | +98 (Σ20,855) |    2c | прошло  8.5м · ост.~ 7.5м
  [water] тайл 257/482 | +67 (Σ20,922) |    2c | прошло  8.6м · ост.~ 7.5м
  [water] тайл 258/482 | +46 (Σ20,968) |    2c | прошло  8.6м · ост.~ 7.5м
  [water] тайл 259/482 | +32 (Σ21,000) |    2c | прошло  8.6м · ост.~ 7.4м
  [water] тайл 260/482 | +25 (Σ21,025) |    2c | прошло  8.7м · ост.~ 7.4м
  [water] тайл 261/482 | +34 (Σ21,059) |    2c | прошло  8.7м · ост.~ 7.4м
  [water] тайл 262/482 | +93 (Σ21,152) |    2c | прошло  8.7м · ост.~ 7.3м
  [water] тайл 263/482 | +42 (Σ21,194) |    2c | прошло  8.7м · ост.~ 7.3м
  [water] тайл 264/482 | +67 (Σ21,261) |    2c | прошло  8.8м · ост.~ 7.2м
  [water] тайл 265/482 | +81 (Σ21,342) |    2c | прошло  8.8м · ост.~ 7.2м
  [water] тайл 266/482 | +42 (Σ21,384) |    2c | прошло  8.8м · ост.~ 7.2м
  [water] тайл 267/482 | +29 (Σ21,413) |    2c | прошло  8.9м · ост.~ 7.1м
  [water] тайл 268/482 | +40 (Σ21,453) |    2c | прошло  8.9м · ост.~ 7.1м

In [15]:
layers["industrial"] = geo.fetch_layer(points, OSM_CACHE_DIR, "industrial")

[industrial] сетка ~5 км: 482 тайлов
  [industrial] скачиваю 482 тайлов из OSM…
  [industrial] тайл 1/482 | +9 (Σ9) |    2c | прошло  0.0м · ост.~12.4м
  [industrial] тайл 2/482 | +16 (Σ25) |    2c | прошло  0.1м · ост.~12.6м
  [industrial] тайл 3/482 | +6 (Σ31) |    2c | прошло  0.1м · ост.~12.8м
  [industrial] тайл 4/482 | +20 (Σ51) |    2c | прошло  0.1м · ост.~12.9м
  [industrial] тайл 5/482 | +15 (Σ66) |    2c | прошло  0.1м · ост.~13.0м
  [industrial] тайл 6/482 | +2 (Σ68) |    2c | прошло  0.2м · ост.~13.1м
  [industrial] тайл 7/482 | +0 (Σ68) |    1c | прошло  0.2м · ост.~11.8м
  [industrial] тайл 8/482 | +22 (Σ90) |    2c | прошло  0.2м · ост.~11.9м
  [industrial] тайл 9/482 | +8 (Σ98) |    2c | прошло  0.2м · ост.~12.0м
  [industrial] тайл 10/482 | +6 (Σ104) |    2c | прошло  0.3м · ост.~12.3м
  [industrial] тайл 11/482 | +5 (Σ109) |    2c | прошло  0.3м · ост.~12.3м
  [industrial] тайл 12/482 | +51 (Σ160) |    2c | прошло  0.3м · ост.~12.5м
  [industrial] тайл 13/482 | +2 (Σ162) |    2c | прошло  0.3м · ост.~12.6м
  [industrial] тайл 14/482 | +10 (Σ172) |    2c | прошло  0.4м · ост.~12.6м
  [industrial] тайл 15/482 | +17 (Σ189) |    2c | прошло  0.4м · ост.~12.7м
  [industrial] тайл 16/482 | +5 (Σ194) |    2c | прошло  0.4м · ост.~12.7м
  [industrial] тайл 17/482 | +8 (Σ202) |    2c | прошло  0.5м · ост.~12.7м
  [industrial] тайл 18/482 | +5 (Σ207) |    2c | прошло  0.5м · ост.~12.7м
  [industrial] тайл 19/482 | +2 (Σ209) |    2c | прошло  0.5м · ост.~12.6м
  [industrial] тайл 20/482 | +12 (Σ221) |    2c | прошло  0.6м · ост.~12.7м
  [industrial] тайл 21/482 | +3 (Σ224) |    2c | прошло  0.6м · ост.~12.7м
  [industrial] тайл 22/482 | +31 (Σ255) |    2c | прошло  0.6м · ост.~12.6м
  [industrial] тайл 23/482 | +106 (Σ361) |    2c | прошло  0.6м · ост.~12.6м
  [industrial] тайл 24/482 | +10 (Σ371) |    2c | прошло  0.7м · ост.~12.7м
  [industrial] тайл 25/482 | +11 (Σ382) |    2c | прошло  0.7м · ост.~12.6м
  [industrial] тайл 26/482 | +34 (Σ416) |    2c | прошло  0.7м · ост.~12.6м
  [industrial] тайл 27/482 | +15 (Σ431) |    2c | прошло  0.7м · ост.~12.6м
  [industrial] тайл 28/482 | +4 (Σ435) |    2c | прошло  0.8м · ост.~12.5м
  [industrial] тайл 29/482 | +4 (Σ439) |    2c | прошло  0.8м · ост.~12.5м
  [industrial] тайл 30/482 | +10 (Σ449) |    2c | прошло  0.8м · ост.~12.5м
  [industrial] тайл 31/482 | +25 (Σ474) |    2c | прошло  0.9м · ост.~12.5м
  [industrial] тайл 32/482 | +10 (Σ484) |    2c | прошло  0.9м · ост.~12.5м
  [industrial] тайл 33/482 | +6 (Σ490) |    2c | прошло  0.9м · ост.~12.5м
  [industrial] тайл 34/482 | +34 (Σ524) |    2c | прошло  0.9м · ост.~12.5м
  [industrial] тайл 35/482 | +6 (Σ530) |    2c | прошло  1.0м · ост.~12.4м
  [industrial] тайл 36/482 | +2 (Σ532) |    2c | прошло  1.0м · ост.~12.4м
  [industrial] тайл 37/482 | +22 (Σ554) |    2c | прошло  1.0м · ост.~12.4м
  [industrial] тайл 38/482 | +48 (Σ602) |    2c | прошло  1.1м · ост.~12.4м
  [industrial] тайл 39/482 | +8 (Σ610) |    2c | прошло  1.1м · ост.~12.3м
  [industrial] тайл 40/482 | +28 (Σ638) |    2c | прошло  1.1м · ост.~12.3м
  [industrial] тайл 41/482 | +66 (Σ704) |    2c | прошло  1.1м · ост.~12.3м
  [industrial] тайл 42/482 | +0 (Σ704) |    1c | прошло  1.2м · ост.~12.1м
  [industrial] тайл 43/482 | +3 (Σ707) |    3c | прошло  1.2м · ост.~12.2м
  [industrial] тайл 44/482 | +7 (Σ714) |    2c | прошло  1.2м · ост.~12.2м
  [industrial] тайл 45/482 | +2 (Σ716) |    1c | прошло  1.2м · ост.~12.1м
  [industrial] тайл 46/482 | +11 (Σ727) |    2c | прошло  1.3м · ост.~12.1м
  [industrial] тайл 47/482 | +13 (Σ740) |    2c | прошло  1.3м · ост.~12.1м
  [industrial] тайл 48/482 | +30 (Σ770) |    2c | прошло  1.3м · ост.~12.0м
  [industrial] тайл 49/482 | +8 (Σ778) |    2c | прошло  1.4м · ост.~12.0м
  [industrial] тайл 50/482 | +43 (Σ821) |    2c | прошло  1.4м · ост.~12.0м
  [industrial] тайл 51/482 | +12 (Σ833) |    2c | прошло  1.4м · ост.~11.9м
  [industrial] тайл 52/482 | +4 (Σ837) |    2c | прошло  1.4м · ост.~11.9м
  [industrial] тайл 53/482 | +3 (Σ840) |    2c | прошло  1.5м · ост.~11.9м
  [industrial] тайл 54/482 | +24 (Σ864) |   37c | прошло  2.1м · ост.~16.6м
  [industrial] тайл 55/482 | +39 (Σ903) |  123c | прошло  4.1м · ост.~32.2м
  [industrial] тайл 56/482 | +15 (Σ918) |    2c | прошло  4.2м · ост.~31.7м
  [industrial] тайл 57/482 | +9 (Σ927) |    2c | прошло  4.2м · ост.~31.3м
  [industrial] тайл 58/482 | +12 (Σ939) |    2c | прошло  4.2м · ост.~30.9м
  [industrial] тайл 59/482 | +26 (Σ965) |    2c | прошло  4.3м · ост.~30.5м
  [industrial] тайл 60/482 | +62 (Σ1,027) |    2c | прошло  4.3м · ост.~30.1м
  [industrial] тайл 61/482 | +15 (Σ1,042) |    2c | прошло  4.3м · ост.~29.7м
  [industrial] тайл 62/482 | +5 (Σ1,047) |    2c | прошло  4.3м · ост.~29.4м
  [industrial] тайл 63/482 | +35 (Σ1,082) |    2c | прошло  4.4м · ост.~29.0м
  [industrial] тайл 64/482 | +35 (Σ1,117) |    2c | прошло  4.4м · ост.~28.7м
  [industrial] тайл 65/482 | +72 (Σ1,189) |    2c | прошло  4.4м · ост.~28.4м
  [industrial] тайл 66/482 | +14 (Σ1,203) |    2c | прошло  4.5м · ост.~28.1м
  [industrial] тайл 67/482 | +18 (Σ1,221) |    2c | прошло  4.5м · ост.~27.8м
  [industrial] тайл 68/482 | +0 (Σ1,221) |    1c | прошло  4.5м · ост.~27.4м
  [industrial] тайл 69/482 | +52 (Σ1,273) |    2c | прошло  4.5м · ост.~27.1м
  [industrial] тайл 70/482 | +21 (Σ1,294) |    2c | прошло  4.6м · ост.~26.9м
  [industrial] тайл 71/482 | +29 (Σ1,323) |    2c | прошло  4.6м · ост.~26.6м
  [industrial] тайл 72/482 | +6 (Σ1,329) |    2c | прошло  4.6м · ост.~26.3м
  [industrial] тайл 73/482 | +5 (Σ1,334) |    2c | прошло  4.7м · ост.~26.1м
  [industrial] тайл 74/482 | +6 (Σ1,340) |    2c | прошло  4.7м · ост.~25.8м
  [industrial] тайл 75/482 | +7 (Σ1,347) |    2c | прошло  4.7м · ост.~25.6м
  [industrial] тайл 76/482 | +40 (Σ1,387) |    2c | прошло  4.7м · ост.~25.3м
  [industrial] тайл 77/482 | +83 (Σ1,470) |    2c | прошло  4.8м · ост.~25.1м
  [industrial] тайл 78/482 | +11 (Σ1,481) |    2c | прошло  4.8м · ост.~24.8м
  [industrial] тайл 79/482 | +8 (Σ1,489) |    2c | прошло  4.8м · ост.~24.6м
  [industrial] тайл 80/482 | +28 (Σ1,517) |    2c | прошло  4.9м · ост.~24.4м
  [industrial] тайл 81/482 | +31 (Σ1,548) |    2c | прошло  4.9м · ост.~24.2м
  [industrial] тайл 82/482 | +36 (Σ1,584) |    2c | прошло  4.9м · ост.~24.0м
  [industrial] тайл 83/482 | +14 (Σ1,598) |    2c | прошло  4.9м · ост.~23.8м
  [industrial] тайл 84/482 | +6 (Σ1,604) |    3c | прошло  5.0м · ост.~23.6м
  [industrial] тайл 85/482 | +18 (Σ1,622) |    2c | прошло  5.0м · ост.~23.5м
  [industrial] тайл 86/482 | +40 (Σ1,662) |  131c | прошло  7.2м · ост.~33.2м
  [industrial] тайл 87/482 | +95 (Σ1,757) |    2c | прошло  7.2м · ост.~32.9м
  [industrial] тайл 88/482 | +60 (Σ1,817) |    2c | прошло  7.3м · ост.~32.5м
  [industrial] тайл 89/482 | +3 (Σ1,820) |    3c | прошло  7.3м · ост.~32.3м
  [industrial] тайл 90/482 | +29 (Σ1,849) |    7c | прошло  7.4м · ост.~32.4м
  [industrial] тайл 91/482 | +13 (Σ1,862) |    8c | прошло  7.6м · ост.~32.5м
  [industrial] тайл 92/482 | +52 (Σ1,914) |    2c | прошло  7.6м · ост.~32.2м
  [industrial] тайл 93/482 | +39 (Σ1,953) |    3c | прошло  7.7м · ост.~32.0м
  [industrial] тайл 94/482 | +14 (Σ1,967) |    2c | прошло  7.7м · ост.~31.7м
  [industrial] тайл 95/482 | +0 (Σ1,967) |    3c | прошло  7.7м · ост.~31.5м
  [industrial] тайл 96/482 | +0 (Σ1,967) |    2c | прошло  7.8м · ост.~31.2м
  [industrial] тайл 97/482 | +1 (Σ1,968) |    7c | прошло  7.9м · ост.~31.3м
  [industrial] тайл 98/482 | +2 (Σ1,970) |    6c | прошло  8.0м · ост.~31.2м
  [industrial] тайл 99/482 | +1 (Σ1,971) |  104c | прошло  9.7м · ост.~37.6м
  [industrial] тайл 100/482 | +27 (Σ1,998) |    2c | прошло  9.7м · ост.~37.2м
  [industrial] тайл 101/482 | +45 (Σ2,043) |    2c | прошло  9.8м · ост.~36.9м
  [industrial] тайл 102/482 | +65 (Σ2,108) |  103c | прошло 11.5м · ост.~42.8м
  [industrial] тайл 103/482 | +101 (Σ2,209) |   19c | прошло 11.8м · ост.~43.5м
  [industrial] тайл 104/482 | +26 (Σ2,235) |    9c | прошло 12.0м · ост.~43.5м
  [industrial] тайл 105/482 | +43 (Σ2,278) |    6c | прошло 12.1м · ост.~43.3м
  [industrial] тайл 106/482 | +21 (Σ2,299) |  651c | прошло 22.9м · ост.~81.3м
  [industrial] тайл 107/482 | +103 (Σ2,402) |  325c | прошло 28.3м · ост.~99.3м
  [industrial] тайл 108/482 | +23 (Σ2,425) |    5c | прошло 28.4м · ост.~98.4м
  [industrial] тайл 109/482 | +32 (Σ2,457) |    2c | прошло 28.4м · ост.~97.3м
  [industrial] тайл 110/482 | +88 (Σ2,545) |    3c | прошло 28.5м · ост.~96.3м
  [industrial] тайл 111/482 | +96 (Σ2,641) |    2c | прошло 28.5м · ост.~95.3м
  [industrial] тайл 112/482 | +20 (Σ2,661) |    2c | прошло 28.6м · ост.~94.3м
  [industrial] тайл 113/482 | +24 (Σ2,685) |    6c | прошло 28.7м · ост.~93.6м
  [industrial] тайл 114/482 | +6 (Σ2,691) |    2c | прошло 28.7м · ост.~92.6м
  [industrial] тайл 115/482 | +121 (Σ2,812) |    2c | прошло 28.7м · ост.~91.6м
  [industrial] тайл 116/482 | +34 (Σ2,846) |    2c | прошло 28.7м · ост.~90.7м
  [industrial] тайл 117/482 | +8 (Σ2,854) |    2c | прошло 28.8м · ост.~89.7м
  [industrial] тайл 118/482 | +3 (Σ2,857) |    2c | прошло 28.8м · ост.~88.8м
  [industrial] тайл 119/482 | +4 (Σ2,861) |    2c | прошло 28.8м · ост.~87.9м
  [industrial] тайл 120/482 | +52 (Σ2,913) |    3c | прошло 28.9м · ост.~87.1м
  [industrial] тайл 121/482 | +53 (Σ2,966) |  124c | прошло 30.9м · ост.~92.3м
  [industrial] тайл 122/482 | +19 (Σ2,985) |    5c | прошло 31.0м · ост.~91.5м
  [industrial] тайл 123/482 | +16 (Σ3,001) |  150c | прошло 33.5м · ост.~97.8м
  [industrial] тайл 124/482 | +41 (Σ3,042) |   33c | прошло 34.1м · ост.~98.3м
  [industrial] тайл 125/482 | +156 (Σ3,198) |   28c | прошло 34.5м · ост.~98.6м
  [industrial] тайл 126/482 | +25 (Σ3,223) |  139c | прошло 36.9м · ост.~104.1м
  [industrial] тайл 127/482 | +33 (Σ3,256) |  287c | прошло 41.6м · ост.~116.4м
  [industrial] тайл 128/482 | +80 (Σ3,336) |    7c | прошло 41.8м · ост.~115.5м
  [industrial] тайл 129/482 | +143 (Σ3,479) |   89c | прошло 43.2м · ост.~118.3м
  [industrial] тайл 130/482 | +55 (Σ3,534) |    2c | прошло 43.3м · ост.~117.2м
  [industrial] тайл 131/482 | +51 (Σ3,585) |    2c | прошло 43.3м · ост.~116.0м
  [industrial] тайл 132/482 | +31 (Σ3,616) |    2c | прошло 43.3м · ост.~114.9м
  [industrial] тайл 133/482 | +26 (Σ3,642) |    2c | прошло 43.4м · ост.~113.8м
  [industrial] тайл 134/482 | +5 (Σ3,647) |    2c | прошло 43.4м · ост.~112.7м
  [industrial] тайл 135/482 | +4 (Σ3,651) |    2c | прошло 43.4м · ост.~111.6м
  [industrial] тайл 136/482 | +2 (Σ3,653) |    2c | прошло 43.5м · ост.~110.5м
  [industrial] тайл 137/482 | +50 (Σ3,703) |    2c | прошло 43.5м · ост.~109.5м
  [industrial] тайл 138/482 | +6 (Σ3,709) |    2c | прошло 43.5м · ост.~108.5м
  [industrial] тайл 139/482 | +67 (Σ3,776) |    2c | прошло 43.5м · ост.~107.4м
  [industrial] тайл 140/482 | +95 (Σ3,871) |    4c | прошло 43.6м · ост.~106.5м
  [industrial] тайл 141/482 | +4 (Σ3,875) |  277c | прошло 48.2м · ост.~116.6м
  [industrial] тайл 142/482 | +13 (Σ3,888) |   11c | прошло 48.4м · ост.~115.9м
  [industrial] тайл 143/482 | +14 (Σ3,902) |    2c | прошло 48.4м · ост.~114.8м
  [industrial] тайл 144/482 | +35 (Σ3,937) |    3c | прошло 48.5м · ост.~113.8м
  [industrial] тайл 145/482 | +23 (Σ3,960) |    2c | прошло 48.5м · ост.~112.8м
  [industrial] тайл 146/482 | +55 (Σ4,015) |    5c | прошло 48.6м · ост.~111.9м
  [industrial] тайл 147/482 | +83 (Σ4,098) |    5c | прошло 48.7м · ост.~111.0м
  [industrial] тайл 148/482 | +150 (Σ4,248) |    3c | прошло 48.8м · ост.~110.0м
  [industrial] тайл 149/482 | +49 (Σ4,297) |   14c | прошло 49.0м · ост.~109.5м
  [industrial] тайл 150/482 | +215 (Σ4,512) |    2c | прошло 49.0м · ост.~108.5м
  [industrial] тайл 151/482 | +385 (Σ4,897) |    2c | прошло 49.1м · ост.~107.6м
  [industrial] тайл 152/482 | +86 (Σ4,983) |    2c | прошло 49.1м · ост.~106.6м
  [industrial] тайл 153/482 | +83 (Σ5,066) |    2c | прошло 49.1м · ост.~105.7м
  [industrial] тайл 154/482 | +69 (Σ5,135) |    2c | прошло 49.2м · ост.~104.7м
  [industrial] тайл 155/482 | +8 (Σ5,143) |    2c | прошло 49.2м · ост.~103.8м
  [industrial] тайл 156/482 | +3 (Σ5,146) |    2c | прошло 49.2м · ост.~102.9м
  [industrial] тайл 157/482 | +8 (Σ5,154) |    2c | прошло 49.3м · ост.~102.0м
  [industrial] тайл 158/482 | +288 (Σ5,442) |    2c | прошло 49.3м · ост.~101.1м
  [industrial] тайл 159/482 | +73 (Σ5,515) |    2c | прошло 49.3м · ост.~100.2м
  [industrial] тайл 160/482 | +3 (Σ5,518) |    2c | прошло 49.3м · ост.~99.3м
  [industrial] тайл 161/482 | +3 (Σ5,521) |    2c | прошло 49.4м · ост.~98.4м
  [industrial] тайл 162/482 | +8 (Σ5,529) |    2c | прошло 49.4м · ост.~97.6м
  [industrial] тайл 163/482 | +13 (Σ5,542) |    2c | прошло 49.4м · ост.~96.7м
  [industrial] тайл 164/482 | +16 (Σ5,558) |    2c | прошло 49.5м · ост.~95.9м
  [industrial] тайл 165/482 | +8 (Σ5,566) |    2c | прошло 49.5м · ост.~95.1м
  [industrial] тайл 166/482 | +28 (Σ5,594) |    2c | прошло 49.5м · ост.~94.3м
  [industrial] тайл 167/482 | +50 (Σ5,644) |    2c | прошло 49.6м · ост.~93.5м
  [industrial] тайл 168/482 | +65 (Σ5,709) |    2c | прошло 49.6м · ост.~92.7м
  [industrial] тайл 169/482 | +142 (Σ5,851) |    2c | прошло 49.6м · ост.~91.9м
  [industrial] тайл 170/482 | +140 (Σ5,991) |    2c | прошло 49.7м · ост.~91.2м
  [industrial] тайл 171/482 | +118 (Σ6,109) |    2c | прошло 49.7м · ост.~90.4м
  [industrial] тайл 172/482 | +151 (Σ6,260) |    3c | прошло 49.7м · ост.~89.7м
  [industrial] тайл 173/482 | +313 (Σ6,573) |    2c | прошло 49.8м · ост.~88.9м
  [industrial] тайл 174/482 | +174 (Σ6,747) |    2c | прошло 49.8м · ост.~88.2м
  [industrial] тайл 175/482 | +96 (Σ6,843) |    2c | прошло 49.9м · ост.~87.5м
  [industrial] тайл 176/482 | +83 (Σ6,926) |    2c | прошло 49.9м · ост.~86.7м
  [industrial] тайл 177/482 | +48 (Σ6,974) |    2c | прошло 49.9м · ост.~86.0м
  [industrial] тайл 178/482 | +19 (Σ6,993) |    2c | прошло 49.9м · ост.~85.3м
  [industrial] тайл 179/482 | +14 (Σ7,007) |    2c | прошло 50.0м · ост.~84.6м
  [industrial] тайл 180/482 | +13 (Σ7,020) |    2c | прошло 50.0м · ост.~83.9м
  [industrial] тайл 181/482 | +1 (Σ7,021) |    2c | прошло 50.0м · ост.~83.2м
  [industrial] тайл 182/482 | +7 (Σ7,028) |    2c | прошло 50.1м · ост.~82.5м
  [industrial] тайл 183/482 | +5 (Σ7,033) |    2c | прошло 50.1м · ост.~81.8м
  [industrial] тайл 184/482 | +4 (Σ7,037) |    2c | прошло 50.1м · ост.~81.2м
  [industrial] тайл 185/482 | +0 (Σ7,037) |    0c | прошло 50.1м · ост.~80.5м
  [industrial] тайл 186/482 | +1 (Σ7,038) |    2c | прошло 50.1м · ост.~79.8м
  [industrial] тайл 187/482 | +24 (Σ7,062) |    2c | прошло 50.2м · ост.~79.1м
  [industrial] тайл 188/482 | +96 (Σ7,158) |    2c | прошло 50.2м · ост.~78.5м
  [industrial] тайл 189/482 | +120 (Σ7,278) |    2c | прошло 50.2м · ост.~77.9м
  [industrial] тайл 190/482 | +137 (Σ7,415) |    2c | прошло 50.3м · ост.~77.2м
  [industrial] тайл 191/482 | +96 (Σ7,511) |    2c | прошло 50.3м · ост.~76.6м
  [industrial] тайл 192/482 | +41 (Σ7,552) |    2c | прошло 50.3м · ост.~76.0м
  [industrial] тайл 193/482 | +60 (Σ7,612) |    2c | прошло 50.4м · ост.~75.4м
  [industrial] тайл 194/482 | +147 (Σ7,759) |    2c | прошло 50.4м · ост.~74.8м
  [industrial] тайл 195/482 | +182 (Σ7,941) |    2c | прошло 50.4м · ост.~74.2м
  [industrial] тайл 196/482 | +161 (Σ8,102) |    3c | прошло 50.5м · ост.~73.7м
  [industrial] тайл 197/482 | +289 (Σ8,391) |    3c | прошло 50.5м · ост.~73.1м
  [industrial] тайл 198/482 | +486 (Σ8,877) |    3c | прошло 50.6м · ост.~72.6м
  [industrial] тайл 199/482 | +276 (Σ9,153) |    2c | прошло 50.6м · ост.~72.0м
  [industrial] тайл 200/482 | +250 (Σ9,403) |    3c | прошло 50.7м · ост.~71.5м
  [industrial] тайл 201/482 | +153 (Σ9,556) |    2c | прошло 50.7м · ост.~70.9м
  [industrial] тайл 202/482 | +88 (Σ9,644) |    2c | прошло 50.7м · ост.~70.3м
  [industrial] тайл 203/482 | +99 (Σ9,743) |    2c | прошло 50.8м · ост.~69.8м
  [industrial] тайл 204/482 | +41 (Σ9,784) |    2c | прошло 50.8м · ост.~69.2м
  [industrial] тайл 205/482 | +25 (Σ9,809) |    2c | прошло 50.8м · ост.~68.7м
  [industrial] тайл 206/482 | +24 (Σ9,833) |    2c | прошло 50.9м · ост.~68.1м
  [industrial] тайл 207/482 | +3 (Σ9,836) |    2c | прошло 50.9м · ост.~67.6м
  [industrial] тайл 208/482 | +23 (Σ9,859) |    2c | прошло 50.9м · ост.~67.1м
  [industrial] тайл 209/482 | +26 (Σ9,885) |    2c | прошло 51.0м · ост.~66.6м
  [industrial] тайл 210/482 | +20 (Σ9,905) |    4c | прошло 51.0м · ост.~66.1м
  [industrial] тайл 211/482 | +16 (Σ9,921) |   23c | прошло 51.4м · ост.~66.0м
  [industrial] тайл 212/482 | +21 (Σ9,942) |   14c | прошло 51.6м · ост.~65.8м
  [industrial] тайл 213/482 | +20 (Σ9,962) |    2c | прошло 51.7м · ост.~65.2м
  [industrial] тайл 214/482 | +0 (Σ9,962) |   88c | прошло 53.1м · ост.~66.5м
  [industrial] тайл 215/482 | +3 (Σ9,965) |    2c | прошло 53.2м · ост.~66.0м
  [industrial] тайл 216/482 | +23 (Σ9,988) |    2c | прошло 53.2м · ост.~65.5м
  [industrial] тайл 217/482 | +36 (Σ10,024) |    2c | прошло 53.2м · ост.~65.0м
  [industrial] тайл 218/482 | +73 (Σ10,097) |    2c | прошло 53.2м · ост.~64.5м
  [industrial] тайл 219/482 | +104 (Σ10,201) |    2c | прошло 53.3м · ост.~64.0м
  [industrial] тайл 220/482 | +110 (Σ10,311) |    2c | прошло 53.3м · ост.~63.5м
  [industrial] тайл 221/482 | +105 (Σ10,416) |    2c | прошло 53.3м · ост.~63.0м
  [industrial] тайл 222/482 | +137 (Σ10,553) |    2c | прошло 53.4м · ост.~62.5м
  [industrial] тайл 223/482 | +206 (Σ10,759) |    2c | прошло 53.4м · ост.~62.0м
  [industrial] тайл 224/482 | +325 (Σ11,084) |    3c | прошло 53.4м · ост.~61.6м
  [industrial] тайл 225/482 | +535 (Σ11,619) |    2c | прошло 53.5м · ост.~61.1м
  [industrial] тайл 226/482 | +434 (Σ12,053) |    3c | прошло 53.5м · ост.~60.6м
  [industrial] тайл 227/482 | +259 (Σ12,312) |    2c | прошло 53.6м · ост.~60.2м
  [industrial] тайл 228/482 | +232 (Σ12,544) |    2c | прошло 53.6м · ост.~59.7м
  [industrial] тайл 229/482 | +50 (Σ12,594) |    2c | прошло 53.7м · ост.~59.3м
  [industrial] тайл 230/482 | +11 (Σ12,605) |    2c | прошло 53.7м · ост.~58.8м
  [industrial] тайл 231/482 | +8 (Σ12,613) |    2c | прошло 53.7м · ост.~58.4м
  [industrial] тайл 232/482 | +15 (Σ12,628) |    2c | прошло 53.7м · ост.~57.9м
  [industrial] тайл 233/482 | +3 (Σ12,631) |    2c | прошло 53.8м · ост.~57.5м
  [industrial] тайл 234/482 | +6 (Σ12,637) |    2c | прошло 53.8м · ост.~57.0м
  [industrial] тайл 235/482 | +14 (Σ12,651) |    2c | прошло 53.8м · ост.~56.6м
  [industrial] тайл 236/482 | +3 (Σ12,654) |    2c | прошло 53.8м · ост.~56.1м
  [industrial] тайл 237/482 | +28 (Σ12,682) |    2c | прошло 53.9м · ост.~55.7м
  [industrial] тайл 238/482 | +21 (Σ12,703) |    2c | прошло 53.9м · ост.~55.3м
  [industrial] тайл 239/482 | +5 (Σ12,708) |    2c | прошло 53.9м · ост.~54.8м
  [industrial] тайл 240/482 | +1 (Σ12,709) |    2c | прошло 54.0м · ост.~54.4м
  [industrial] тайл 241/482 | +0 (Σ12,709) |    1c | прошло 54.0м · ост.~54.0м
  [industrial] тайл 242/482 | +0 (Σ12,709) |    1c | прошло 54.0м · ост.~53.5м
  [industrial] тайл 243/482 | +10 (Σ12,719) |    2c | прошло 54.0м · ост.~53.1м
  [industrial] тайл 244/482 | +11 (Σ12,730) |    2c | прошло 54.0м · ост.~52.7м
  [industrial] тайл 245/482 | +5 (Σ12,735) |    2c | прошло 54.1м · ост.~52.3м
  [industrial] тайл 246/482 | +27 (Σ12,762) |    2c | прошло 54.1м · ост.~51.9м
  [industrial] тайл 247/482 | +23 (Σ12,785) |    2c | прошло 54.1м · ост.~51.5м
  [industrial] тайл 248/482 | +38 (Σ12,823) |    2c | прошло 54.1м · ост.~51.1м
  [industrial] тайл 249/482 | +114 (Σ12,937) |    2c | прошло 54.2м · ост.~50.7м
  [industrial] тайл 250/482 | +183 (Σ13,120) |    2c | прошло 54.2м · ост.~50.3м
  [industrial] тайл 251/482 | +146 (Σ13,266) |    2c | прошло 54.2м · ост.~49.9м
  [industrial] тайл 252/482 | +206 (Σ13,472) |    3c | прошло 54.3м · ост.~49.6м
  [industrial] тайл 253/482 | +480 (Σ13,952) |    3c | прошло 54.4м · ост.~49.2м
  [industrial] тайл 254/482 | +408 (Σ14,360) |    4c | прошло 54.4м · ост.~48.8м

In [16]:
layers["cemetery"] = geo.fetch_layer(points, OSM_CACHE_DIR, "cemetery")

[cemetery] сетка ~10 км: 164 тайлов
  [cemetery] скачиваю 164 тайлов из OSM…
  [cemetery] тайл 1/164 | +2 (Σ2) |    1c | прошло  0.0м · ост.~ 3.9м
  [cemetery] тайл 2/164 | +4 (Σ6) |    1c | прошло  0.0м · ост.~ 3.7м
  [cemetery] тайл 3/164 | +1 (Σ7) |   30c | прошло  0.5м · ост.~28.9м
  [cemetery] тайл 4/164 | +1 (Σ8) |    2c | прошло  0.6м · ост.~22.9м
  [cemetery] тайл 5/164 | +6 (Σ14) |  180c | прошло  3.6м · ост.~113.5м
  [cemetery] тайл 6/164 | +2 (Σ16) |    2c | прошло  3.6м · ост.~94.7м
  [cemetery] тайл 7/164 | +4 (Σ20) |    1c | прошло  3.6м · ост.~81.2м
  [cemetery] тайл 8/164 | +1 (Σ21) |    2c | прошло  3.6м · ост.~71.1м
  [cemetery] тайл 9/164 | +6 (Σ27) |    2c | прошло  3.7м · ост.~63.4м
  [cemetery] тайл 10/164 | +3 (Σ30) |    6c | прошло  3.8м · ост.~58.1м
  [cemetery] тайл 11/164 | +5 (Σ35) |    1c | прошло  3.8м · ост.~52.8м
  [cemetery] тайл 12/164 | +0 (Σ35) |    0c | прошло  3.8м · ост.~48.2м
  [cemetery] тайл 13/164 | +4 (Σ39) |    1c | прошло  3.8м · ост.~44.5м
  [cemetery] тайл 14/164 | +2 (Σ41) |    1c | прошло  3.9м · ост.~41.3м
  [cemetery] тайл 15/164 | +7 (Σ48) |    1c | прошло  3.9м · ост.~38.5м
  [cemetery] тайл 16/164 | +2 (Σ50) |    1c | прошло  3.9м · ост.~36.1м
  [cemetery] тайл 17/164 | +2 (Σ52) |    1c | прошло  3.9м · ост.~33.9м
  [cemetery] тайл 18/164 | +6 (Σ58) |    1c | прошло  3.9м · ост.~32.0м
  [cemetery] тайл 19/164 | +8 (Σ66) |    1c | прошло  4.0м · ост.~30.3м
  [cemetery] тайл 20/164 | +3 (Σ69) |    2c | прошло  4.0м · ост.~28.8м
  [cemetery] тайл 21/164 | +9 (Σ78) |    1c | прошло  4.0м · ост.~27.4м
  [cemetery] тайл 22/164 | +1 (Σ79) |    1c | прошло  4.0м · ост.~26.1м
  [cemetery] тайл 23/164 | +2 (Σ81) |    2c | прошло  4.1м · ост.~24.9м
  [cemetery] тайл 24/164 | +11 (Σ92) |    1c | прошло  4.1м · ост.~23.9м
  [cemetery] тайл 25/164 | +4 (Σ96) |    1c | прошло  4.1м · ост.~22.9м
  [cemetery] тайл 26/164 | +3 (Σ99) |    1c | прошло  4.1м · ост.~22.0м
  [cemetery] тайл 27/164 | +4 (Σ103) |    1c | прошло  4.2м · ост.~21.1м
  [cemetery] тайл 28/164 | +7 (Σ110) |    1c | прошло  4.2м · ост.~20.3м
  [cemetery] тайл 29/164 | +5 (Σ115) |    1c | прошло  4.2м · ост.~19.6м
  [cemetery] тайл 30/164 | +3 (Σ118) |    1c | прошло  4.2м · ост.~18.9м
  [cemetery] тайл 31/164 | +4 (Σ122) |    2c | прошло  4.3м · ост.~18.3м
  [cemetery] тайл 32/164 | +4 (Σ126) |    1c | прошло  4.3м · ост.~17.7м
  [cemetery] тайл 33/164 | +5 (Σ131) |    1c | прошло  4.3м · ост.~17.1м
  [cemetery] тайл 34/164 | +3 (Σ134) |    1c | прошло  4.3м · ост.~16.6м
  [cemetery] тайл 35/164 | +2 (Σ136) |    1c | прошло  4.4м · ост.~16.0м
  [cemetery] тайл 36/164 | +2 (Σ138) |    2c | прошло  4.4м · ост.~15.6м
  [cemetery] тайл 37/164 | +1 (Σ139) |    2c | прошло  4.4м · ост.~15.2м
  [cemetery] тайл 38/164 | +0 (Σ139) |    0c | прошло  4.4м · ост.~14.7м
  [cemetery] тайл 39/164 | +0 (Σ139) |    1c | прошло  4.4м · ост.~14.2м
  [cemetery] тайл 40/164 | +2 (Σ141) |    1c | прошло  4.5м · ост.~13.8м
  [cemetery] тайл 41/164 | +5 (Σ146) |    1c | прошло  4.5м · ост.~13.4м
  [cemetery] тайл 42/164 | +6 (Σ152) |    1c | прошло  4.5м · ост.~13.1м
  [cemetery] тайл 43/164 | +5 (Σ157) |    1c | прошло  4.5м · ост.~12.7м
  [cemetery] тайл 44/164 | +3 (Σ160) |    2c | прошло  4.6м · ост.~12.4м
  [cemetery] тайл 45/164 | +3 (Σ163) |    2c | прошло  4.6м · ост.~12.1м
  [cemetery] тайл 46/164 | +12 (Σ175) |    2c | прошло  4.6м · ост.~11.8м
  [cemetery] тайл 47/164 | +6 (Σ181) |    1c | прошло  4.6м · ост.~11.5м
  [cemetery] тайл 48/164 | +6 (Σ187) |    1c | прошло  4.6м · ост.~11.2м
  [cemetery] тайл 49/164 | +2 (Σ189) |    1c | прошло  4.7м · ост.~11.0м
  [cemetery] тайл 50/164 | +5 (Σ194) |    1c | прошло  4.7м · ост.~10.7м
  [cemetery] тайл 51/164 | +8 (Σ202) |    2c | прошло  4.7м · ост.~10.5м
  [cemetery] тайл 52/164 | +5 (Σ207) |    1c | прошло  4.7м · ост.~10.2м
  [cemetery] тайл 53/164 | +3 (Σ210) |    1c | прошло  4.8м · ост.~10.0м
  [cemetery] тайл 54/164 | +7 (Σ217) |    1c | прошло  4.8м · ост.~ 9.8м
  [cemetery] тайл 55/164 | +4 (Σ221) |    1c | прошло  4.8м · ост.~ 9.5м
  [cemetery] тайл 56/164 | +9 (Σ230) |    2c | прошло  4.8м · ост.~ 9.3м
  [cemetery] тайл 57/164 | +9 (Σ239) |    2c | прошло  4.9м · ост.~ 9.1м
  [cemetery] тайл 58/164 | +6 (Σ245) |    2c | прошло  4.9м · ост.~ 8.9м
  [cemetery] тайл 59/164 | +5 (Σ250) |    2c | прошло  4.9м · ост.~ 8.8м
  [cemetery] тайл 60/164 | +11 (Σ261) |    2c | прошло  4.9м · ост.~ 8.6м
  [cemetery] тайл 61/164 | +6 (Σ267) |    2c | прошло  5.0м · ост.~ 8.4м
  [cemetery] тайл 62/164 | +3 (Σ270) |    2c | прошло  5.0м · ост.~ 8.2м
  [cemetery] тайл 63/164 | +2 (Σ272) |    2c | прошло  5.0м · ост.~ 8.1м
  [cemetery] тайл 64/164 | +1 (Σ273) |    3c | прошло  5.1м · ост.~ 7.9м
  [cemetery] тайл 65/164 | +4 (Σ277) |   91c | прошло  6.6м · ост.~10.0м
  [cemetery] тайл 66/164 | +2 (Σ279) |    2c | прошло  6.6м · ост.~ 9.8м
  [cemetery] тайл 67/164 | +2 (Σ281) |    1c | прошло  6.6м · ост.~ 9.6м
  [cemetery] тайл 68/164 | +5 (Σ286) |    1c | прошло  6.7м · ост.~ 9.4м
  [cemetery] тайл 69/164 | +6 (Σ292) |    1c | прошло  6.7м · ост.~ 9.2м
  [cemetery] тайл 70/164 | +13 (Σ305) |    2c | прошло  6.7м · ост.~ 9.0м
  [cemetery] тайл 71/164 | +10 (Σ315) |    2c | прошло  6.7м · ост.~ 8.8м
  [cemetery] тайл 72/164 | +5 (Σ320) |    2c | прошло  6.8м · ост.~ 8.7м
  [cemetery] тайл 73/164 | +8 (Σ328) |    2c | прошло  6.8м · ост.~ 8.5м
  [cemetery] тайл 74/164 | +7 (Σ335) |    2c | прошло  6.8м · ост.~ 8.3м
  [cemetery] тайл 75/164 | +11 (Σ346) |    2c | прошло  6.9м · ост.~ 8.1м
  [cemetery] тайл 76/164 | +4 (Σ350) |    1c | прошло  6.9м · ост.~ 8.0м
  [cemetery] тайл 77/164 | +8 (Σ358) |    1c | прошло  6.9м · ост.~ 7.8м
  [cemetery] тайл 78/164 | +5 (Σ363) |    1c | прошло  6.9м · ост.~ 7.6м
  [cemetery] тайл 79/164 | +7 (Σ370) |    1c | прошло  7.0м · ост.~ 7.5м
  [cemetery] тайл 80/164 | +7 (Σ377) |    1c | прошло  7.0м · ост.~ 7.3м
  [cemetery] тайл 81/164 | +5 (Σ382) |    1c | прошло  7.0м · ост.~ 7.2м
  [cemetery] тайл 82/164 | +2 (Σ384) |    1c | прошло  7.0м · ост.~ 7.0м
  [cemetery] тайл 83/164 | +3 (Σ387) |    1c | прошло  7.0м · ост.~ 6.9м
  [cemetery] тайл 84/164 | +4 (Σ391) |    1c | прошло  7.1м · ост.~ 6.7м
  [cemetery] тайл 85/164 | +14 (Σ405) |    1c | прошло  7.1м · ост.~ 6.6м
  [cemetery] тайл 86/164 | +7 (Σ412) |    2c | прошло  7.1м · ост.~ 6.5м
  [cemetery] тайл 87/164 | +9 (Σ421) |    1c | прошло  7.1м · ост.~ 6.3м
  [cemetery] тайл 88/164 | +4 (Σ425) |    2c | прошло  7.2м · ост.~ 6.2м
  [cemetery] тайл 89/164 | +9 (Σ434) |    2c | прошло  7.2м · ост.~ 6.1м
  [cemetery] тайл 90/164 | +7 (Σ441) |    2c | прошло  7.2м · ост.~ 6.0м
  [cemetery] тайл 91/164 | +6 (Σ447) |    1c | прошло  7.3м · ост.~ 5.8м
  [cemetery] тайл 92/164 | +2 (Σ449) |    1c | прошло  7.3м · ост.~ 5.7м
  [cemetery] тайл 93/164 | +2 (Σ451) |    1c | прошло  7.3м · ост.~ 5.6м
  [cemetery] тайл 94/164 | +5 (Σ456) |    1c | прошло  7.3м · ост.~ 5.5м
  [cemetery] тайл 95/164 | +6 (Σ462) |    1c | прошло  7.4м · ост.~ 5.3м
  [cemetery] тайл 96/164 | +7 (Σ469) |    1c | прошло  7.4м · ост.~ 5.2м
  [cemetery] тайл 97/164 | +185 (Σ654) |    2c | прошло  7.4м · ост.~ 5.1м
  [cemetery] тайл 98/164 | +7 (Σ661) |    1c | прошло  7.4м · ост.~ 5.0м
  [cemetery] тайл 99/164 | +8 (Σ669) |    2c | прошло  7.5м · ост.~ 4.9м
  [cemetery] тайл 100/164 | +12 (Σ681) |    2c | прошло  7.5м · ост.~ 4.8м
  [cemetery] тайл 101/164 | +5 (Σ686) |    1c | прошло  7.5м · ост.~ 4.7м
  [cemetery] тайл 102/164 | +2 (Σ688) |    1c | прошло  7.5м · ост.~ 4.6м
  [cemetery] тайл 103/164 | +8 (Σ696) |    2c | прошло  7.6м · ост.~ 4.5м
  [cemetery] тайл 104/164 | +3 (Σ699) |    1c | прошло  7.6м · ост.~ 4.4м
  [cemetery] тайл 105/164 | +1 (Σ700) |    1c | прошло  7.6м · ост.~ 4.3м
  [cemetery] тайл 106/164 | +4 (Σ704) |    1c | прошло  7.6м · ост.~ 4.2м
  [cemetery] тайл 107/164 | +4 (Σ708) |    1c | прошло  7.7м · ост.~ 4.1м
  [cemetery] тайл 108/164 | +2 (Σ710) |    1c | прошло  7.7м · ост.~ 4.0м
  [cemetery] тайл 109/164 | +3 (Σ713) |    1c | прошло  7.7м · ост.~ 3.9м
  [cemetery] тайл 110/164 | +9 (Σ722) |    1c | прошло  7.7м · ост.~ 3.8м
  [cemetery] тайл 111/164 | +10 (Σ732) |    2c | прошло  7.8м · ост.~ 3.7м
  [cemetery] тайл 112/164 | +4 (Σ736) |    2c | прошло  7.8м · ост.~ 3.6м
  [cemetery] тайл 113/164 | +9 (Σ745) |    2c | прошло  7.8м · ост.~ 3.5м
  [cemetery] тайл 114/164 | +12 (Σ757) |    2c | прошло  7.8м · ост.~ 3.4м
  [cemetery] тайл 115/164 | +5 (Σ762) |    2c | прошло  7.9м · ост.~ 3.3м
  [cemetery] тайл 116/164 | +1 (Σ763) |    1c | прошло  7.9м · ост.~ 3.3м
  [cemetery] тайл 117/164 | +8 (Σ771) |    1c | прошло  7.9м · ост.~ 3.2м
  [cemetery] тайл 118/164 | +4 (Σ775) |    1c | прошло  7.9м · ост.~ 3.1м
  [cemetery] тайл 119/164 | +3 (Σ778) |    1c | прошло  8.0м · ост.~ 3.0м
  [cemetery] тайл 120/164 | +7 (Σ785) |    1c | прошло  8.0м · ост.~ 2.9м
  [cemetery] тайл 121/164 | +3 (Σ788) |    1c | прошло  8.0м · ост.~ 2.8м
  [cemetery] тайл 122/164 | +3 (Σ791) |    1c | прошло  8.0м · ост.~ 2.8м
  [cemetery] тайл 123/164 | +4 (Σ795) |    1c | прошло  8.1м · ост.~ 2.7м
  [cemetery] тайл 124/164 | +5 (Σ800) |    1c | прошло  8.1м · ост.~ 2.6м
  [cemetery] тайл 125/164 | +5 (Σ805) |    1c | прошло  8.1м · ост.~ 2.5м
  [cemetery] тайл 126/164 | +3 (Σ808) |    1c | прошло  8.1м · ост.~ 2.5м
  [cemetery] тайл 127/164 | +6 (Σ814) |    2c | прошло  8.2м · ост.~ 2.4м
  [cemetery] тайл 128/164 | +3 (Σ817) |    1c | прошло  8.2м · ост.~ 2.3м
  [cemetery] тайл 129/164 | +2 (Σ819) |    1c | прошло  8.2м · ост.~ 2.2м
  [cemetery] тайл 130/164 | +3 (Σ822) |    1c | прошло  8.2м · ост.~ 2.1м
  [cemetery] тайл 131/164 | +7 (Σ829) |    1c | прошло  8.2м · ост.~ 2.1м
  [cemetery] тайл 132/164 | +5 (Σ834) |    1c | прошло  8.3м · ост.~ 2.0м
  [cemetery] тайл 133/164 | +4 (Σ838) |    1c | прошло  8.3м · ост.~ 1.9м
  [cemetery] тайл 134/164 | +6 (Σ844) |    1c | прошло  8.3м · ост.~ 1.9м
  [cemetery] тайл 135/164 | +3 (Σ847) |    1c | прошло  8.3м · ост.~ 1.8м
  [cemetery] тайл 136/164 | +2 (Σ849) |    1c | прошло  8.4м · ост.~ 1.7м
  [cemetery] тайл 137/164 | +6 (Σ855) |    1c | прошло  8.4м · ост.~ 1.7м
  [cemetery] тайл 138/164 | +2 (Σ857) |    1c | прошло  8.4м · ост.~ 1.6м
  [cemetery] тайл 139/164 | +1 (Σ858) |    2c | прошло  8.4м · ост.~ 1.5м
  [cemetery] тайл 140/164 | +5 (Σ863) |    1c | прошло  8.5м · ост.~ 1.5м
  [cemetery] тайл 141/164 | +3 (Σ866) |    1c | прошло  8.5м · ост.~ 1.4м
  [cemetery] тайл 142/164 | +2 (Σ868) |    1c | прошло  8.5м · ост.~ 1.3м
  [cemetery] тайл 143/164 | +4 (Σ872) |    1c | прошло  8.5м · ост.~ 1.3м
  [cemetery] тайл 144/164 | +7 (Σ879) |    1c | прошло  8.6м · ост.~ 1.2м
  [cemetery] тайл 145/164 | +6 (Σ885) |    1c | прошло  8.6м · ост.~ 1.1м
  [cemetery] тайл 146/164 | +4 (Σ889) |    1c | прошло  8.6м · ост.~ 1.1м
  [cemetery] тайл 147/164 | +1 (Σ890) |    1c | прошло  8.6м · ост.~ 1.0м
  [cemetery] тайл 148/164 | +3 (Σ893) |    1c | прошло  8.6м · ост.~ 0.9м
  [cemetery] тайл 149/164 | +4 (Σ897) |    1c | прошло  8.7м · ост.~ 0.9м
  [cemetery] тайл 150/164 | +2 (Σ899) |    1c | прошло  8.7м · ост.~ 0.8м
  [cemetery] тайл 151/164 | +2 (Σ901) |    1c | прошло  8.7м · ост.~ 0.8м
  [cemetery] тайл 152/164 | +3 (Σ904) |    1c | прошло  8.7м · ост.~ 0.7м
  [cemetery] тайл 153/164 | +1 (Σ905) |    1c | прошло  8.8м · ост.~ 0.6м
  [cemetery] тайл 154/164 | +4 (Σ909) |    1c | прошло  8.8м · ост.~ 0.6м
  [cemetery] тайл 155/164 | +0 (Σ909) |    0c | прошло  8.8м · ост.~ 0.5м
  [cemetery] тайл 156/164 | +5 (Σ914) |    1c | прошло  8.8м · ост.~ 0.5м
  [cemetery] тайл 157/164 | +4 (Σ918) |    1c | прошло  8.8м · ост.~ 0.4м
  [cemetery] тайл 158/164 | +3 (Σ921) |    1c | прошло  8.9м · ост.~ 0.3м
  [cemetery] тайл 159/164 | +3 (Σ924) |    1c | прошло  8.9м · ост.~ 0.3м
  [cemetery] тайл 160/164 | +3 (Σ927) |    1c | прошло  8.9м · ост.~ 0.2м
  [cemetery] тайл 161/164 | +4 (Σ931) |    1c | прошло  8.9м · ост.~ 0.2м
  [cemetery] тайл 162/164 | +4 (Σ935) |    1c | прошло  9.0м · ост.~ 0.1м
  [cemetery] тайл 163/164 | +2 (Σ937) |    1c | прошло  9.0м · ост.~ 0.1м
  [cemetery] тайл 164/164 | +0 (Σ937) |    0c | прошло  9.0м · ост.~ 0.0м
  [cemetery] ГОТОВО: 913 объектов

In [17]:
layers["major_roads"] = geo.fetch_layer(points, OSM_CACHE_DIR, "major_roads")

[major_roads] сетка ~5 км: 482 тайлов
  [major_roads] скачиваю 482 тайлов из OSM…
  [major_roads] тайл 1/482 | +11 (Σ11) |    2c | прошло  0.0м · ост.~14.1м
  [major_roads] тайл 2/482 | +21 (Σ32) |    2c | прошло  0.1м · ост.~14.7м
  [major_roads] тайл 3/482 | +5 (Σ37) |    2c | прошло  0.1м · ост.~14.5м
  [major_roads] тайл 4/482 | +21 (Σ58) |    2c | прошло  0.1м · ост.~14.5м
  [major_roads] тайл 5/482 | +171 (Σ229) |    2c | прошло  0.2м · ост.~14.6м
  [major_roads] тайл 6/482 | +0 (Σ229) |    1c | прошло  0.2м · ост.~13.1м
  [major_roads] тайл 7/482 | +2 (Σ231) |    2c | прошло  0.2м · ост.~13.2м
  [major_roads] тайл 8/482 | +37 (Σ268) |    2c | прошло  0.2м · ост.~13.3м
  [major_roads] тайл 9/482 | +15 (Σ283) |    2c | прошло  0.3м · ост.~13.4м
  [major_roads] тайл 10/482 | +0 (Σ283) |    1c | прошло  0.3м · ост.~12.6м
  [major_roads] тайл 11/482 | +38 (Σ321) |    2c | прошло  0.3м · ост.~12.7м
  [major_roads] тайл 12/482 | +60 (Σ381) |    2c | прошло  0.3м · ост.~12.9м
  [major_roads] тайл 13/482 | +0 (Σ381) |    1c | прошло  0.3м · ост.~12.3м
  [major_roads] тайл 14/482 | +39 (Σ420) |    2c | прошло  0.4м · ост.~12.4м
  [major_roads] тайл 15/482 | +15 (Σ435) |    2c | прошло  0.4м · ост.~12.5м
  [major_roads] тайл 16/482 | +21 (Σ456) |    2c | прошло  0.4м · ост.~12.6м
  [major_roads] тайл 17/482 | +8 (Σ464) |    2c | прошло  0.5м · ост.~12.6м
  [major_roads] тайл 18/482 | +18 (Σ482) |    2c | прошло  0.5м · ост.~12.7м
  [major_roads] тайл 19/482 | +6 (Σ488) |    2c | прошло  0.5м · ост.~12.7м
  [major_roads] тайл 20/482 | +22 (Σ510) |    2c | прошло  0.6м · ост.~12.7м
  [major_roads] тайл 21/482 | +37 (Σ547) |    2c | прошло  0.6м · ост.~12.8м
  [major_roads] тайл 22/482 | +25 (Σ572) |    2c | прошло  0.6м · ост.~12.8м
  [major_roads] тайл 23/482 | +138 (Σ710) |    2c | прошло  0.6м · ост.~12.8м
  [major_roads] тайл 24/482 | +14 (Σ724) |    2c | прошло  0.7м · ост.~12.8м
  [major_roads] тайл 25/482 | +57 (Σ781) |    2c | прошло  0.7м · ост.~12.8м
  [major_roads] тайл 26/482 | +87 (Σ868) |    2c | прошло  0.7м · ост.~12.8м
  [major_roads] тайл 27/482 | +81 (Σ949) |    2c | прошло  0.8м · ост.~12.9м
  [major_roads] тайл 28/482 | +0 (Σ949) |    1c | прошло  0.8м · ост.~12.6м
  [major_roads] тайл 29/482 | +4 (Σ953) |    2c | прошло  0.8м · ост.~12.6м
  [major_roads] тайл 30/482 | +21 (Σ974) |    2c | прошло  0.8м · ост.~12.6м
  [major_roads] тайл 31/482 | +53 (Σ1,027) |    2c | прошло  0.9м · ост.~12.6м
  [major_roads] тайл 32/482 | +36 (Σ1,063) |    2c | прошло  0.9м · ост.~12.6м
  [major_roads] тайл 33/482 | +32 (Σ1,095) |    2c | прошло  0.9м · ост.~12.6м
  [major_roads] тайл 34/482 | +84 (Σ1,179) |    2c | прошло  1.0м · ост.~12.6м
  [major_roads] тайл 35/482 | +13 (Σ1,192) |    2c | прошло  1.0м · ост.~12.6м
  [major_roads] тайл 36/482 | +4 (Σ1,196) |    2c | прошло  1.0м · ост.~12.6м
  [major_roads] тайл 37/482 | +81 (Σ1,277) |    2c | прошло  1.0м · ост.~12.6м
  [major_roads] тайл 38/482 | +82 (Σ1,359) |    2c | прошло  1.1м · ост.~12.6м
  [major_roads] тайл 39/482 | +2 (Σ1,361) |    2c | прошло  1.1м · ост.~12.6м
  [major_roads] тайл 40/482 | +11 (Σ1,372) |    2c | прошло  1.1м · ост.~12.6м
  [major_roads] тайл 41/482 | +72 (Σ1,444) |    2c | прошло  1.2м · ост.~12.6м
  [major_roads] тайл 42/482 | +7 (Σ1,451) |    2c | прошло  1.2м · ост.~12.5м
  [major_roads] тайл 43/482 | +16 (Σ1,467) |    2c | прошло  1.2м · ост.~12.5м
  [major_roads] тайл 44/482 | +2 (Σ1,469) |    2c | прошло  1.3м · ост.~12.5м
  [major_roads] тайл 45/482 | +28 (Σ1,497) |    2c | прошло  1.3м · ост.~12.5м
  [major_roads] тайл 46/482 | +0 (Σ1,497) |    1c | прошло  1.3м · ост.~12.3м
  [major_roads] тайл 47/482 | +11 (Σ1,508) |    2c | прошло  1.3м · ост.~12.3м
  [major_roads] тайл 48/482 | +71 (Σ1,579) |    2c | прошло  1.4м · ост.~12.3м
  [major_roads] тайл 49/482 | +29 (Σ1,608) |    2c | прошло  1.4м · ост.~12.2м
  [major_roads] тайл 50/482 | +95 (Σ1,703) |    2c | прошло  1.4м · ост.~12.3м
  [major_roads] тайл 51/482 | +62 (Σ1,765) |    4c | прошло  1.5м · ост.~12.6м
  [major_roads] тайл 52/482 | +0 (Σ1,765) |    1c | прошло  1.5м · ост.~12.4м
  [major_roads] тайл 53/482 | +8 (Σ1,773) |    2c | прошло  1.5м · ост.~12.4м
  [major_roads] тайл 54/482 | +74 (Σ1,847) |    2c | прошло  1.6м · ост.~12.4м
  [major_roads] тайл 55/482 | +68 (Σ1,915) |    2c | прошло  1.6м · ост.~12.3м
  [major_roads] тайл 56/482 | +59 (Σ1,974) |    2c | прошло  1.6м · ост.~12.3м
  [major_roads] тайл 57/482 | +8 (Σ1,982) |    2c | прошло  1.7м · ост.~12.3м
  [major_roads] тайл 58/482 | +12 (Σ1,994) |    2c | прошло  1.7м · ост.~12.3м
  [major_roads] тайл 59/482 | +106 (Σ2,100) |    2c | прошло  1.7м · ост.~12.3м
  [major_roads] тайл 60/482 | +103 (Σ2,203) |    2c | прошло  1.7м · ост.~12.3м
  [major_roads] тайл 61/482 | +35 (Σ2,238) |    2c | прошло  1.8м · ост.~12.3м
  [major_roads] тайл 62/482 | +24 (Σ2,262) |    2c | прошло  1.8м · ост.~12.3м
  [major_roads] тайл 63/482 | +59 (Σ2,321) |    2c | прошло  1.8м · ост.~12.2м
  [major_roads] тайл 64/482 | +1 (Σ2,322) |    2c | прошло  1.9м · ост.~12.2м
  [major_roads] тайл 65/482 | +153 (Σ2,475) |    2c | прошло  1.9м · ост.~12.2м
  [major_roads] тайл 66/482 | +18 (Σ2,493) |    2c | прошло  1.9м · ост.~12.2м
  [major_roads] тайл 67/482 | +17 (Σ2,510) |    2c | прошло  2.0м · ост.~12.2м
  [major_roads] тайл 68/482 | +8 (Σ2,518) |    2c | прошло  2.0м · ост.~12.2м
  [major_roads] тайл 69/482 | +95 (Σ2,613) |    3c | прошло  2.1м · ост.~12.3м
  [major_roads] тайл 70/482 | +8 (Σ2,621) |    2c | прошло  2.1м · ост.~12.3м
  [major_roads] тайл 71/482 | +17 (Σ2,638) |    2c | прошло  2.1м · ост.~12.3м
  [major_roads] тайл 72/482 | +0 (Σ2,638) |    1c | прошло  2.1м · ост.~12.1м
  [major_roads] тайл 73/482 | +19 (Σ2,657) |    2c | прошло  2.2м · ост.~12.1м
  [major_roads] тайл 74/482 | +62 (Σ2,719) |    2c | прошло  2.2м · ост.~12.1м
  [major_roads] тайл 75/482 | +7 (Σ2,726) |    2c | прошло  2.2м · ост.~12.1м
  [major_roads] тайл 76/482 | +109 (Σ2,835) |    2c | прошло  2.3м · ост.~12.1м
  [major_roads] тайл 77/482 | +25 (Σ2,860) |    2c | прошло  2.3м · ост.~12.0м
  [major_roads] тайл 78/482 | +12 (Σ2,872) |    2c | прошло  2.3м · ост.~12.0м
  [major_roads] тайл 79/482 | +6 (Σ2,878) |    2c | прошло  2.4м · ост.~12.0м
  [major_roads] тайл 80/482 | +13 (Σ2,891) |    2c | прошло  2.4м · ост.~12.0м
  [major_roads] тайл 81/482 | +153 (Σ3,044) |    2c | прошло  2.4м · ост.~12.0м
  [major_roads] тайл 82/482 | +181 (Σ3,225) |    2c | прошло  2.5м · ост.~12.0м
  [major_roads] тайл 83/482 | +86 (Σ3,311) |    2c | прошло  2.5м · ост.~12.0м
  [major_roads] тайл 84/482 | +71 (Σ3,382) |    2c | прошло  2.5м · ост.~12.0м
  [major_roads] тайл 85/482 | +23 (Σ3,405) |    2c | прошло  2.6м · ост.~12.0м
  [major_roads] тайл 86/482 | +123 (Σ3,528) |    3c | прошло  2.6м · ост.~12.0м
  [major_roads] тайл 87/482 | +26 (Σ3,554) |    2c | прошло  2.6м · ост.~12.0м
  [major_roads] тайл 88/482 | +31 (Σ3,585) |    2c | прошло  2.7м · ост.~11.9м
  [major_roads] тайл 89/482 | +1 (Σ3,586) |    2c | прошло  2.7м · ост.~11.9м
  [major_roads] тайл 90/482 | +44 (Σ3,630) |    2c | прошло  2.7м · ост.~11.9м
  [major_roads] тайл 91/482 | +6 (Σ3,636) |    2c | прошло  2.8м · ост.~11.9м
  [major_roads] тайл 92/482 | +118 (Σ3,754) |    2c | прошло  2.8м · ост.~11.8м
  [major_roads] тайл 93/482 | +57 (Σ3,811) |    2c | прошло  2.8м · ост.~11.8м
  [major_roads] тайл 94/482 | +47 (Σ3,858) |    2c | прошло  2.9м · ост.~11.8м
  [major_roads] тайл 95/482 | +0 (Σ3,858) |    1c | прошло  2.9м · ост.~11.7м
  [major_roads] тайл 96/482 | +2 (Σ3,860) |    2c | прошло  2.9м · ост.~11.7м
  [major_roads] тайл 97/482 | +0 (Σ3,860) |    1c | прошло  2.9м · ост.~11.6м
  [major_roads] тайл 98/482 | +0 (Σ3,860) |    1c | прошло  2.9м · ост.~11.5м
  [major_roads] тайл 99/482 | +0 (Σ3,860) |    1c | прошло  2.9м · ост.~11.4м
  [major_roads] тайл 100/482 | +21 (Σ3,881) |    2c | прошло  3.0м · ост.~11.4м
  [major_roads] тайл 101/482 | +115 (Σ3,996) |    2c | прошло  3.0м · ост.~11.3м
  [major_roads] тайл 102/482 | +77 (Σ4,073) |    2c | прошло  3.0м · ост.~11.3м
  [major_roads] тайл 103/482 | +173 (Σ4,246) |    2c | прошло  3.1м · ост.~11.3м
  [major_roads] тайл 104/482 | +26 (Σ4,272) |    2c | прошло  3.1м · ост.~11.3м
  [major_roads] тайл 105/482 | +63 (Σ4,335) |    2c | прошло  3.1м · ост.~11.3м
  [major_roads] тайл 106/482 | +73 (Σ4,408) |    2c | прошло  3.2м · ост.~11.3м
  [major_roads] тайл 107/482 | +84 (Σ4,492) |    2c | прошло  3.2м · ост.~11.3м
  [major_roads] тайл 108/482 | +3 (Σ4,495) |    2c | прошло  3.2м · ост.~11.2м
  [major_roads] тайл 109/482 | +43 (Σ4,538) |    2c | прошло  3.3м · ост.~11.2м
  [major_roads] тайл 110/482 | +485 (Σ5,023) |    2c | прошло  3.3м · ост.~11.2м
  [major_roads] тайл 111/482 | +172 (Σ5,195) |    2c | прошло  3.3м · ост.~11.2м
  [major_roads] тайл 112/482 | +99 (Σ5,294) |    2c | прошло  3.4м · ост.~11.2м
  [major_roads] тайл 113/482 | +119 (Σ5,413) |    2c | прошло  3.4м · ост.~11.1м
  [major_roads] тайл 114/482 | +29 (Σ5,442) |    2c | прошло  3.4м · ост.~11.1м
  [major_roads] тайл 115/482 | +210 (Σ5,652) |    2c | прошло  3.5м · ост.~11.1м
  [major_roads] тайл 116/482 | +30 (Σ5,682) |    2c | прошло  3.5м · ост.~11.1м
  [major_roads] тайл 117/482 | +15 (Σ5,697) |    2c | прошло  3.5м · ост.~11.0м
  [major_roads] тайл 118/482 | +5 (Σ5,702) |    2c | прошло  3.6м · ост.~11.0м
  [major_roads] тайл 119/482 | +11 (Σ5,713) |    2c | прошло  3.6м · ост.~11.0м
  [major_roads] тайл 120/482 | +53 (Σ5,766) |    2c | прошло  3.6м · ост.~11.0м
  [major_roads] тайл 121/482 | +100 (Σ5,866) |    2c | прошло  3.7м · ост.~11.0м
  [major_roads] тайл 122/482 | +4 (Σ5,870) |    2c | прошло  3.7м · ост.~10.9м
  [major_roads] тайл 123/482 | +36 (Σ5,906) |    2c | прошло  3.7м · ост.~10.9м
  [major_roads] тайл 124/482 | +195 (Σ6,101) |    2c | прошло  3.8м · ост.~10.9м
  [major_roads] тайл 125/482 | +183 (Σ6,284) |    2c | прошло  3.8м · ост.~10.9м
  [major_roads] тайл 126/482 | +148 (Σ6,432) |    2c | прошло  3.8м · ост.~10.9м
  [major_roads] тайл 127/482 | +60 (Σ6,492) |    2c | прошло  3.9м · ост.~10.8м
  [major_roads] тайл 128/482 | +68 (Σ6,560) |    2c | прошло  3.9м · ост.~10.8м
  [major_roads] тайл 129/482 | +60 (Σ6,620) |    2c | прошло  3.9м · ост.~10.8м
  [major_roads] тайл 130/482 | +27 (Σ6,647) |    2c | прошло  4.0м · ост.~10.8м
  [major_roads] тайл 131/482 | +10 (Σ6,657) |    2c | прошло  4.0м · ост.~10.8м
  [major_roads] тайл 132/482 | +133 (Σ6,790) |    2c | прошло  4.0м · ост.~10.7м
  [major_roads] тайл 133/482 | +87 (Σ6,877) |    2c | прошло  4.1м · ост.~10.7м
  [major_roads] тайл 134/482 | +4 (Σ6,881) |    2c | прошло  4.1м · ост.~10.7м
  [major_roads] тайл 135/482 | +37 (Σ6,918) |    2c | прошло  4.1м · ост.~10.6м
  [major_roads] тайл 136/482 | +2 (Σ6,920) |    2c | прошло  4.2м · ост.~10.6м
  [major_roads] тайл 137/482 | +60 (Σ6,980) |    2c | прошло  4.2м · ост.~10.6м
  [major_roads] тайл 138/482 | +4 (Σ6,984) |    2c | прошло  4.2м · ост.~10.5м
  [major_roads] тайл 139/482 | +56 (Σ7,040) |    2c | прошло  4.3м · ост.~10.5м
  [major_roads] тайл 140/482 | +36 (Σ7,076) |    2c | прошло  4.3м · ост.~10.5м
  [major_roads] тайл 141/482 | +46 (Σ7,122) |    2c | прошло  4.3м · ост.~10.4м
  [major_roads] тайл 142/482 | +13 (Σ7,135) |    2c | прошло  4.4м · ост.~10.4м
  [major_roads] тайл 143/482 | +59 (Σ7,194) |    2c | прошло  4.4м · ост.~10.4м
  [major_roads] тайл 144/482 | +88 (Σ7,282) |    2c | прошло  4.4м · ост.~10.4м
  [major_roads] тайл 145/482 | +62 (Σ7,344) |    2c | прошло  4.4м · ост.~10.3м
  [major_roads] тайл 146/482 | +261 (Σ7,605) |    2c | прошло  4.5м · ост.~10.3м
  [major_roads] тайл 147/482 | +107 (Σ7,712) |    2c | прошло  4.5м · ост.~10.3м
  [major_roads] тайл 148/482 | +203 (Σ7,915) |    2c | прошло  4.6м · ост.~10.3м
  [major_roads] тайл 149/482 | +151 (Σ8,066) |    2c | прошло  4.6м · ост.~10.2м
  [major_roads] тайл 150/482 | +367 (Σ8,433) |    2c | прошло  4.6м · ост.~10.2м
  [major_roads] тайл 151/482 | +407 (Σ8,840) |    2c | прошло  4.7м · ост.~10.2м
  [major_roads] тайл 152/482 | +46 (Σ8,886) |    2c | прошло  4.7м · ост.~10.2м
  [major_roads] тайл 153/482 | +59 (Σ8,945) |    2c | прошло  4.7м · ост.~10.2м
  [major_roads] тайл 154/482 | +124 (Σ9,069) |    2c | прошло  4.8м · ост.~10.1м
  [major_roads] тайл 155/482 | +25 (Σ9,094) |    2c | прошло  4.8м · ост.~10.1м
  [major_roads] тайл 156/482 | +13 (Σ9,107) |    2c | прошло  4.8м · ост.~10.1м
  [major_roads] тайл 157/482 | +37 (Σ9,144) |    2c | прошло  4.9м · ост.~10.0м
  [major_roads] тайл 158/482 | +23 (Σ9,167) |    2c | прошло  4.9м · ост.~10.0м
  [major_roads] тайл 159/482 | +44 (Σ9,211) |    2c | прошло  4.9м · ост.~10.0м
  [major_roads] тайл 160/482 | +3 (Σ9,214) |    2c | прошло  4.9м · ост.~ 9.9м
  [major_roads] тайл 161/482 | +0 (Σ9,214) |    1c | прошло  5.0м · ост.~ 9.9м
  [major_roads] тайл 162/482 | +23 (Σ9,237) |    2c | прошло  5.0м · ост.~ 9.8м
  [major_roads] тайл 163/482 | +73 (Σ9,310) |    2c | прошло  5.0м · ост.~ 9.8м
  [major_roads] тайл 164/482 | +28 (Σ9,338) |    2c | прошло  5.0м · ост.~ 9.8м
  [major_roads] тайл 165/482 | +4 (Σ9,342) |    2c | прошло  5.1м · ост.~ 9.8м
  [major_roads] тайл 166/482 | +116 (Σ9,458) |    2c | прошло  5.1м · ост.~ 9.7м
  [major_roads] тайл 167/482 | +352 (Σ9,810) |    2c | прошло  5.2м · ост.~ 9.7м
  [major_roads] тайл 168/482 | +224 (Σ10,034) |    2c | прошло  5.2м · ост.~ 9.7м
  [major_roads] тайл 169/482 | +242 (Σ10,276) |    2c | прошло  5.2м · ост.~ 9.7м
  [major_roads] тайл 170/482 | +454 (Σ10,730) |    2c | прошло  5.3м · ост.~ 9.7м
  [major_roads] тайл 171/482 | +285 (Σ11,015) |    2c | прошло  5.3м · ост.~ 9.6м
  [major_roads] тайл 172/482 | +322 (Σ11,337) |    3c | прошло  5.3м · ост.~ 9.6м
  [major_roads] тайл 173/482 | +639 (Σ11,976) |    2c | прошло  5.4м · ост.~ 9.6м
  [major_roads] тайл 174/482 | +487 (Σ12,463) |    2c | прошло  5.4м · ост.~ 9.6м
  [major_roads] тайл 175/482 | +157 (Σ12,620) |    2c | прошло  5.5м · ост.~ 9.6м
  [major_roads] тайл 176/482 | +159 (Σ12,779) |    2c | прошло  5.5м · ост.~ 9.5м
  [major_roads] тайл 177/482 | +63 (Σ12,842) |    2c | прошло  5.5м · ост.~ 9.5м
  [major_roads] тайл 178/482 | +24 (Σ12,866) |    2c | прошло  5.5м · ост.~ 9.5м
  [major_roads] тайл 179/482 | +12 (Σ12,878) |    2c | прошло  5.6м · ост.~ 9.4м
  [major_roads] тайл 180/482 | +25 (Σ12,903) |    2c | прошло  5.6м · ост.~ 9.4м
  [major_roads] тайл 181/482 | +10 (Σ12,913) |    2c | прошло  5.6м · ост.~ 9.4м
  [major_roads] тайл 182/482 | +8 (Σ12,921) |    2c | прошло  5.7м · ост.~ 9.4м
  [major_roads] тайл 183/482 | +0 (Σ12,921) |    1c | прошло  5.7м · ост.~ 9.3м
  [major_roads] тайл 184/482 | +16 (Σ12,937) |    2c | прошло  5.7м · ост.~ 9.3м
  [major_roads] тайл 185/482 | +3 (Σ12,940) |    2c | прошло  5.7м · ост.~ 9.2м
  [major_roads] тайл 186/482 | +3 (Σ12,943) |    2c | прошло  5.8м · ост.~ 9.2м
  [major_roads] тайл 187/482 | +32 (Σ12,975) |    2c | прошло  5.8м · ост.~ 9.2м
  [major_roads] тайл 188/482 | +154 (Σ13,129) |    2c | прошло  5.8м · ост.~ 9.1м
  [major_roads] тайл 189/482 | +161 (Σ13,290) |    2c | прошло  5.9м · ост.~ 9.1м
  [major_roads] тайл 190/482 | +213 (Σ13,503) |    2c | прошло  5.9м · ост.~ 9.1м
  [major_roads] тайл 191/482 | +93 (Σ13,596) |    2c | прошло  5.9м · ост.~ 9.0м
  [major_roads] тайл 192/482 | +157 (Σ13,753) |    2c | прошло  6.0м · ост.~ 9.0м
  [major_roads] тайл 193/482 | +133 (Σ13,886) |    2c | прошло  6.0м · ост.~ 9.0м
  [major_roads] тайл 194/482 | +418 (Σ14,304) |    2c | прошло  6.0м · ост.~ 9.0м
  [major_roads] тайл 195/482 | +431 (Σ14,735) |    2c | прошло  6.1м · ост.~ 9.0м
  [major_roads] тайл 196/482 | +577 (Σ15,312) |    3c | прошло  6.1м · ост.~ 8.9м
  [major_roads] тайл 197/482 | +732 (Σ16,044) |    3c | прошло  6.2м · ост.~ 8.9м
  [major_roads] тайл 198/482 | +458 (Σ16,502) |    3c | прошло  6.2м · ост.~ 8.9м
  [major_roads] тайл 199/482 | +309 (Σ16,811) |    3c | прошло  6.3м · ост.~ 8.9м
  [major_roads] тайл 200/482 | +459 (Σ17,270) |    3c | прошло  6.3м · ост.~ 8.9м
  [major_roads] тайл 201/482 | +365 (Σ17,635) |    2c | прошло  6.4м · ост.~ 8.9м
  [major_roads] тайл 202/482 | +155 (Σ17,790) |    2c | прошло  6.4м · ост.~ 8.9м
  [major_roads] тайл 203/482 | +99 (Σ17,889) |    2c | прошло  6.4м · ост.~ 8.8м
  [major_roads] тайл 204/482 | +31 (Σ17,920) |    2c | прошло  6.5м · ост.~ 8.8м
  [major_roads] тайл 205/482 | +29 (Σ17,949) |    2c | прошло  6.5м · ост.~ 8.8м
  [major_roads] тайл 206/482 | +45 (Σ17,994) |    2c | прошло  6.5м · ост.~ 8.7м
  [major_roads] тайл 207/482 | +49 (Σ18,043) |    2c | прошло  6.5м · ост.~ 8.7м
  [major_roads] тайл 208/482 | +78 (Σ18,121) |    2c | прошло  6.6м · ост.~ 8.7м
  [major_roads] тайл 209/482 | +107 (Σ18,228) |    2c | прошло  6.6м · ост.~ 8.6м
  [major_roads] тайл 210/482 | +68 (Σ18,296) |    2c | прошло  6.6м · ост.~ 8.6м
  [major_roads] тайл 211/482 | +40 (Σ18,336) |    2c | прошло  6.7м · ост.~ 8.6м
  [major_roads] тайл 212/482 | +28 (Σ18,364) |    2c | прошло  6.7м · ост.~ 8.5м
  [major_roads] тайл 213/482 | +3 (Σ18,367) |    2c | прошло  6.7м · ост.~ 8.5м
  [major_roads] тайл 214/482 | +0 (Σ18,367) |    1c | прошло  6.7м · ост.~ 8.4м
  [major_roads] тайл 215/482 | +2 (Σ18,369) |    2c | прошло  6.8м · ост.~ 8.4м
  [major_roads] тайл 216/482 | +53 (Σ18,422) |    2c | прошло  6.8м · ост.~ 8.4м
  [major_roads] тайл 217/482 | +107 (Σ18,529) |    2c | прошло  6.8м · ост.~ 8.3м
  [major_roads] тайл 218/482 | +79 (Σ18,608) |    2c | прошло  6.9м · ост.~ 8.3м
  [major_roads] тайл 219/482 | +130 (Σ18,738) |    2c | прошло  6.9м · ост.~ 8.3м
  [major_roads] тайл 220/482 | +124 (Σ18,862) |    2c | прошло  6.9м · ост.~ 8.2м
  [major_roads] тайл 221/482 | +387 (Σ19,249) |    2c | прошло  6.9м · ост.~ 8.2м
  [major_roads] тайл 222/482 | +330 (Σ19,579) |    2c | прошло  7.0м · ост.~ 8.2м
  [major_roads] тайл 223/482 | +534 (Σ20,113) |    2c | прошло  7.0м · ост.~ 8.1м
  [major_roads] тайл 224/482 | +981 (Σ21,094) |    3c | прошло  7.1м · ост.~ 8.1м
  [major_roads] тайл 225/482 | +1317 (Σ22,411) |    3c | прошло  7.1м · ост.~ 8.1м
  [major_roads] тайл 226/482 | +780 (Σ23,191) |    3c | прошло  7.2м · ост.~ 8.1м
  [major_roads] тайл 227/482 | +662 (Σ23,853) |    2c | прошло  7.2м · ост.~ 8.1м
  [major_roads] тайл 228/482 | +401 (Σ24,254) |    2c | прошло  7.2м · ост.~ 8.1м
  [major_roads] тайл 229/482 | +12 (Σ24,266) |    2c | прошло  7.3м · ост.~ 8.0м
  [major_roads] тайл 230/482 | +9 (Σ24,275) |    2c | прошло  7.3м · ост.~ 8.0м
  [major_roads] тайл 231/482 | +9 (Σ24,284) |    2c | прошло  7.3м · ост.~ 8.0м
  [major_roads] тайл 232/482 | +0 (Σ24,284) |    1c | прошло  7.3м · ост.~ 7.9м
  [major_roads] тайл 233/482 | +0 (Σ24,284) |    1c | прошло  7.4м · ост.~ 7.9м
  [major_roads] тайл 234/482 | +0 (Σ24,284) |    1c | прошло  7.4м · ост.~ 7.8м
  [major_roads] тайл 235/482 | +45 (Σ24,329) |    2c | прошло  7.4м · ост.~ 7.8м
  [major_roads] тайл 236/482 | +0 (Σ24,329) |    1c | прошло  7.4м · ост.~ 7.7м
  [major_roads] тайл 237/482 | +40 (Σ24,369) |    2c | прошло  7.4м · ост.~ 7.7м
  [major_roads] тайл 238/482 | +26 (Σ24,395) |    2c | прошло  7.5м · ост.~ 7.7м
  [major_roads] тайл 239/482 | +2 (Σ24,397) |    2c | прошло  7.5м · ост.~ 7.6м
  [major_roads] тайл 240/482 | +2 (Σ24,399) |    2c | прошло  7.5м · ост.~ 7.6м
  [major_roads] тайл 241/482 | +0 (Σ24,399) |    1c | прошло  7.6м · ост.~ 7.6м
  [major_roads] тайл 242/482 | +0 (Σ24,399) |    1c | прошло  7.6м · ост.~ 7.5м
  [major_roads] тайл 243/482 | +0 (Σ24,399) |    1c | прошло  7.6м · ост.~ 7.5м
  [major_roads] тайл 244/482 | +37 (Σ24,436) |    2c | прошло  7.6м · ост.~ 7.4м
  [major_roads] тайл 245/482 | +3 (Σ24,439) |    2c | прошло  7.6м · ост.~ 7.4м
  [major_roads] тайл 246/482 | +28 (Σ24,467) |    2c | прошло  7.7м · ост.~ 7.4м
  [major_roads] тайл 247/482 | +24 (Σ24,491) |    2c | прошло  7.7м · ост.~ 7.3м
  [major_roads] тайл 248/482 | +112 (Σ24,603) |    2c | прошло  7.7м · ост.~ 7.3м
  [major_roads] тайл 249/482 | +162 (Σ24,765) |    2c | прошло  7.8м · ост.~ 7.3м

In [18]:
layers["railway"] = geo.fetch_layer(points, OSM_CACHE_DIR, "railway")

[railway] сетка ~5 км: 482 тайлов
  [railway] скачиваю 482 тайлов из OSM…
  [railway] тайл 1/482 | +28 (Σ28) |    1c | прошло  0.0м · ост.~11.0м
  [railway] тайл 2/482 | +0 (Σ28) |    0c | прошло  0.0м · ост.~ 6.8м
  [railway] тайл 3/482 | +0 (Σ28) |    0c | прошло  0.0м · ост.~ 5.3м
  [railway] тайл 4/482 | +50 (Σ78) |    1c | прошло  0.1м · ост.~ 6.9м
  [railway] тайл 5/482 | +0 (Σ78) |    0c | прошло  0.1м · ост.~ 5.9м
  [railway] тайл 6/482 | +0 (Σ78) |    0c | прошло  0.1м · ост.~ 5.4м
  [railway] тайл 7/482 | +0 (Σ78) |    0c | прошло  0.1м · ост.~ 4.9м
  [railway] тайл 8/482 | +13 (Σ91) |    1c | прошло  0.1м · ост.~ 5.7м
  [railway] тайл 9/482 | +2 (Σ93) |    1c | прошло  0.1м · ост.~ 6.2м
  [railway] тайл 10/482 | +0 (Σ93) |    0c | прошло  0.1м · ост.~ 5.8м
  [railway] тайл 11/482 | +0 (Σ93) |    0c | прошло  0.1м · ост.~ 5.5м
  [railway] тайл 12/482 | +59 (Σ152) |    1c | прошло  0.2м · ост.~ 5.9м
  [railway] тайл 13/482 | +0 (Σ152) |    0c | прошло  0.2м · ост.~ 5.7м
  [railway] тайл 14/482 | +2 (Σ154) |    1c | прошло  0.2м · ост.~ 6.1м
  [railway] тайл 15/482 | +2 (Σ156) |    1c | прошло  0.2м · ост.~ 6.4м
  [railway] тайл 16/482 | +0 (Σ156) |    0c | прошло  0.2м · ост.~ 6.1м
  [railway] тайл 17/482 | +21 (Σ177) |    1c | прошло  0.2м · ост.~ 6.3м
  [railway] тайл 18/482 | +7 (Σ184) |    1c | прошло  0.3м · ост.~ 6.6м
  [railway] тайл 19/482 | +0 (Σ184) |    0c | прошло  0.3м · ост.~ 6.4м
  [railway] тайл 20/482 | +0 (Σ184) |    0c | прошло  0.3м · ост.~ 6.2м
  [railway] тайл 21/482 | +2 (Σ186) |    1c | прошло  0.3м · ост.~ 6.4м
  [railway] тайл 22/482 | +8 (Σ194) |    1c | прошло  0.3м · ост.~ 6.5м
  [railway] тайл 23/482 | +101 (Σ295) |    1c | прошло  0.3м · ост.~ 6.7м
  [railway] тайл 24/482 | +4 (Σ299) |    2c | прошло  0.4м · ост.~ 6.9м
  [railway] тайл 25/482 | +0 (Σ299) |    0c | прошло  0.4м · ост.~ 6.7м
  [railway] тайл 26/482 | +116 (Σ415) |    1c | прошло  0.4м · ост.~ 6.8м
  [railway] тайл 27/482 | +7 (Σ422) |    1c | прошло  0.4м · ост.~ 6.9м
  [railway] тайл 28/482 | +0 (Σ422) |    0c | прошло  0.4м · ост.~ 6.8м
  [railway] тайл 29/482 | +2 (Σ424) |    1c | прошло  0.4м · ост.~ 6.9м
  [railway] тайл 30/482 | +91 (Σ515) |    1c | прошло  0.5м · ост.~ 7.0м
  [railway] тайл 31/482 | +8 (Σ523) |    1c | прошло  0.5м · ост.~ 7.1м
  [railway] тайл 32/482 | +6 (Σ529) |    1c | прошло  0.5м · ост.~ 7.2м
  [railway] тайл 33/482 | +6 (Σ535) |    1c | прошло  0.5м · ост.~ 7.2м
  [railway] тайл 34/482 | +3 (Σ538) |    1c | прошло  0.6м · ост.~ 7.3м
  [railway] тайл 35/482 | +0 (Σ538) |    0c | прошло  0.6м · ост.~ 7.2м
  [railway] тайл 36/482 | +5 (Σ543) |    1c | прошло  0.6м · ост.~ 7.2м
  [railway] тайл 37/482 | +17 (Σ560) |    1c | прошло  0.6м · ост.~ 7.3м
  [railway] тайл 38/482 | +0 (Σ560) |    0c | прошло  0.6м · ост.~ 7.2м
  [railway] тайл 39/482 | +0 (Σ560) |    0c | прошло  0.6м · ост.~ 7.0м
  [railway] тайл 40/482 | +17 (Σ577) |    1c | прошло  0.6м · ост.~ 7.1м
  [railway] тайл 41/482 | +31 (Σ608) |    1c | прошло  0.7м · ост.~ 7.2м
  [railway] тайл 42/482 | +0 (Σ608) |    0c | прошло  0.7м · ост.~ 7.0м
  [railway] тайл 43/482 | +0 (Σ608) |    0c | прошло  0.7м · ост.~ 6.9м
  [railway] тайл 44/482 | +0 (Σ608) |    0c | прошло  0.7м · ост.~ 6.8м
  [railway] тайл 45/482 | +0 (Σ608) |    0c | прошло  0.7м · ост.~ 6.7м
  [railway] тайл 46/482 | +0 (Σ608) |    0c | прошло  0.7м · ост.~ 6.6м
  [railway] тайл 47/482 | +5 (Σ613) |    1c | прошло  0.7м · ост.~ 6.7м
  [railway] тайл 48/482 | +54 (Σ667) |    2c | прошло  0.7м · ост.~ 6.7м
  [railway] тайл 49/482 | +1 (Σ668) |    1c | прошло  0.8м · ост.~ 6.8м
  [railway] тайл 50/482 | +44 (Σ712) |    1c | прошло  0.8м · ост.~ 6.8м
  [railway] тайл 51/482 | +1 (Σ713) |    2c | прошло  0.8м · ост.~ 6.9м
  [railway] тайл 52/482 | +0 (Σ713) |    0c | прошло  0.8м · ост.~ 6.8м
  [railway] тайл 53/482 | +0 (Σ713) |    0c | прошло  0.8м · ост.~ 6.7м
  [railway] тайл 54/482 | +0 (Σ713) |    0c | прошло  0.8м · ост.~ 6.6м
  [railway] тайл 55/482 | +65 (Σ778) |    1c | прошло  0.9м · ост.~ 6.6м
  [railway] тайл 56/482 | +24 (Σ802) |    2c | прошло  0.9м · ост.~ 6.7м
  [railway] тайл 57/482 | +0 (Σ802) |    0c | прошло  0.9м · ост.~ 6.6м
  [railway] тайл 58/482 | +0 (Σ802) |    0c | прошло  0.9м · ост.~ 6.5м
  [railway] тайл 59/482 | +0 (Σ802) |    1c | прошло  0.9м · ост.~ 6.5м
  [railway] тайл 60/482 | +32 (Σ834) |    2c | прошло  0.9м · ост.~ 6.5м
  [railway] тайл 61/482 | +2 (Σ836) |    1c | прошло  1.0м · ост.~ 6.6м
  [railway] тайл 62/482 | +0 (Σ836) |    0c | прошло  1.0м · ост.~ 6.5м
  [railway] тайл 63/482 | +12 (Σ848) |    1c | прошло  1.0м · ост.~ 6.5м
  [railway] тайл 64/482 | +61 (Σ909) |    1c | прошло  1.0м · ост.~ 6.6м
  [railway] тайл 65/482 | +24 (Σ933) |    1c | прошло  1.0м · ост.~ 6.6м
  [railway] тайл 66/482 | +6 (Σ939) |    1c | прошло  1.1м · ост.~ 6.6м
  [railway] тайл 67/482 | +0 (Σ939) |    0c | прошло  1.1м · ост.~ 6.6м
  [railway] тайл 68/482 | +0 (Σ939) |    0c | прошло  1.1м · ост.~ 6.5м
  [railway] тайл 69/482 | +0 (Σ939) |    0c | прошло  1.1м · ост.~ 6.4м
  [railway] тайл 70/482 | +0 (Σ939) |    0c | прошло  1.1м · ост.~ 6.3м
  [railway] тайл 71/482 | +9 (Σ948) |    1c | прошло  1.1м · ост.~ 6.4м
  [railway] тайл 72/482 | +2 (Σ950) |    1c | прошло  1.1м · ост.~ 6.4м
  [railway] тайл 73/482 | +2 (Σ952) |    1c | прошло  1.1м · ост.~ 6.4м
  [railway] тайл 74/482 | +11 (Σ963) |    1c | прошло  1.2м · ост.~ 6.4м
  [railway] тайл 75/482 | +6 (Σ969) |    1c | прошло  1.2м · ост.~ 6.5м
  [railway] тайл 76/482 | +25 (Σ994) |    1c | прошло  1.2м · ост.~ 6.5м
  [railway] тайл 77/482 | +32 (Σ1,026) |    1c | прошло  1.2м · ост.~ 6.5м
  [railway] тайл 78/482 | +0 (Σ1,026) |    0c | прошло  1.2м · ост.~ 6.4м
  [railway] тайл 79/482 | +0 (Σ1,026) |    0c | прошло  1.3м · ост.~ 6.4м
  [railway] тайл 80/482 | +0 (Σ1,026) |    0c | прошло  1.3м · ост.~ 6.3м
  [railway] тайл 81/482 | +63 (Σ1,089) |    2c | прошло  1.3м · ост.~ 6.3м
  [railway] тайл 82/482 | +4 (Σ1,093) |    1c | прошло  1.3м · ост.~ 6.4м
  [railway] тайл 83/482 | +12 (Σ1,105) |    1c | прошло  1.3м · ост.~ 6.4м
  [railway] тайл 84/482 | +0 (Σ1,105) |    0c | прошло  1.3м · ост.~ 6.3м
  [railway] тайл 85/482 | +0 (Σ1,105) |    0c | прошло  1.3м · ост.~ 6.3м
  [railway] тайл 86/482 | +0 (Σ1,105) |    0c | прошло  1.3м · ост.~ 6.2м
  [railway] тайл 87/482 | +6 (Σ1,111) |    1c | прошло  1.4м · ост.~ 6.2м
  [railway] тайл 88/482 | +23 (Σ1,134) |    2c | прошло  1.4м · ост.~ 6.3м
  [railway] тайл 89/482 | +0 (Σ1,134) |    0c | прошло  1.4м · ост.~ 6.2м
  [railway] тайл 90/482 | +0 (Σ1,134) |    0c | прошло  1.4м · ост.~ 6.1м
  [railway] тайл 91/482 | +4 (Σ1,138) |    2c | прошло  1.4м · ост.~ 6.2м
  [railway] тайл 92/482 | +83 (Σ1,221) |    1c | прошло  1.5м · ост.~ 6.2м
  [railway] тайл 93/482 | +0 (Σ1,221) |    0c | прошло  1.5м · ост.~ 6.1м
  [railway] тайл 94/482 | +0 (Σ1,221) |    0c | прошло  1.5м · ост.~ 6.1м
  [railway] тайл 95/482 | +0 (Σ1,221) |    0c | прошло  1.5м · ост.~ 6.0м
  [railway] тайл 96/482 | +0 (Σ1,221) |    0c | прошло  1.5м · ост.~ 6.0м
  [railway] тайл 97/482 | +0 (Σ1,221) |    0c | прошло  1.5м · ост.~ 5.9м
  [railway] тайл 98/482 | +0 (Σ1,221) |    0c | прошло  1.5м · ост.~ 5.8м
  [railway] тайл 99/482 | +0 (Σ1,221) |    0c | прошло  1.5м · ост.~ 5.8м
  [railway] тайл 100/482 | +0 (Σ1,221) |    0c | прошло  1.5м · ост.~ 5.7м
  [railway] тайл 101/482 | +0 (Σ1,221) |    0c | прошло  1.5м · ост.~ 5.7м
  [railway] тайл 102/482 | +55 (Σ1,276) |    1c | прошло  1.5м · ост.~ 5.7м
  [railway] тайл 103/482 | +14 (Σ1,290) |    1c | прошло  1.6м · ост.~ 5.7м
  [railway] тайл 104/482 | +6 (Σ1,296) |    1c | прошло  1.6м · ост.~ 5.8м
  [railway] тайл 105/482 | +15 (Σ1,311) |    1c | прошло  1.6м · ост.~ 5.8м
  [railway] тайл 106/482 | +0 (Σ1,311) |    0c | прошло  1.6м · ост.~ 5.7м
  [railway] тайл 107/482 | +88 (Σ1,399) |    1c | прошло  1.6м · ост.~ 5.7м
  [railway] тайл 108/482 | +0 (Σ1,399) |    0c | прошло  1.6м · ост.~ 5.7м
  [railway] тайл 109/482 | +0 (Σ1,399) |    0c | прошло  1.7м · ост.~ 5.7м
  [railway] тайл 110/482 | +183 (Σ1,582) |    1c | прошло  1.7м · ост.~ 5.7м
  [railway] тайл 111/482 | +26 (Σ1,608) |    1c | прошло  1.7м · ост.~ 5.7м
  [railway] тайл 112/482 | +3 (Σ1,611) |    1c | прошло  1.7м · ост.~ 5.7м
  [railway] тайл 113/482 | +0 (Σ1,611) |    0c | прошло  1.7м · ост.~ 5.6м
  [railway] тайл 114/482 | +4 (Σ1,615) |    1c | прошло  1.7м · ост.~ 5.6м
  [railway] тайл 115/482 | +12 (Σ1,627) |    1c | прошло  1.8м · ост.~ 5.7м
  [railway] тайл 116/482 | +0 (Σ1,627) |    0c | прошло  1.8м · ост.~ 5.6м
  [railway] тайл 117/482 | +0 (Σ1,627) |    0c | прошло  1.8м · ост.~ 5.6м
  [railway] тайл 118/482 | +0 (Σ1,627) |    0c | прошло  1.8м · ост.~ 5.5м
  [railway] тайл 119/482 | +0 (Σ1,627) |    0c | прошло  1.8м · ост.~ 5.5м
  [railway] тайл 120/482 | +0 (Σ1,627) |    0c | прошло  1.8м · ост.~ 5.4м
  [railway] тайл 121/482 | +0 (Σ1,627) |    0c | прошло  1.8м · ост.~ 5.4м
  [railway] тайл 122/482 | +0 (Σ1,627) |    0c | прошло  1.8м · ост.~ 5.3м
  [railway] тайл 123/482 | +0 (Σ1,627) |    0c | прошло  1.8м · ост.~ 5.3м
  [railway] тайл 124/482 | +42 (Σ1,669) |    1c | прошло  1.8м · ост.~ 5.3м
  [railway] тайл 125/482 | +150 (Σ1,819) |    2c | прошло  1.9м · ост.~ 5.3м
  [railway] тайл 126/482 | +0 (Σ1,819) |    0c | прошло  1.9м · ост.~ 5.3м
  [railway] тайл 127/482 | +4 (Σ1,823) |    1c | прошло  1.9м · ост.~ 5.3м
  [railway] тайл 128/482 | +27 (Σ1,850) |    1c | прошло  1.9м · ост.~ 5.3м
  [railway] тайл 129/482 | +6 (Σ1,856) |    1c | прошло  1.9м · ост.~ 5.3м
  [railway] тайл 130/482 | +0 (Σ1,856) |    0c | прошло  1.9м · ост.~ 5.3м
  [railway] тайл 131/482 | +24 (Σ1,880) |    1c | прошло  2.0м · ост.~ 5.3м
  [railway] тайл 132/482 | +18 (Σ1,898) |    1c | прошло  2.0м · ост.~ 5.3м
  [railway] тайл 133/482 | +0 (Σ1,898) |    0c | прошло  2.0м · ост.~ 5.3м
  [railway] тайл 134/482 | +1 (Σ1,899) |    1c | прошло  2.0м · ост.~ 5.3м
  [railway] тайл 135/482 | +0 (Σ1,899) |    0c | прошло  2.0м · ост.~ 5.2м
  [railway] тайл 136/482 | +1 (Σ1,900) |    1c | прошло  2.1м · ост.~ 5.2м
  [railway] тайл 137/482 | +19 (Σ1,919) |    1c | прошло  2.1м · ост.~ 5.2м
  [railway] тайл 138/482 | +0 (Σ1,919) |    0c | прошло  2.1м · ост.~ 5.2м
  [railway] тайл 139/482 | +8 (Σ1,927) |    1c | прошло  2.1м · ост.~ 5.2м
  [railway] тайл 140/482 | +19 (Σ1,946) |    1c | прошло  2.1м · ост.~ 5.2м
  [railway] тайл 141/482 | +0 (Σ1,946) |    0c | прошло  2.1м · ост.~ 5.2м
  [railway] тайл 142/482 | +0 (Σ1,946) |    0c | прошло  2.1м · ост.~ 5.1м
  [railway] тайл 143/482 | +0 (Σ1,946) |    0c | прошло  2.1м · ост.~ 5.1м
  [railway] тайл 144/482 | +0 (Σ1,946) |    0c | прошло  2.2м · ост.~ 5.1м
  [railway] тайл 145/482 | +0 (Σ1,946) |    0c | прошло  2.2м · ост.~ 5.0м
  [railway] тайл 146/482 | +145 (Σ2,091) |    1c | прошло  2.2м · ост.~ 5.0м
  [railway] тайл 147/482 | +109 (Σ2,200) |    1c | прошло  2.2м · ост.~ 5.0м
  [railway] тайл 148/482 | +84 (Σ2,284) |    2c | прошло  2.2м · ост.~ 5.0м
  [railway] тайл 149/482 | +24 (Σ2,308) |    2c | прошло  2.3м · ост.~ 5.1м
  [railway] тайл 150/482 | +248 (Σ2,556) |    2c | прошло  2.3м · ост.~ 5.1м
  [railway] тайл 151/482 | +143 (Σ2,699) |    1c | прошло  2.3м · ост.~ 5.1м
  [railway] тайл 152/482 | +23 (Σ2,722) |    2c | прошло  2.3м · ост.~ 5.1м
  [railway] тайл 153/482 | +25 (Σ2,747) |    1c | прошло  2.4м · ост.~ 5.1м
  [railway] тайл 154/482 | +0 (Σ2,747) |    0c | прошло  2.4м · ост.~ 5.0м
  [railway] тайл 155/482 | +0 (Σ2,747) |    0c | прошло  2.4м · ост.~ 5.0м
  [railway] тайл 156/482 | +3 (Σ2,750) |    1c | прошло  2.4м · ост.~ 5.0м
  [railway] тайл 157/482 | +2 (Σ2,752) |    1c | прошло  2.4м · ост.~ 5.0м
  [railway] тайл 158/482 | +20 (Σ2,772) |    1c | прошло  2.4м · ост.~ 5.0м
  [railway] тайл 159/482 | +70 (Σ2,842) |    1c | прошло  2.5м · ост.~ 5.0м
  [railway] тайл 160/482 | +2 (Σ2,844) |    1c | прошло  2.5м · ост.~ 5.0м
  [railway] тайл 161/482 | +8 (Σ2,852) |    1c | прошло  2.5м · ост.~ 5.0м
  [railway] тайл 162/482 | +3 (Σ2,855) |    1c | прошло  2.5м · ост.~ 5.0м
  [railway] тайл 163/482 | +0 (Σ2,855) |    0c | прошло  2.5м · ост.~ 5.0м
  [railway] тайл 164/482 | +0 (Σ2,855) |    0c | прошло  2.5м · ост.~ 4.9м
  [railway] тайл 165/482 | +0 (Σ2,855) |    0c | прошло  2.6м · ост.~ 4.9м
  [railway] тайл 166/482 | +58 (Σ2,913) |    1c | прошло  2.6м · ост.~ 4.9м
  [railway] тайл 167/482 | +90 (Σ3,003) |    2c | прошло  2.6м · ост.~ 4.9м
  [railway] тайл 168/482 | +47 (Σ3,050) |    2c | прошло  2.6м · ост.~ 4.9м
  [railway] тайл 169/482 | +99 (Σ3,149) |    2c | прошло  2.7м · ост.~ 4.9м
  [railway] тайл 170/482 | +312 (Σ3,461) |    3c | прошло  2.7м · ост.~ 4.9м
  [railway] тайл 171/482 | +53 (Σ3,514) |    1c | прошло  2.7м · ост.~ 4.9м
  [railway] тайл 172/482 | +164 (Σ3,678) |    2c | прошло  2.8м · ост.~ 5.0м
  [railway] тайл 173/482 | +119 (Σ3,797) |    2c | прошло  2.8м · ост.~ 5.0м
  [railway] тайл 174/482 | +168 (Σ3,965) |    2c | прошло  2.8м · ост.~ 5.0м
  [railway] тайл 175/482 | +13 (Σ3,978) |    2c | прошло  2.8м · ост.~ 5.0м
  [railway] тайл 176/482 | +66 (Σ4,044) |    2c | прошло  2.9м · ост.~ 5.0м
  [railway] тайл 177/482 | +47 (Σ4,091) |    1c | прошло  2.9м · ост.~ 5.0м
  [railway] тайл 178/482 | +0 (Σ4,091) |    1c | прошло  2.9м · ост.~ 5.0м
  [railway] тайл 179/482 | +31 (Σ4,122) |    1c | прошло  2.9м · ост.~ 5.0м
  [railway] тайл 180/482 | +0 (Σ4,122) |    0c | прошло  2.9м · ост.~ 4.9м
  [railway] тайл 181/482 | +0 (Σ4,122) |    0c | прошло  2.9м · ост.~ 4.9м
  [railway] тайл 182/482 | +0 (Σ4,122) |    0c | прошло  2.9м · ост.~ 4.8м
  [railway] тайл 183/482 | +0 (Σ4,122) |    0c | прошло  3.0м · ост.~ 4.8м
  [railway] тайл 184/482 | +0 (Σ4,122) |    0c | прошло  3.0м · ост.~ 4.8м
  [railway] тайл 185/482 | +0 (Σ4,122) |    0c | прошло  3.0м · ост.~ 4.8м
  [railway] тайл 186/482 | +0 (Σ4,122) |    0c | прошло  3.0м · ост.~ 4.7м
  [railway] тайл 187/482 | +37 (Σ4,159) |    1c | прошло  3.0м · ост.~ 4.7м
  [railway] тайл 188/482 | +53 (Σ4,212) |    1c | прошло  3.0м · ост.~ 4.7м
  [railway] тайл 189/482 | +21 (Σ4,233) |    1c | прошло  3.0м · ост.~ 4.7м
  [railway] тайл 190/482 | +45 (Σ4,278) |    1c | прошло  3.1м · ост.~ 4.7м
  [railway] тайл 191/482 | +85 (Σ4,363) |    2c | прошло  3.1м · ост.~ 4.7м
  [railway] тайл 192/482 | +115 (Σ4,478) |    1c | прошло  3.1м · ост.~ 4.7м
  [railway] тайл 193/482 | +10 (Σ4,488) |    2c | прошло  3.1м · ост.~ 4.7м
  [railway] тайл 194/482 | +37 (Σ4,525) |    2c | прошло  3.2м · ост.~ 4.7м
  [railway] тайл 195/482 | +165 (Σ4,690) |    2c | прошло  3.2м · ост.~ 4.7м
  [railway] тайл 196/482 | +163 (Σ4,853) |    2c | прошло  3.2м · ост.~ 4.7м
  [railway] тайл 197/482 | +657 (Σ5,510) |    2c | прошло  3.3м · ост.~ 4.7м
  [railway] тайл 198/482 | +476 (Σ5,986) |    2c | прошло  3.3м · ост.~ 4.7м
  [railway] тайл 199/482 | +315 (Σ6,301) |    2c | прошло  3.3м · ост.~ 4.7м
  [railway] тайл 200/482 | +153 (Σ6,454) |    2c | прошло  3.3м · ост.~ 4.7м
  [railway] тайл 201/482 | +48 (Σ6,502) |    1c | прошло  3.4м · ост.~ 4.7м
  [railway] тайл 202/482 | +58 (Σ6,560) |    2c | прошло  3.4м · ост.~ 4.7м
  [railway] тайл 203/482 | +86 (Σ6,646) |    2c | прошло  3.4м · ост.~ 4.7м
  [railway] тайл 204/482 | +12 (Σ6,658) |    1c | прошло  3.4м · ост.~ 4.7м
  [railway] тайл 205/482 | +39 (Σ6,697) |    1c | прошло  3.5м · ост.~ 4.7м
  [railway] тайл 206/482 | +37 (Σ6,734) |    1c | прошло  3.5м · ост.~ 4.7м
  [railway] тайл 207/482 | +8 (Σ6,742) |    1c | прошло  3.5м · ост.~ 4.7м
  [railway] тайл 208/482 | +19 (Σ6,761) |    1c | прошло  3.5м · ост.~ 4.7м
  [railway] тайл 209/482 | +57 (Σ6,818) |    1c | прошло  3.6м · ост.~ 4.7м
  [railway] тайл 210/482 | +32 (Σ6,850) |    1c | прошло  3.6м · ост.~ 4.6м
  [railway] тайл 211/482 | +4 (Σ6,854) |    1c | прошло  3.6м · ост.~ 4.6м
  [railway] тайл 212/482 | +0 (Σ6,854) |    0c | прошло  3.6м · ост.~ 4.6м
  [railway] тайл 213/482 | +0 (Σ6,854) |    0c | прошло  3.6м · ост.~ 4.6м
  [railway] тайл 214/482 | +0 (Σ6,854) |    0c | прошло  3.6м · ост.~ 4.5м
  [railway] тайл 215/482 | +0 (Σ6,854) |    0c | прошло  3.6м · ост.~ 4.5м
  [railway] тайл 216/482 | +0 (Σ6,854) |    0c | прошло  3.6м · ост.~ 4.5м
  [railway] тайл 217/482 | +30 (Σ6,884) |    1c | прошло  3.7м · ост.~ 4.5м
  [railway] тайл 218/482 | +103 (Σ6,987) |    1c | прошло  3.7м · ост.~ 4.5м
  [railway] тайл 219/482 | +66 (Σ7,053) |    1c | прошло  3.7м · ост.~ 4.5м
  [railway] тайл 220/482 | +34 (Σ7,087) |    1c | прошло  3.7м · ост.~ 4.4м
  [railway] тайл 221/482 | +112 (Σ7,199) |    2c | прошло  3.8м · ост.~ 4.4м
  [railway] тайл 222/482 | +255 (Σ7,454) |    2c | прошло  3.8м · ост.~ 4.4м
  [railway] тайл 223/482 | +298 (Σ7,752) |    2c | прошло  3.8м · ост.~ 4.4м
  [railway] тайл 224/482 | +444 (Σ8,196) |    2c | прошло  3.8м · ост.~ 4.4м
  [railway] тайл 225/482 | +702 (Σ8,898) |    2c | прошло  3.9м · ост.~ 4.4м
  [railway] тайл 226/482 | +548 (Σ9,446) |    2c | прошло  3.9м · ост.~ 4.4м
  [railway] тайл 227/482 | +453 (Σ9,899) |    2c | прошло  3.9м · ост.~ 4.4м
  [railway] тайл 228/482 | +118 (Σ10,017) |    2c | прошло  4.0м · ост.~ 4.4м
  [railway] тайл 229/482 | +4 (Σ10,021) |    1c | прошло  4.0м · ост.~ 4.4м
  [railway] тайл 230/482 | +0 (Σ10,021) |    0c | прошло  4.0м · ост.~ 4.4м
  [railway] тайл 231/482 | +0 (Σ10,021) |    0c | прошло  4.0м · ост.~ 4.4м
  [railway] тайл 232/482 | +0 (Σ10,021) |    0c | прошло  4.0м · ост.~ 4.3м
  [railway] тайл 233/482 | +0 (Σ10,021) |    0c | прошло  4.0м · ост.~ 4.3м
  [railway] тайл 234/482 | +0 (Σ10,021) |    0c | прошло  4.0м · ост.~ 4.3м
  [railway] тайл 235/482 | +0 (Σ10,021) |    0c | прошло  4.0м · ост.~ 4.2м
  [railway] тайл 236/482 | +8 (Σ10,029) |    1c | прошло  4.1м · ост.~ 4.2м
  [railway] тайл 237/482 | +36 (Σ10,065) |    1c | прошло  4.1м · ост.~ 4.2м
  [railway] тайл 238/482 | +0 (Σ10,065) |    0c | прошло  4.1м · ост.~ 4.2м
  [railway] тайл 239/482 | +0 (Σ10,065) |    0c | прошло  4.1м · ост.~ 4.2м
  [railway] тайл 240/482 | +0 (Σ10,065) |    0c | прошло  4.1м · ост.~ 4.1м
  [railway] тайл 241/482 | +0 (Σ10,065) |    0c | прошло  4.1м · ост.~ 4.1м
  [railway] тайл 242/482 | +0 (Σ10,065) |    0c | прошло  4.1м · ост.~ 4.1м
  [railway] тайл 243/482 | +0 (Σ10,065) |    0c | прошло  4.1м · ост.~ 4.0м
  [railway] тайл 244/482 | +0 (Σ10,065) |    0c | прошло  4.1м · ост.~ 4.0м
  [railway] тайл 245/482 | +0 (Σ10,065) |    0c | прошло  4.1м · ост.~ 4.0м
  [railway] тайл 246/482 | +0 (Σ10,065) |    0c | прошло  4.1м · ост.~ 4.0м
  [railway] тайл 247/482 | +6 (Σ10,071) |    1c | прошло  4.2м · ост.~ 4.0м
  [railway] тайл 248/482 | +28 (Σ10,099) |    1c | прошло  4.2м · ост.~ 3.9м
  [railway] тайл 249/482 | +112 (Σ10,211) |    2c | прошло  4.2м · ост.~ 3.9м
  [railway] тайл 250/482 | +145 (Σ10,356) |    2c | прошло  4.2м · ост.~ 3.9м
  [railway] тайл 251/482 | +140 (Σ10,496) |    2c | прошло  4.3м · ост.~ 3.9м
  [railway] тайл 252/482 | +591 (Σ11,087) |    2c | прошло  4.3м · ост.~ 3.9м
  [railway] тайл 253/482 | +1050 (Σ12,137) |    2c | прошло  4.3м · ост.~ 3.9м
  [railway] тайл 254/482 | +1413 (Σ13,550) |    2c | прошло  4.4м · ост.~ 3.9м
  [railway] тайл 255/482 | +565 (Σ14,115) |    2c | прошло  4.4м · ост.~ 3.9м
  [railway] тайл 256/482 | +94 (Σ14,209) |    2c | прошло  4.4м · ост.~ 3.9м
  [railway] тайл 257/482 | +14 (Σ14,223) |    1c | прошло  4.5м · ост.~ 3.9м
  [railway] тайл 258/482 | +0 (Σ14,223) |    0c | прошло  4.5м · ост.~ 3.9м
  [railway] тайл 259/482 | +0 (Σ14,223) |    0c | прошло  4.5м · ост.~ 3.8м
  [railway] тайл 260/482 | +0 (Σ14,223) |    0c | прошло  4.5м · ост.~ 3.8м
  [railway] тайл 261/482 | +0 (Σ14,223) |    0c | прошло  4.5м · ост.~ 3.8м
  [railway] тайл 262/482 | +0 (Σ14,223) |    0c | прошло  4.5м · ост.~ 3.8м
  [railway] тайл 263/482 | +0 (Σ14,223) |    0c | прошло  4.5м · ост.~ 3.7м
  [railway] тайл 264/482 | +0 (Σ14,223) |    0c | прошло  4.5м · ост.~ 3.7м
  [railway] тайл 265/482 | +0 (Σ14,223) |    0c | прошло  4.5м · ост.~ 3.7м
  [railway] тайл 266/482 | +9 (Σ14,232) |    1c | прошло  4.5м · ост.~ 3.7м

In [19]:
layers["power_lines"] = geo.fetch_layer(points, OSM_CACHE_DIR, "power_lines")

[power_lines] сетка ~5 км: 482 тайлов
  [power_lines] скачиваю 482 тайлов из OSM…
  [power_lines] тайл 1/482 | +79 (Σ79) |    2c | прошло  0.0м · ост.~13.7м
  [power_lines] тайл 2/482 | +266 (Σ345) |    2c | прошло  0.1м · ост.~13.7м
  [power_lines] тайл 3/482 | +3 (Σ348) |    2c | прошло  0.1м · ост.~13.3м
  [power_lines] тайл 4/482 | +170 (Σ518) |    2c | прошло  0.1м · ост.~13.2м
  [power_lines] тайл 5/482 | +61 (Σ579) |    2c | прошло  0.1м · ост.~13.1м
  [power_lines] тайл 6/482 | +19 (Σ598) |    2c | прошло  0.2м · ост.~13.2м
  [power_lines] тайл 7/482 | +1 (Σ599) |    2c | прошло  0.2м · ост.~13.1м
  [power_lines] тайл 8/482 | +124 (Σ723) |    2c | прошло  0.2м · ост.~13.2м
  [power_lines] тайл 9/482 | +104 (Σ827) |    2c | прошло  0.3м · ост.~13.1м
  [power_lines] тайл 10/482 | +86 (Σ913) |    2c | прошло  0.3м · ост.~13.1м
  [power_lines] тайл 11/482 | +85 (Σ998) |    2c | прошло  0.3м · ост.~13.1м
  [power_lines] тайл 12/482 | +177 (Σ1,175) |    2c | прошло  0.3м · ост.~13.0м
  [power_lines] тайл 13/482 | +88 (Σ1,263) |    2c | прошло  0.4м · ост.~13.0м
  [power_lines] тайл 14/482 | +47 (Σ1,310) |    2c | прошло  0.4м · ост.~12.9м
  [power_lines] тайл 15/482 | +65 (Σ1,375) |    2c | прошло  0.4м · ост.~12.9м
  [power_lines] тайл 16/482 | +63 (Σ1,438) |    2c | прошло  0.4м · ост.~12.9м
  [power_lines] тайл 17/482 | +65 (Σ1,503) |    2c | прошло  0.5м · ост.~12.9м
  [power_lines] тайл 18/482 | +78 (Σ1,581) |    2c | прошло  0.5м · ост.~12.8м
  [power_lines] тайл 19/482 | +446 (Σ2,027) |    2c | прошло  0.5м · ост.~12.8м
  [power_lines] тайл 20/482 | +92 (Σ2,119) |    2c | прошло  0.6м · ост.~12.9м
  [power_lines] тайл 21/482 | +36 (Σ2,155) |    2c | прошло  0.6м · ост.~12.8м
  [power_lines] тайл 22/482 | +181 (Σ2,336) |    2c | прошло  0.6м · ост.~12.8м
  [power_lines] тайл 23/482 | +179 (Σ2,515) |    2c | прошло  0.6м · ост.~13.0м
  [power_lines] тайл 24/482 | +13 (Σ2,528) |    2c | прошло  0.7м · ост.~12.9м
  [power_lines] тайл 25/482 | +46 (Σ2,574) |    2c | прошло  0.7м · ост.~12.9м
  [power_lines] тайл 26/482 | +204 (Σ2,778) |  304c | прошло  5.8м · ост.~101.2м
  [power_lines] тайл 27/482 | +38 (Σ2,816) |  286c | прошло 10.5м · ост.~177.6м
  [power_lines] тайл 28/482 | +18 (Σ2,834) |  417c | прошло 17.5м · ост.~283.6м
  [power_lines] тайл 29/482 | +42 (Σ2,876) |   30c | прошло 18.0м · ост.~281.0м
  [power_lines] тайл 30/482 | +93 (Σ2,969) |  198c | прошло 21.3м · ост.~320.8м
  [power_lines] тайл 31/482 | +39 (Σ3,008) |    8c | прошло 21.4м · ост.~311.8м
  [power_lines] тайл 32/482 | +52 (Σ3,060) |    3c | прошло 21.5м · ост.~302.1м
  [power_lines] тайл 33/482 | +52 (Σ3,112) |    2c | прошло 21.5м · ост.~292.7м
  [power_lines] тайл 34/482 | +216 (Σ3,328) |    2c | прошло 21.5м · ост.~283.9м
  [power_lines] тайл 35/482 | +82 (Σ3,410) |   11c | прошло 21.7м · ост.~277.6м
  [power_lines] тайл 36/482 | +21 (Σ3,431) |    2c | прошло 21.8м · ост.~269.6м
  [power_lines] тайл 37/482 | +55 (Σ3,486) |    4c | прошло 21.8м · ост.~262.6м
  [power_lines] тайл 38/482 | +79 (Σ3,565) |    2c | прошло 21.9м · ост.~255.4м
  [power_lines] тайл 39/482 | +39 (Σ3,604) |    5c | прошло 21.9м · ост.~249.2м
  [power_lines] тайл 40/482 | +75 (Σ3,679) |  114c | прошло 23.8м · ост.~263.5м
  [power_lines] тайл 41/482 | +83 (Σ3,762) |  246c | прошло 27.9м · ост.~300.6м
  [power_lines] тайл 42/482 | +0 (Σ3,762) |   26c | прошло 28.4м · ост.~297.3м
  [power_lines] тайл 43/482 | +34 (Σ3,796) |  144c | прошло 30.8м · ост.~314.2м
  [power_lines] тайл 44/482 | +48 (Σ3,844) |  655c | прошло 41.7м · ост.~415.1м
  [power_lines] тайл 45/482 | +120 (Σ3,964) |  139c | прошло 44.0м · ост.~427.4м
  [power_lines] тайл 46/482 | +32 (Σ3,996) |  306c | прошло 49.1м · ост.~465.6м
  [power_lines] тайл 47/482 | +15 (Σ4,011) |   25c | прошло 49.5м · ост.~458.5м
  [power_lines] тайл 48/482 | +116 (Σ4,127) |   30c | прошло 50.0м · ост.~452.5м
  [power_lines] тайл 49/482 | +54 (Σ4,181) |   27c | прошло 50.5м · ост.~446.2м
  [power_lines] тайл 50/482 | +121 (Σ4,302) |   32c | прошло 51.0м · ост.~440.8м
  [power_lines] тайл 51/482 | +42 (Σ4,344) |  153c | прошло 53.6м · ост.~452.7м
  [power_lines] тайл 52/482 | +40 (Σ4,384) |   30c | прошло 54.1м · ост.~447.1м
  [power_lines] тайл 53/482 | +134 (Σ4,518) |   27c | прошло 54.5м · ост.~441.3м
  [power_lines] тайл 54/482 | +33 (Σ4,551) |  299c | прошло 59.5м · ост.~471.6м
  [power_lines] тайл 55/482 | +107 (Σ4,658) |  236c | прошло 63.4м · ост.~492.5м
  [power_lines] тайл 56/482 | +150 (Σ4,808) |    2c | прошло 63.5м · ост.~482.9м
  [power_lines] тайл 57/482 | +59 (Σ4,867) |    3c | прошло 63.5м · ост.~473.6м
  [power_lines] тайл 58/482 | +181 (Σ5,048) |    4c | прошло 63.6м · ост.~464.8м
  [power_lines] тайл 59/482 | +212 (Σ5,260) |    2c | прошло 63.6м · ост.~456.1м
  [power_lines] тайл 60/482 | +345 (Σ5,605) |    2c | прошло 63.6м · ост.~447.6м
  [power_lines] тайл 61/482 | +193 (Σ5,798) |    5c | прошло 63.7м · ост.~439.8м
  [power_lines] тайл 62/482 | +70 (Σ5,868) |    2c | прошло 63.8м · ост.~431.9м
  [power_lines] тайл 63/482 | +72 (Σ5,940) |    2c | прошло 63.8м · ост.~424.2м
  [power_lines] тайл 64/482 | +149 (Σ6,089) |    2c | прошло 63.8м · ост.~416.8м
  [power_lines] тайл 65/482 | +105 (Σ6,194) |    2c | прошло 63.8м · ост.~409.6м
  [power_lines] тайл 66/482 | +47 (Σ6,241) |    2c | прошло 63.9м · ост.~402.6м
  [power_lines] тайл 67/482 | +46 (Σ6,287) |    2c | прошло 63.9м · ост.~395.8м
  [power_lines] тайл 68/482 | +13 (Σ6,300) |    2c | прошло 63.9м · ост.~389.2м
  [power_lines] тайл 69/482 | +73 (Σ6,373) |    2c | прошло 64.0м · ост.~382.8м
  [power_lines] тайл 70/482 | +160 (Σ6,533) |    2c | прошло 64.0м · ост.~376.6м
  [power_lines] тайл 71/482 | +110 (Σ6,643) |    2c | прошло 64.0м · ост.~370.6м
  [power_lines] тайл 72/482 | +41 (Σ6,684) |    2c | прошло 64.0м · ост.~364.7м
  [power_lines] тайл 73/482 | +64 (Σ6,748) |    2c | прошло 64.1м · ост.~359.0м
  [power_lines] тайл 74/482 | +53 (Σ6,801) |    2c | прошло 64.1м · ост.~353.4м
  [power_lines] тайл 75/482 | +119 (Σ6,920) |    2c | прошло 64.1м · ост.~348.0м
  [power_lines] тайл 76/482 | +171 (Σ7,091) |    2c | прошло 64.2м · ост.~342.7м
  [power_lines] тайл 77/482 | +125 (Σ7,216) |    2c | прошло 64.2м · ост.~337.6м
  [power_lines] тайл 78/482 | +30 (Σ7,246) |    2c | прошло 64.2м · ост.~332.6м
  [power_lines] тайл 79/482 | +24 (Σ7,270) |    2c | прошло 64.2м · ост.~327.7м
  [power_lines] тайл 80/482 | +53 (Σ7,323) |    2c | прошло 64.3м · ост.~322.9м
  [power_lines] тайл 81/482 | +200 (Σ7,523) |    2c | прошло 64.3м · ост.~318.3м
  [power_lines] тайл 82/482 | +192 (Σ7,715) |    2c | прошло 64.3м · ост.~313.8м
  [power_lines] тайл 83/482 | +60 (Σ7,775) |    2c | прошло 64.4м · ост.~309.4м
  [power_lines] тайл 84/482 | +61 (Σ7,836) |    2c | прошло 64.4м · ост.~305.1м
  [power_lines] тайл 85/482 | +25 (Σ7,861) |    2c | прошло 64.4м · ост.~300.8м
  [power_lines] тайл 86/482 | +52 (Σ7,913) |    2c | прошло 64.4м · ост.~296.7м
  [power_lines] тайл 87/482 | +211 (Σ8,124) |    2c | прошло 64.5м · ост.~292.7м
  [power_lines] тайл 88/482 | +82 (Σ8,206) |    2c | прошло 64.5м · ост.~288.8м
  [power_lines] тайл 89/482 | +29 (Σ8,235) |    2c | прошло 64.5м · ост.~285.0м
  [power_lines] тайл 90/482 | +134 (Σ8,369) |    2c | прошло 64.6м · ост.~281.2м
  [power_lines] тайл 91/482 | +68 (Σ8,437) |    2c | прошло 64.6м · ост.~277.5м
  [power_lines] тайл 92/482 | +173 (Σ8,610) |    2c | прошло 64.6м · ост.~273.9м
  [power_lines] тайл 93/482 | +104 (Σ8,714) |    2c | прошло 64.6м · ост.~270.4м
  [power_lines] тайл 94/482 | +52 (Σ8,766) |    2c | прошло 64.7м · ост.~266.9м
  [power_lines] тайл 95/482 | +0 (Σ8,766) |    1c | прошло 64.7м · ост.~263.5м
  [power_lines] тайл 96/482 | +33 (Σ8,799) |    2c | прошло 64.7м · ост.~260.2м
  [power_lines] тайл 97/482 | +0 (Σ8,799) |    1c | прошло 64.7м · ост.~256.9м
  [power_lines] тайл 98/482 | +0 (Σ8,799) |    0c | прошло 64.7м · ост.~253.6м
  [power_lines] тайл 99/482 | +31 (Σ8,830) |    2c | прошло 64.8м · ост.~250.5м
  [power_lines] тайл 100/482 | +183 (Σ9,013) |    2c | прошло 64.8м · ост.~247.5м
  [power_lines] тайл 101/482 | +9 (Σ9,022) |    2c | прошло 64.8м · ост.~244.5м
  [power_lines] тайл 102/482 | +89 (Σ9,111) |    2c | прошло 64.8м · ост.~241.6м
  [power_lines] тайл 103/482 | +229 (Σ9,340) |    2c | прошло 64.9м · ост.~238.7м
  [power_lines] тайл 104/482 | +44 (Σ9,384) |    2c | прошло 64.9м · ост.~235.9м
  [power_lines] тайл 105/482 | +8 (Σ9,392) |    2c | прошло 64.9м · ост.~233.2м
  [power_lines] тайл 106/482 | +35 (Σ9,427) |    2c | прошло 65.0м · ост.~230.5м
  [power_lines] тайл 107/482 | +130 (Σ9,557) |    2c | прошло 65.0м · ост.~227.8м
  [power_lines] тайл 108/482 | +50 (Σ9,607) |    2c | прошло 65.0м · ост.~225.2м
  [power_lines] тайл 109/482 | +153 (Σ9,760) |    2c | прошло 65.1м · ост.~222.6м
  [power_lines] тайл 110/482 | +221 (Σ9,981) |    2c | прошло 65.1м · ост.~220.1м
  [power_lines] тайл 111/482 | +172 (Σ10,153) |    2c | прошло 65.1м · ост.~217.7м
  [power_lines] тайл 112/482 | +13 (Σ10,166) |    2c | прошло 65.2м · ост.~215.2м
  [power_lines] тайл 113/482 | +70 (Σ10,236) |    2c | прошло 65.2м · ост.~212.8м
  [power_lines] тайл 114/482 | +52 (Σ10,288) |    2c | прошло 65.2м · ост.~210.5м
  [power_lines] тайл 115/482 | +142 (Σ10,430) |    2c | прошло 65.2м · ост.~208.2м
  [power_lines] тайл 116/482 | +31 (Σ10,461) |    2c | прошло 65.3м · ост.~205.9м
  [power_lines] тайл 117/482 | +64 (Σ10,525) |    2c | прошло 65.3м · ост.~203.7м
  [power_lines] тайл 118/482 | +143 (Σ10,668) |    2c | прошло 65.3м · ост.~201.5м
  [power_lines] тайл 119/482 | +0 (Σ10,668) |    1c | прошло 65.3м · ост.~199.3м
  [power_lines] тайл 120/482 | +106 (Σ10,774) |    2c | прошло 65.4м · ост.~197.2м
  [power_lines] тайл 121/482 | +83 (Σ10,857) |    2c | прошло 65.4м · ост.~195.1м
  [power_lines] тайл 122/482 | +96 (Σ10,953) |    2c | прошло 65.4м · ост.~193.0м
  [power_lines] тайл 123/482 | +54 (Σ11,007) |    2c | прошло 65.4м · ост.~191.0м
  [power_lines] тайл 124/482 | +125 (Σ11,132) |    2c | прошло 65.5м · ост.~189.0м
  [power_lines] тайл 125/482 | +223 (Σ11,355) |    2c | прошло 65.5м · ост.~187.1м
  [power_lines] тайл 126/482 | +42 (Σ11,397) |    2c | прошло 65.5м · ост.~185.2м
  [power_lines] тайл 127/482 | +24 (Σ11,421) |    2c | прошло 65.6м · ост.~183.3м
  [power_lines] тайл 128/482 | +138 (Σ11,559) |    2c | прошло 65.6м · ост.~181.4м
  [power_lines] тайл 129/482 | +102 (Σ11,661) |    2c | прошло 65.6м · ост.~179.6м
  [power_lines] тайл 130/482 | +95 (Σ11,756) |    2c | прошло 65.7м · ост.~177.8м
  [power_lines] тайл 131/482 | +270 (Σ12,026) |    2c | прошло 65.7м · ост.~176.0м
  [power_lines] тайл 132/482 | +40 (Σ12,066) |    2c | прошло 65.7м · ост.~174.3м
  [power_lines] тайл 133/482 | +54 (Σ12,120) |    2c | прошло 65.8м · ост.~172.5м
  [power_lines] тайл 134/482 | +39 (Σ12,159) |    2c | прошло 65.8м · ост.~170.8м
  [power_lines] тайл 135/482 | +102 (Σ12,261) |    2c | прошло 65.8м · ост.~169.2м
  [power_lines] тайл 136/482 | +94 (Σ12,355) |    2c | прошло 65.8м · ост.~167.5м
  [power_lines] тайл 137/482 | +58 (Σ12,413) |    2c | прошло 65.9м · ост.~165.9м
  [power_lines] тайл 138/482 | +72 (Σ12,485) |    2c | прошло 65.9м · ост.~164.3м
  [power_lines] тайл 139/482 | +15 (Σ12,500) |    2c | прошло 65.9м · ост.~162.7м
  [power_lines] тайл 140/482 | +208 (Σ12,708) |    2c | прошло 65.9м · ост.~161.1м
  [power_lines] тайл 141/482 | +76 (Σ12,784) |    2c | прошло 66.0м · ост.~159.6м
  [power_lines] тайл 142/482 | +65 (Σ12,849) |    2c | прошло 66.0м · ост.~158.0м
  [power_lines] тайл 143/482 | +127 (Σ12,976) |    2c | прошло 66.0м · ост.~156.5м
  [power_lines] тайл 144/482 | +49 (Σ13,025) |    2c | прошло 66.1м · ост.~155.1м
  [power_lines] тайл 145/482 | +10 (Σ13,035) |    2c | прошло 66.1м · ост.~153.6м
  [power_lines] тайл 146/482 | +99 (Σ13,134) |    2c | прошло 66.1м · ост.~152.2м
  [power_lines] тайл 147/482 | +57 (Σ13,191) |    2c | прошло 66.2м · ост.~150.8м
  [power_lines] тайл 148/482 | +206 (Σ13,397) |    2c | прошло 66.2м · ост.~149.4м
  [power_lines] тайл 149/482 | +127 (Σ13,524) |    2c | прошло 66.2м · ост.~148.0м
  [power_lines] тайл 150/482 | +174 (Σ13,698) |    2c | прошло 66.3м · ост.~146.6м
  [power_lines] тайл 151/482 | +444 (Σ14,142) |    2c | прошло 66.3м · ост.~145.3м
  [power_lines] тайл 152/482 | +78 (Σ14,220) |    2c | прошло 66.3м · ост.~144.0м
  [power_lines] тайл 153/482 | +111 (Σ14,331) |    2c | прошло 66.3м · ост.~142.7м
  [power_lines] тайл 154/482 | +24 (Σ14,355) |    2c | прошло 66.4м · ост.~141.4м
  [power_lines] тайл 155/482 | +17 (Σ14,372) |    5c | прошло 66.5м · ост.~140.2м
  [power_lines] тайл 156/482 | +1 (Σ14,373) |    2c | прошло 66.5м · ост.~138.9м
  [power_lines] тайл 157/482 | +83 (Σ14,456) |    2c | прошло 66.5м · ост.~137.7м
  [power_lines] тайл 158/482 | +88 (Σ14,544) |    2c | прошло 66.5м · ост.~136.5м
  [power_lines] тайл 159/482 | +134 (Σ14,678) |    2c | прошло 66.6м · ост.~135.2м
  [power_lines] тайл 160/482 | +27 (Σ14,705) |    2c | прошло 66.6м · ост.~134.0м
  [power_lines] тайл 161/482 | +17 (Σ14,722) |    2c | прошло 66.6м · ост.~132.8м
  [power_lines] тайл 162/482 | +144 (Σ14,866) |    2c | прошло 66.7м · ост.~131.7м
  [power_lines] тайл 163/482 | +68 (Σ14,934) |    2c | прошло 66.7м · ост.~130.5м
  [power_lines] тайл 164/482 | +0 (Σ14,934) |    1c | прошло 66.7м · ост.~129.3м
  [power_lines] тайл 165/482 | +49 (Σ14,983) |    2c | прошло 66.7м · ост.~128.2м
  [power_lines] тайл 166/482 | +22 (Σ15,005) |    2c | прошло 66.8м · ост.~127.1м
  [power_lines] тайл 167/482 | +63 (Σ15,068) |    2c | прошло 66.8м · ост.~126.0м
  [power_lines] тайл 168/482 | +240 (Σ15,308) |    2c | прошло 66.8м · ост.~124.9м
  [power_lines] тайл 169/482 | +223 (Σ15,531) |    2c | прошло 66.9м · ост.~123.8м
  [power_lines] тайл 170/482 | +291 (Σ15,822) |    2c | прошло 66.9м · ост.~122.8м
  [power_lines] тайл 171/482 | +88 (Σ15,910) |    2c | прошло 66.9м · ост.~121.7м
  [power_lines] тайл 172/482 | +133 (Σ16,043) |    2c | прошло 67.0м · ост.~120.7м
  [power_lines] тайл 173/482 | +335 (Σ16,378) |    2c | прошло 67.0м · ост.~119.7м
  [power_lines] тайл 174/482 | +257 (Σ16,635) |    2c | прошло 67.0м · ост.~118.7м
  [power_lines] тайл 175/482 | +181 (Σ16,816) |    2c | прошло 67.1м · ост.~117.7м
  [power_lines] тайл 176/482 | +61 (Σ16,877) |    2c | прошло 67.1м · ост.~116.7м
  [power_lines] тайл 177/482 | +113 (Σ16,990) |    2c | прошло 67.1м · ост.~115.7м
  [power_lines] тайл 178/482 | +29 (Σ17,019) |    2c | прошло 67.2м · ост.~114.7м
  [power_lines] тайл 179/482 | +221 (Σ17,240) |    2c | прошло 67.2м · ост.~113.7м
  [power_lines] тайл 180/482 | +86 (Σ17,326) |    2c | прошло 67.2м · ост.~112.8м
  [power_lines] тайл 181/482 | +19 (Σ17,345) |    2c | прошло 67.2м · ост.~111.8м
  [power_lines] тайл 182/482 | +3 (Σ17,348) |    2c | прошло 67.3м · ост.~110.9м
  [power_lines] тайл 183/482 | +24 (Σ17,372) |    2c | прошло 67.3м · ост.~110.0м
  [power_lines] тайл 184/482 | +6 (Σ17,378) |    2c | прошло 67.3м · ост.~109.0м
  [power_lines] тайл 185/482 | +32 (Σ17,410) |    2c | прошло 67.3м · ост.~108.1м
  [power_lines] тайл 186/482 | +35 (Σ17,445) |    2c | прошло 67.4м · ост.~107.2м
  [power_lines] тайл 187/482 | +178 (Σ17,623) |    2c | прошло 67.4м · ост.~106.3м
  [power_lines] тайл 188/482 | +242 (Σ17,865) |    2c | прошло 67.4м · ост.~105.5м
  [power_lines] тайл 189/482 | +113 (Σ17,978) |    2c | прошло 67.5м · ост.~104.6м
  [power_lines] тайл 190/482 | +143 (Σ18,121) |    2c | прошло 67.5м · ост.~103.7м
  [power_lines] тайл 191/482 | +274 (Σ18,395) |    2c | прошло 67.5м · ост.~102.9м
  [power_lines] тайл 192/482 | +81 (Σ18,476) |    2c | прошло 67.6м · ост.~102.0м
  [power_lines] тайл 193/482 | +150 (Σ18,626) |    2c | прошло 67.6м · ост.~101.2м
  [power_lines] тайл 194/482 | +189 (Σ18,815) |    2c | прошло 67.6м · ост.~100.4м
  [power_lines] тайл 195/482 | +118 (Σ18,933) |    2c | прошло 67.7м · ост.~99.6м
  [power_lines] тайл 196/482 | +147 (Σ19,080) |    3c | прошло 67.7м · ост.~98.8м
  [power_lines] тайл 197/482 | +251 (Σ19,331) |    2c | прошло 67.7м · ост.~98.0м
  [power_lines] тайл 198/482 | +345 (Σ19,676) |    3c | прошло 67.8м · ост.~97.2м
  [power_lines] тайл 199/482 | +264 (Σ19,940) |    2c | прошло 67.8м · ост.~96.5м
  [power_lines] тайл 200/482 | +334 (Σ20,274) |    2c | прошло 67.9м · ост.~95.7м
  [power_lines] тайл 201/482 | +115 (Σ20,389) |    2c | прошло 67.9м · ост.~94.9м
  [power_lines] тайл 202/482 | +150 (Σ20,539) |    2c | прошло 67.9м · ост.~94.2м
  [power_lines] тайл 203/482 | +220 (Σ20,759) |    2c | прошло 68.0м · ост.~93.4м
  [power_lines] тайл 204/482 | +91 (Σ20,850) |    2c | прошло 68.0м · ост.~92.7м
  [power_lines] тайл 205/482 | +109 (Σ20,959) |    2c | прошло 68.0м · ост.~91.9м
  [power_lines] тайл 206/482 | +195 (Σ21,154) |    2c | прошло 68.0м · ост.~91.2м
  [power_lines] тайл 207/482 | +107 (Σ21,261) |    2c | прошло 68.1м · ост.~90.4м
  [power_lines] тайл 208/482 | +148 (Σ21,409) |    2c | прошло 68.1м · ост.~89.7м
  [power_lines] тайл 209/482 | +99 (Σ21,508) |    2c | прошло 68.1м · ост.~89.0м
  [power_lines] тайл 210/482 | +78 (Σ21,586) |    2c | прошло 68.2м · ост.~88.3м
  [power_lines] тайл 211/482 | +41 (Σ21,627) |    2c | прошло 68.2м · ост.~87.6м
  [power_lines] тайл 212/482 | +86 (Σ21,713) |    2c | прошло 68.2м · ост.~86.9м
  [power_lines] тайл 213/482 | +22 (Σ21,735) |    2c | прошло 68.2м · ост.~86.2м
  [power_lines] тайл 214/482 | +0 (Σ21,735) |    1c | прошло 68.2м · ост.~85.5м
  [power_lines] тайл 215/482 | +25 (Σ21,760) |    2c | прошло 68.3м · ост.~84.8м
  [power_lines] тайл 216/482 | +93 (Σ21,853) |    2c | прошло 68.3м · ост.~84.1м
  [power_lines] тайл 217/482 | +234 (Σ22,087) |    2c | прошло 68.3м · ост.~83.4м
  [power_lines] тайл 218/482 | +198 (Σ22,285) |    2c | прошло 68.4м · ост.~82.8м
  [power_lines] тайл 219/482 | +220 (Σ22,505) |    2c | прошло 68.4м · ост.~82.1м
  [power_lines] тайл 220/482 | +143 (Σ22,648) |    2c | прошло 68.4м · ост.~81.5м
  [power_lines] тайл 221/482 | +340 (Σ22,988) |    2c | прошло 68.4м · ост.~80.8м
  [power_lines] тайл 222/482 | +122 (Σ23,110) |    2c | прошло 68.5м · ост.~80.2м
  [power_lines] тайл 223/482 | +221 (Σ23,331) |    2c | прошло 68.5м · ост.~79.6м
  [power_lines] тайл 224/482 | +259 (Σ23,590) |    2c | прошло 68.5м · ост.~79.0м
  [power_lines] тайл 225/482 | +495 (Σ24,085) |    2c | прошло 68.6м · ост.~78.3м
  [power_lines] тайл 226/482 | +335 (Σ24,420) |    3c | прошло 68.6м · ост.~77.7м
  [power_lines] тайл 227/482 | +173 (Σ24,593) |    2c | прошло 68.7м · ост.~77.1м
  [power_lines] тайл 228/482 | +321 (Σ24,914) |    2c | прошло 68.7м · ост.~76.5м
  [power_lines] тайл 229/482 | +103 (Σ25,017) |    2c | прошло 68.7м · ост.~75.9м
  [power_lines] тайл 230/482 | +40 (Σ25,057) |    2c | прошло 68.8м · ост.~75.3м
  [power_lines] тайл 231/482 | +16 (Σ25,073) |    2c | прошло 68.8м · ост.~74.7м
  [power_lines] тайл 232/482 | +41 (Σ25,114) |    2c | прошло 68.8м · ост.~74.2м
  [power_lines] тайл 233/482 | +15 (Σ25,129) |    2c | прошло 68.8м · ост.~73.6м
  [power_lines] тайл 234/482 | +32 (Σ25,161) |    2c | прошло 68.9м · ост.~73.0м
  [power_lines] тайл 235/482 | +116 (Σ25,277) |    2c | прошло 68.9м · ост.~72.4м
  [power_lines] тайл 236/482 | +29 (Σ25,306) |    2c | прошло 68.9м · ост.~71.9м
  [power_lines] тайл 237/482 | +160 (Σ25,466) |    2c | прошло 69.0м · ост.~71.3м
  [power_lines] тайл 238/482 | +165 (Σ25,631) |    2c | прошло 69.0м · ост.~70.7м
  [power_lines] тайл 239/482 | +74 (Σ25,705) |    2c | прошло 69.0м · ост.~70.2м
  [power_lines] тайл 240/482 | +51 (Σ25,756) |    2c | прошло 69.0м · ост.~69.6м
  [power_lines] тайл 241/482 | +0 (Σ25,756) |    1c | прошло 69.1м · ост.~69.1м
  [power_lines] тайл 242/482 | +1 (Σ25,757) |    2c | прошло 69.1м · ост.~68.5м
  [power_lines] тайл 243/482 | +3 (Σ25,760) |    2c | прошло 69.1м · ост.~68.0м
  [power_lines] тайл 244/482 | +67 (Σ25,827) |    2c | прошло 69.1м · ост.~67.4м
  [power_lines] тайл 245/482 | +33 (Σ25,860) |    2c | прошло 69.2м · ост.~66.9м

### Сборка слоёв

Дочитываем все слои из кэша (готовые — мгновенно, без сети), чтобы `build_features`
получил полный набор даже если отдельные ячейки выше не запускались.

In [20]:
layers = geo.fetch_all_layers(points, OSM_CACHE_DIR)
print()
for name, gdf in layers.items():
    print(f"  {name:14} {len(gdf):>8,} объектов")

Сетка ~10 км: 164 тайлов
Сетка ~5 км: 482 тайлов

  metro            22,555 объектов
  schools           9,266 объектов
  green            99,377 объектов
  water            36,028 объектов
  industrial       22,285 объектов
  cemetery            913 объектов
  power_lines      46,941 объектов
  major_roads      40,495 объектов
  railway          19,550 объектов

## 3. Расчёт геофич

- **Расстояния** до ближайшего объекта: метро, школы, вода, промзона, кладбище, ЛЭП, крупная дорога, ж/д.
- **Счётчики** POI в кольцах (школы), **доли площади** (зелень/вода/промзона/кладбище),
  **длины** линий (дороги/ж/д/ЛЭП) и **плотность соседних ЖК** — по кольцам 500/1000/2000 м.

In [21]:
geo_feats = geo.build_features(points, layers, rings=geo.RINGS)
print(f"Геофич: {geo_feats.shape[1]} | проектов: {geo_feats.shape[0]}")
display(geo_feats.head())
print("\nОписательная статистика:")
display(geo_feats.describe().T[["mean", "min", "50%", "max"]].round(2))

Геофич: 35 | проектов: 752

,dist_to_metro_m,dist_to_school_m,dist_to_water_m,dist_to_industrial_m,dist_to_cemetery_m,dist_to_power_line_m,dist_to_major_road_m,dist_to_railway_m,schools_count_500m,schools_count_1000m,schools_count_2000m,green_share_500m,green_share_1000m,green_share_2000m,water_share_500m,water_share_1000m,water_share_2000m,industrial_share_500m,industrial_share_1000m,industrial_share_2000m,cemetery_share_500m,cemetery_share_1000m,cemetery_share_2000m,major_roads_length_500m,major_roads_length_1000m,major_roads_length_2000m,railway_length_500m,railway_length_1000m,railway_length_2000m,power_lines_length_500m,power_lines_length_1000m,power_lines_length_2000m,nearby_complexes_count_500m,nearby_complexes_count_1000m,nearby_complexes_count_2000m
project_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
551,190.247540,30.714609,661.140915,418.341852,4275.658116,421.647674,159.154735,225.802843,10,30,72,0.105312,0.223349,0.164918,0.000000,0.111986,0.125104,0.006945,0.006512,0.088559,0.0,0.0,0.000000,10070.552928,19038.209902,33517.469159,1633.714755,3715.342768,15163.103916,0.000000,0.000000,0.000000,0,1,11
676,88.324525,62.800377,273.029962,313.759172,3815.389005,313.759172,476.857707,828.813657,11,33,86,0.140036,0.119793,0.208946,0.000000,0.000000,0.092523,0.000048,0.008604,0.091934,0.0,0.0,0.000000,655.987379,14117.019478,30425.794551,0.000000,2835.141365,11543.737055,0.000000,0.000000,0.000000,1,3,12
683,361.790991,308.993178,81.331186,223.651401,3853.174785,1046.170695,940.523005,1435.388139,2,2,5,0.260974,0.087225,0.071654,0.005868,0.005419,0.005649,0.028414,0.061489,0.105868,0.0,0.0,0.000000,0.000000,508.472741,11067.608115,0.000000,0.000000,14993.814115,0.000000,0.000000,0.000000,0,0,1
688,98.273968,107.512755,369.183725,246.960404,2349.284559,357.399015,474.290722,1356.008722,4,14,25,0.055673,0.212474,0.343713,0.011617,0.012290,0.007083,0.045839,0.059854,0.050422,0.0,0.0,0.000000,325.420219,3184.444580,35081.739787,0.000000,0.000000,18238.885551,937.405965,3412.747056,7349.619076,1,2,5
696,114.080661,103.104423,812.219817,252.465171,1801.262631,252.465171,476.177470,2522.634618,6,16,22,0.135891,0.339055,0.554714,0.000000,0.001791,0.004117,0.000297,0.021398,0.021169,0.0,0.0,0.002287,194.866970,3592.102116,22141.559358,0.000000,0.000000,0.000000,0.000000,2048.751567,3395.762762,0,0,1

Описательная статистика:

                                  mean    min       50%        max
dist_to_metro_m                 373.28   9.34    212.45    7465.97
dist_to_school_m                312.93   0.00    194.72    5153.65
dist_to_water_m                 361.98   1.00    305.69    1504.57
dist_to_industrial_m            170.74   0.00    114.12    1677.27
dist_to_cemetery_m             1771.08  38.91   1647.77    5564.23
dist_to_power_line_m            278.14   0.32    198.27    1857.18
dist_to_major_road_m            401.76   6.36    283.22    3693.77
dist_to_railway_m               979.99   1.30    486.03   12009.48
schools_count_500m                3.92   0.00      3.00      19.00
schools_count_1000m              13.22   0.00     12.00      46.00
schools_count_2000m              48.13   0.00     49.00     142.00
green_share_500m                  0.17   0.00      0.11       0.89
green_share_1000m                 0.22   0.00      0.17       1.01
green_share_2000m                 0.28   0.03      0.25       1.09
water_share_500m                  0.02   0.00      0.00       0.54
water_share_1000m                 0.03   0.00      0.01       0.42
water_share_2000m                 0.03   0.00      0.01       0.27
industrial_share_500m             0.12   0.00      0.07       0.90
industrial_share_1000m            0.12   0.00      0.09       0.54
industrial_share_2000m            0.12   0.00      0.10       0.40
cemetery_share_500m               0.00   0.00      0.00       0.34
cemetery_share_1000m              0.01   0.00      0.00       0.27
cemetery_share_2000m              0.01   0.00      0.00       0.10
major_roads_length_500m        1640.82   0.00   1227.20   11054.67
major_roads_length_1000m       6755.26   0.00   5868.28   25702.13
major_roads_length_2000m      26545.57   0.00  25666.87   72810.71
railway_length_500m            2474.87   0.00    285.55   29406.72
railway_length_1000m          10779.20   0.00   4936.85  108683.83
railway_length_2000m          39497.27   0.00  25340.74  238293.82
power_lines_length_500m         431.53   0.00      0.00    5394.25
power_lines_length_1000m       1884.66   0.00    642.80   15790.41
power_lines_length_2000m       7500.76   0.00   5129.75   47567.06
nearby_complexes_count_500m       0.56   0.00      0.00       5.00
nearby_complexes_count_1000m      1.72   0.00      1.00       9.00
nearby_complexes_count_2000m      5.24   0.00      4.00      22.00

## 4. Сохранение

`geo_features.parquet` индексирован по `project_id`; в `04_features` мерджится
в модельный датасет.

In [22]:
GEO_FEATURES_PARQUET.parent.mkdir(parents=True, exist_ok=True)
geo_feats.to_parquet(GEO_FEATURES_PARQUET)
print(f"Сохранено: {GEO_FEATURES_PARQUET}")
print(f"  {geo_feats.shape[0]} проектов x {geo_feats.shape[1]} геофич")
print("\nNaN% по геофичам:")
display((100 * geo_feats.isna().mean()).round(1).sort_values(ascending=False).head(10).to_frame("NaN%"))

Сохранено: /Users/adesayan/demand_elasticity/data/processed/geo_features.parquet
  752 проектов x 35 геофич

NaN% по геофичам:

                          NaN%
dist_to_metro_m            0.0
railway_length_500m        0.0
cemetery_share_500m        0.0
cemetery_share_1000m       0.0
cemetery_share_2000m       0.0
major_roads_length_500m    0.0
major_roads_length_1000m   0.0
major_roads_length_2000m   0.0
railway_length_1000m       0.0
industrial_share_1000m     0.0